### ISSUE TITLE
python fit throws ufunc 'isfinite' type error

### ISSUE THREAD

**Issue by dongxiaotian** [facebook/prophet#1081]
when using fit method, get error like this:
------------------------------------------------------------------------------------------
Traceback (most recent call last):
  File "...\anaconda3\lib\site-packages\pandas\core\nanops.py", line 127, in f
    result = alt(values, axis=axis, skipna=skipna, **kwds)
  File "...\anaconda3\lib\site-packages\pandas\core\nanops.py", line 731, in reduction
    values, skipna, fill_value_typ=fill_value_typ, mask=mask)
  File "...\anaconda3\lib\site-packages\pandas\core\nanops.py", line 223, in _get_values
    mask = isna(values)
  File "...\anaconda3\lib\site-packages\pandas\core\dtypes\missing.py", line 99, in isna
    return _isna(obj)
  File "...\anaconda3\lib\site-packages\pandas\core\dtypes\missing.py", line 142, in _isna_old
    return _isna_ndarraylike_old(obj)
  File "...\anaconda3\lib\site-packages\pandas\core\dtypes\missing.py", line 249, in _isna_ndarraylike_old
    result = ~np.isfinite(values)
TypeError: ufunc 'isfinite' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule ''safe''
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "...\anaconda3\lib\site-packages\IPython\core\interactiveshell.py", line 3296, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-23-90e33aac0955>", line 9, in <module>
    m = Prophet().fit(df)
  File "...\anaconda3\lib\site-packages\fbprophet\forecaster.py", line 1059, in fit
    self.set_auto_seasonalities()
  File "...\anaconda3\lib\site-packages\fbprophet\forecaster.py", line 910, in set_auto_seasonalities
    min_dt = dt.iloc[dt.values.nonzero()[0]].min()
  File "...\anaconda3\lib\site-packages\pandas\core\generic.py", line 10956, in stat_func
    numeric_only=numeric_only)
  File "...\anaconda3\lib\site-packages\pandas\core\series.py", line 3630, in _reduce
    return op(delegate, skipna=skipna, **kwds)
  File "...\anaconda3\lib\site-packages\pandas\core\nanops.py", line 130, in f
    result = alt(values, axis=axis, skipna=skipna, **kwds)
  File "...\anaconda3\lib\site-packages\pandas\core\nanops.py", line 731, in reduction
    values, skipna, fill_value_typ=fill_value_typ, mask=mask)
  File "...\anaconda3\lib\site-packages\pandas\core\nanops.py", line 223, in _get_values
    mask = isna(values)
  File "...\anaconda3\lib\site-packages\pandas\core\dtypes\missing.py", line 99, in isna
    return _isna(obj)
  File "...\anaconda3\lib\site-packages\pandas\core\dtypes\missing.py", line 142, in _isna_old
    return _isna_ndarraylike_old(obj)
  File "...\anaconda3\lib\site-packages\pandas\core\dtypes\missing.py", line 249, in _isna_ndarraylike_old
    result = ~np.isfinite(values)
TypeError: ufunc 'isfinite' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule ''safe''
--------------------------------------------------------------------------------

for simplicity, this code can reproduce my error:
df = pd.DataFrame({
    'ds': pd.to_datetime([
        '2001-01-01',
        '2001-01-02',
        '2001-01-03',
    ]),
    'y': [1., 2., 1.],
})
m = Prophet().fit(df)

platform info:
windows 7
python 3.7.3
fbprophet 0.5
pandas 0.24.2
numpy 1.16.2

I figured something was wrong when installing fbprophet package, and tried to reinstall anaconda and fbprophet, but still got this error and can't use prophet package. please help.

**Comment by seriousmac** [comment]
For me, that code doesn't make any errors. I think you should show the installation error.

**Comment by bletham** [comment]
We've previously had similar issues with old versions of pandas, but 0.24.2 should work. I installed those same versions of numpy and pandas and did not get this error when running that code.

Could you try running just this pandas code to see if it isolates the issue?
```
import pandas as pd

df = pd.DataFrame({
'ds': pd.to_datetime([
'2001-01-01',
'2001-01-01',
'2001-01-02',
'2001-01-03',
]),
'y': [1., 2., 1., 2.],
})
dt = df['ds'].diff()
min_dt = dt.iloc[dt.values.nonzero()[0]].min()
```
That would be very helpful to know if that produces the error for you.

**Comment by dongxiaotian** [comment]
> We've previously had similar issues with old versions of pandas, but 0.24.2 should work. I installed those same versions of numpy and pandas and did not get this error when running that code.
> 
> Could you try running just this pandas code to see if it isolates the issue?
> 
> ```
> import pandas as pd
> 
> df = pd.DataFrame({
> 'ds': pd.to_datetime([
> '2001-01-01',
> '2001-01-01',
> '2001-01-02',
> '2001-01-03',
> ]),
> 'y': [1., 2., 1., 2.],
> })
> dt = df['ds'].diff()
> min_dt = dt.iloc[dt.values.nonzero()[0]].min()
> ```
> 
> That would be very helpful to know if that produces the error for you.

thanks for giving help. I tried this code and everthing goes fine, no error throws. And then I import prophet again and surprisingly find that i can use fit method now. I don't know what might caught this issue but am happy to see it works again in my computer. Thank you!

**Comment by bletham** [comment]
Very strange, but glad to hear it's working now!
