### ISSUE TITLE
Failed building wheel for fbprophet on Google App Engine (GAE)

### ISSUE THREAD

**Issue by complyxm** [facebook/prophet#1086]
I tried to deploy app to project on Google App Engine(GAE) but it failed. 
This setting worked well in my local environment. Does anyone know its solution? 

## Error log
Error log tells that there are `Failed building wheel for fbprophet` and `ModuleNotFoundError: No module named 'pystan'`
```
Step #1 - "builder": File "/tmp/pip-wheel-5327wz7q/fbprophet/setup.py", line 44, in run
Step #1 - "builder": build_stan_model(target_dir)
Step #1 - "builder": File "/tmp/pip-wheel-5327wz7q/fbprophet/setup.py", line 27, in build_stan_model
Step #1 - "builder": from pystan import StanModel
Step #1 - "builder": ModuleNotFoundError: No module named 'pystan'
Step #1 - "builder": 
Step #1 - "builder": ----------------------------------------
Step #1 - "builder": Running setup.py clean for fbprophet
Step #1 - "builder": Building wheel for ephem (setup.py): started
Step #1 - "builder": Building wheel for ephem (setup.py): finished with status 'done'
Step #1 - "builder": Stored in directory: /tmp/tmp4LWGoL/wheel
Step #1 - "builder": Building wheel for googleapis-common-protos (setup.py): started
Step #1 - "builder": Building wheel for googleapis-common-protos (setup.py): finished with status 'done'
Step #1 - "builder": Stored in directory: /tmp/tmp4LWGoL/wheel
Step #1 - "builder": Successfully built holidays ephem googleapis-common-protos
Step #1 - "builder": Failed to build fbprophet
Step #1 - "builder": 
Step #1 - "builder": INFO `pip_download_wheels` had stderr output:
Step #1 - "builder": Failed building wheel for fbprophet
Step #1 - "builder": ERROR: Failed to build one or more wheels
Step #1 - "builder": 
Step #1 - "builder": ERROR error: `pip_download_wheels` returned code: 1
Step #1 - "builder": INFO pip_download_wheels took 27 seconds
Step #1 - "builder": INFO build process for FTL image took 32 seconds
Step #1 - "builder": INFO full build took 32 seconds
Step #1 - "builder": ERROR `pip_download_wheels` had stderr output:
Step #1 - "builder": Failed building wheel for fbprophet
Step #1 - "builder": ERROR: Failed to build one or more wheels
Step #1 - "builder": 
Step #1 - "builder": error: `pip_download_wheels` returned code: 1
Step #1 - "builder": Traceback (most recent call last):
Step #1 - "builder": File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
Step #1 - "builder": "__main__", fname, loader, pkg_name)
Step #1 - "builder": File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
Step #1 - "builder": exec code in run_globals
Step #1 - "builder": File "/usr/local/bin/ftl.par/__main__.py", line 65, in <module>
Step #1 - "builder": File "/usr/local/bin/ftl.par/__main__.py", line 57, in main
Step #1 - "builder": File "/usr/local/bin/ftl.par/__main__/ftl/common/ftl_error.py", line 58, in UserErrorHandler
Step #1 - "builder": IOError: [Errno 2] No such file or directory: '""/output'
Finished Step #1 - "builder"
ERROR
ERROR: build step 1 "gcr.io/gae-runtimes/python37_app_builder:python37_20190527_3_7_3_RC00" failed: exit status 1
```

### app.yaml
```
runtime: python37
```

### requirement.txt 
As follows. Only if I add `fbprophet`, build failed. As many cases show, I could install pystan and Cython if there's no `fbprophet`, too.
```
Flask==1.0.2
Werkzeug>=0.14
gunicorn
requests
google-cloud-firestore

Cython>=0.22
pystan>=2.14
numpy>=1.10.0
pandas>=0.23.4
matplotlib>=2.0.0
lunardate>=0.1.5
convertdate>=2.1.2
holidays>=0.9.5
fbprophet
```

Regards,

**Comment by complyxm** [comment]
The original cause of this error was here.
```
Step #1 - "builder": pkg_resources.ContextualVersionConflict: (pbr 5.4.1 (/tmp/pip-wheel-uvkyf9xp/fbprophet/.eggs/pbr-5.4.1-py3.7.egg), Requirement.parse('pbr<5,>=4.0'), {'httpstan'})
```
pbr 4.0 allows only python2, so I should set runtime python27.
When I use python27, it worked. 

```
ERROR: build step 1 "gcr.io/ga…/python37_app_builder:python37_20190527_3_7_3_RC00" failed: exit status 1
ERROR
Finished Step #1 - "builder"
Step #1 - "builder": IOError: [Errno 2] No such file or directory: '""/output'
Step #1 - "builder": File "/usr/local/bin/ftl.par/__main__/ftl/common/ftl_error.py", line 58, in UserErrorHandler
Step #1 - "builder": File "/usr/local/bin/ftl.par/__main__.py", line 57, in main
Step #1 - "builder": File "/usr/local/bin/ftl.par/__main__.py", line 65, in <module>
Step #1 - "builder": exec code in run_globals
Step #1 - "builder": File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
Step #1 - "builder": "__main__", fname, loader, pkg_name)
Step #1 - "builder": File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
Step #1 - "builder": Traceback (most recent call last):
Step #1 - "builder": error: `pip_download_wheels` returned code: 1
Step #1 - "builder": 
Step #1 - "builder": Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-wheel-uvkyf9xp/fbprophet/
Step #1 - "builder": ERROR `pip_download_wheels` had stderr output:
Step #1 - "builder": INFO full build took 118 seconds
Step #1 - "builder": INFO build process for FTL image took 118 seconds
Step #1 - "builder": INFO pip_download_wheels took 108 seconds
Step #1 - "builder": ERROR error: `pip_download_wheels` returned code: 1
Step #1 - "builder": 
Step #1 - "builder": Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-wheel-uvkyf9xp/fbprophet/
Step #1 - "builder": INFO `pip_download_wheels` had stderr output:
Step #1 - "builder": 
Step #1 - "builder": ----------------------------------------
Step #1 - "builder":
Step #1 - "builder": pkg_resources.ContextualVersionConflict: (pbr 5.4.1 (/tmp/pip-wheel-uvkyf9xp/fbprophet/.eggs/pbr-5.4.1-py3.7.egg), Requirement.parse('pbr<5,>=4.0'), {'httpstan'})
Step #1 - "builder": raise VersionConflict(dist, req).with_context(dependent_req)
Step #1 - "builder": File "/env/lib/python3.7/site-packages/pkg_resources/__init__.py", line 791, in resolve
Step #1 - "builder": replace_conflicting=True,
Step #1 - "builder": File "/env/lib/python3.7/site-packages/setuptools/dist.py", line 724, in fetch_build_eggs
Step #1 - "builder": dist.fetch_build_eggs(dist.setup_requires)
Step #1 - "builder": File "/env/lib/python3.7/site-packages/setuptools/__init__.py", line 139, in _install_setup_requires
Step #1 - "builder": _install_setup_requires(attrs)
Step #1 - "builder": File "/env/lib/python3.7/site-packages/setuptools/__init__.py", line 144, in setup
Step #1 - "builder": """
Step #1 - "builder": File "/tmp/pip-wheel-uvkyf9xp/fbprophet/setup.py", line 96, in <module>
Step #1 - "builder": File "<string>", line 1, in <module>
Step #1 - "builder": Traceback (most recent call last):
Step #1 - "builder": Installed /tmp/pip-wheel-uvkyf9xp/fbprophet/.eggs/protobuf-3.9.0-py3.7-linux-x86_64.egg
```
