### ISSUE TITLE
Value Error: Length of passed values is 1491, index implies 34 - while calling .predict() function using FB Prophet

### ISSUE THREAD

**Issue by rahangels11** [facebook/prophet#1364]
`visits = visits.rename(columns={'Day': 'ds', 'SEO.Visits':'y'})
print(visits.head())
visits_prophet = Prophet(daily_seasonality=True, changepoint_prior_scale=0.15)
visits_prophet.fit(visits)
visits_forecast = visits_prophet.make_future_dataframe(periods=365, freq='D')
print(visits_forecast.tail())
visits_forecast = visits_prophet.predict(visits_forecast) 
`

When running the last line I get this full error message:

visits_forecast = visits_prophet.predict(visits_forecast) 
Traceback (most recent call last):

  File "<ipython-input-26-3fd13d516a84>", line 1, in <module>
    visits_forecast = visits_prophet.predict(visits_forecast)

  File "C:\Users\rharris\AppData\Local\Continuum\anaconda2\lib\site-packages\fbprophet\forecaster.py", line 1042, in predict
    intervals = self.predict_uncertainty(df)

  File "C:\Users\rharris\AppData\Local\Continuum\anaconda2\lib\site-packages\fbprophet\forecaster.py", line 1244, in predict_uncertainty
    sim_values = self.sample_posterior_predictive(df)

  File "C:\Users\rharris\AppData\Local\Continuum\anaconda2\lib\site-packages\fbprophet\forecaster.py", line 1208, in sample_posterior_predictive
    s_m=component_cols['multiplicative_terms'],

  File "C:\Users\rharris\AppData\Local\Continuum\anaconda2\lib\site-packages\fbprophet\forecaster.py", line 1276, in sample_model
    Xb_a = np.matmul(seasonal_features.values, beta * s_a) * self.y_scale

  File "C:\Users\rharris\AppData\Local\Continuum\anaconda2\lib\site-packages\pandas\core\series.py", line 735, in __array_wrap__
    copy=False).__finalize__(self)

  File "C:\Users\rharris\AppData\Local\Continuum\anaconda2\lib\site-packages\pandas\core\series.py", line 249, in __init__
    .format(val=len(data), ind=len(index)))

ValueError: Length of passed values is 1491, index implies 34

<img width="297" alt="visits df" src="https://user-images.githubusercontent.com/61517209/75377496-95844100-5897-11ea-9cd2-f293022eea61.PNG">
<img width="294" alt="visits forecast df" src="https://user-images.githubusercontent.com/61517209/75377498-961cd780-5897-11ea-9d32-cad1b081adfc.PNG">

Versions I'm Using:
pystan - 2.14.0.0
fbprophet - 0.3
numpy - 1.16.5

Spyder via Anaconda Navigator

**Comment by davidgibsonp** [comment]
Try updating to Anaconda 3 :)

**Comment by bletham** [comment]
@rahangels11 0.3 is a very old version of fbprophet, that has incompatabilities with newer versions of numpy/pandas. This particular error happens for old versions of fbprophet when numpy >= 1.16.0 (see #808). You need to upgrade to at least fbprophet>=0.4.post2, but even better would be to upgrade to the latest version (0.6). (If for whatever reason that isn't possible, you can downgrade numpy to 1.15.4).

**Comment by rahangels11** [comment]
Thanks to you both @davidgibsonp @bletham . 

I've got this working now by updating anaconda
