### ISSUE TITLE
RuntimeError: Initialization failed

### ISSUE THREAD

**Issue by chenchun** [facebook/prophet#1401]
```
                      ds          y
0    2020-03-13 09:40:00  11.363880
1    2020-03-13 09:42:00  11.369476
2    2020-03-13 09:44:00  11.139097
3    2020-03-13 09:46:00  10.971853
4    2020-03-13 09:48:00  11.366969
...                  ...        ...
4769 2020-03-20 03:30:00  -0.749387
4770 2020-03-20 03:44:00  -0.732993
4771 2020-03-20 03:46:00  -1.426140
4772 2020-03-20 04:00:00  -0.749387
4773 2020-03-20 04:14:00  -0.741156

[4774 rows x 2 columns]
/usr/local/lib/python3.6/site-packages/fbprophet/forecaster.py:439: RuntimeWarning:

divide by zero encountered in true_divide

/usr/local/lib/python3.6/site-packages/fbprophet/forecaster.py:439: RuntimeWarning:

invalid value encountered in sin

/usr/local/lib/python3.6/site-packages/fbprophet/forecaster.py:439: RuntimeWarning:

invalid value encountered in cos

Rejecting initial value:
  Error evaluating the log probability at the initial value.
Exception: normal_lpdf: Location parameter[1] is -nan, but must be finite!  (in 'unknown file name' at line 117)


Initialization between (-2, 2) failed after 1 attempts. 
 Try specifying initial values, reducing ranges of constrained values, or reparameterizing the model.
WARNING:fbprophet:Optimization terminated abnormally. Falling back to Newton.
Rejecting initial value:
  Error evaluating the log probability at the initial value.
Exception: normal_lpdf: Location parameter[1] is -nan, but must be finite!  (in 'unknown file name' at line 117)


Initialization between (-2, 2) failed after 1 attempts. 
 Try specifying initial values, reducing ranges of constrained values, or reparameterizing the model.
ERROR: Initialization failed.
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/fbprophet/models.py", line 242, in fit
    params = self.model.optimizing(**args)
  File "/usr/local/lib/python3.6/site-packages/pystan/model.py", line 581, in optimizing
    ret, sample = fit._call_sampler(stan_args)
  File "stanfit4anon_model_888a84912910fa0a45b9d614b75bb8a8_963130691116402448.pyx", line 1046, in stanfit4anon_model_888a84912910fa0a45b9d614b75bb8a8_963130691116402448.StanFit4Model._call_sampler
  File "stanfit4anon_model_888a84912910fa0a45b9d614b75bb8a8_963130691116402448.pyx", line 406, in stanfit4anon_model_888a84912910fa0a45b9d614b75bb8a8_963130691116402448._call_sampler
RuntimeError: Initialization failed.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/prophet/worker.py", line 49, in run
    result = self.__predict()
  File "/prophet/worker.py", line 81, in __predict
    result[typ] = Prophet(data, index, history.sampling_interval, self.__predict_period, typ).run()
  File "/prophet/prophet.py", line 122, in run
    return self.__predict()
  File "/prophet/prophet.py", line 96, in __predict
    m.fit(df)
  File "/usr/local/lib/python3.6/site-packages/fbprophet/forecaster.py", line 1141, in fit
    self.params = self.stan_backend.fit(stan_init, dat, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/fbprophet/models.py", line 249, in fit
    params = self.model.optimizing(**args)
  File "/usr/local/lib/python3.6/site-packages/pystan/model.py", line 581, in optimizing
    ret, sample = fit._call_sampler(stan_args)
  File "stanfit4anon_model_888a84912910fa0a45b9d614b75bb8a8_963130691116402448.pyx", line 1046, in stanfit4anon_model_888a84912910fa0a45b9d614b75bb8a8_963130691116402448.StanFit4Model._call_sampler
  File "stanfit4anon_model_888a84912910fa0a45b9d614b75bb8a8_963130691116402448.pyx", line 406, in stanfit4anon_model_888a84912910fa0a45b9d614b75bb8a8_963130691116402448._call_sampler
RuntimeError: Initialization failed.
```

How should I fix this error ? The following is my code.

```python
        seasonality_list = self.__seasonality_list()
        daily_seasonality, weekly_seasonality = False, False
        for period in seasonality_list:
            if is_daily(period.period):
                daily_seasonality = True
            if is_weekly(period.period):
                weekly_seasonality = True
        seasonality_list = list(filter(lambda x: not (is_daily(x.period) or is_weekly(x.period)), seasonality_list))

        m = fbprophet.Prophet(yearly_seasonality=False,
                              daily_seasonality=daily_seasonality,
                              weekly_seasonality=weekly_seasonality)
        for i in range(len(seasonality_list)):
            m.add_seasonality(name=str(seasonality_list[i].period),
                              period=seasonality_list[i].period,
                              prior_scale=seasonality_list[i].power * vars.MAX_PRIOR_SCALE,
                              fourier_order=int(round(seasonality_list[i].power * vars.MAX_FOURIER_ORDER)))

        df = pd.DataFrame({'ds': self.__index, 'y': np.log(self.__data)})
        print("%s" % df)
        m.fit(df)
        future = m.make_future_dataframe(periods=self.__periods, freq='min')
        forecast = m.predict(future)
```

**Comment by bletham** [comment]
This is the place in code throwing the divide by zero error:
https://github.com/facebook/prophet/blob/d9bea6196981bfcedae40525e702d424d26e7cd0/python/fbprophet/forecaster.py#L437-L439
so it seems that `period` is being set to 0. I don't see your list of periods, but I guess one of them is 0?

**Comment by chenchun** [comment]
Thanks, I deleted the period which equal 0, it works now.

**Comment by pramodty** [comment]
ds                          tar           zen                id              y
8339 2019-04-03        N6C  abc bd 4.0       NYDA105-06  2
8364 2019-04-03        N6C  abc bd 4.0       NYDA105-06  1
8415 2019-04-03        N6C  abc bd 4.0       NYDA105-06  2
8465 2019-04-03        N6C  abc bd 4.0       NYDA105-06  1
8553 2019-04-03        N6C  abc bd 4.0       NYDA105-06  1
9375 2019-04-03        N6C  abc bd 4.0       NYDA105-06  1
8696 2019-04-03        N6C  abc bd 4.0       NYDA105-06  1
8940 2019-04-03        N6C  abc bd 4.0       NYDA105-06  2
8996 2019-04-03        N6C  abc bd 4.0       NYDA105-06  1
8998 2019-04-03        N6C  abc bd 4.0       NYDA105-06  1
9137 2019-04-03        N6C  abc bd 4.0       NYDA105-06  1
9162 2019-04-03        N6C  abc bd 4.0       NYDA105-06  1
9285 2019-04-03        N6C  abc bd 4.0       NYDA105-06  1
9301 2019-04-03        N6C  abc bd 4.0       NYDA105-06  1
9303 2019-04-03        N6C  abc bd 4.0       NYDA105-06  1
8826 2019-04-03        N6C  abc bd 4.0       NYDA105-06  1
9796 2019-04-03        N6C  abc bd 4.0       NYDA105-06  1


.
.
.
I have data like this.While passing this data to m.fit(data) getting error like above mentioned.
How should I fix this error ?

**Comment by pramodty** [comment]
![image](https://user-images.githubusercontent.com/28916110/87031563-ecfccb00-c200-11ea-996b-3564f1ab8f55.png)
