### ISSUE TITLE
RHEL 8.1: pystan installs but won't compile anything

### ISSUE THREAD

**Issue by sbonds** [facebook/prophet#1403]
I was unable to get any version of pystan working on RHEL 8.1 even with the up-to-the-minute latest version of gcc and gcc-g++.

Test code from #1057 was used to test that pystan was actually working since it seems to install fine even when it won't actually work.

The code:

```python
import pystan
model_code = 'parameters {real y;} model {y ~ normal(0,1);}'
model = pystan.StanModel(model_code=model_code)  # this will take a minute
y = model.sampling(n_jobs=1).extract()['y']
y.mean()  # should be close to 0
```

The environment:

Azure RHEL8.1LVM VM

As root install python and needed compilers:

```bash
# yum install gcc gcc-c++ python36
# python3 --version
Python 3.6.8
```

Set up a virtual environment and install pystan:

```bash
$ vi ~/pystan-test.py
<above test code goes in there>
$ python3 -m venv venv3
$ . venv3/bin/activate
(venv3) $ pip3 install pystan
```

Run the test script:

```bash
(venv3) $ which python3
~/venv3/bin/python3
(venv3) $ python3 ~/pystan-test.py
INFO:pystan:COMPILING THE C++ CODE FOR MODEL anon_model_5944b02c79788fa0db5b3a93728ca2bf NOW.
Traceback (most recent call last):
  File "/usr/lib64/python3.6/distutils/unixccompiler.py", line 127, in _compile
    extra_postargs)
  File "/usr/lib64/python3.6/distutils/ccompiler.py", line 909, in spawn
    spawn(cmd, dry_run=self.dry_run)
  File "/usr/lib64/python3.6/distutils/spawn.py", line 36, in spawn
    _spawn_posix(cmd, search_path, dry_run=dry_run)
  File "/usr/lib64/python3.6/distutils/spawn.py", line 159, in _spawn_posix
    % (cmd, exit_status))
distutils.errors.DistutilsExecError: command 'gcc' failed with exit status 1

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/sbonds_adm/pystan-test.py", line 4, in <module>
    model = pystan.StanModel(model_code=model_code)  # this will take a minute
  File "/home/sbonds_adm/venv3/lib64/python3.6/site-packages/pystan/model.py", line 378, in __init__
    build_extension.run()
  File "/usr/lib64/python3.6/distutils/command/build_ext.py", line 339, in run
    self.build_extensions()
  File "/usr/lib64/python3.6/distutils/command/build_ext.py", line 448, in build_extensions
    self._build_extensions_serial()
  File "/usr/lib64/python3.6/distutils/command/build_ext.py", line 473, in _build_extensions_serial
    self.build_extension(ext)
  File "/usr/lib64/python3.6/distutils/command/build_ext.py", line 533, in build_extension
    depends=ext.depends)
  File "/usr/lib64/python3.6/distutils/ccompiler.py", line 574, in compile
    self._compile(obj, src, ext, cc_args, extra_postargs, pp_opts)
  File "/usr/lib64/python3.6/distutils/unixccompiler.py", line 129, in _compile
    raise CompileError(msg)
distutils.errors.CompileError: command 'gcc' failed with exit status 1
```

RHEL7 won't work (e.g. #583), but in theory the GCC included with RHEL8 should work:

```bash
(venve) $ gcc --version
gcc (GCC) 8.3.1 20190507 (Red Hat 8.3.1-4)
Copyright (C) 2018 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

What additional information would help figure out what's not working here?

**Comment by bletham** [comment]
Yeah the version of gcc seems fine. The only other thing I would make sure is in place is the python dev tools. That will be something like `yum install python3-devel.x86_64`. You could try `yum groupinstall "Development Tools"` but I feel like that might be a bit of a stretch.

**Comment by sbonds** [comment]
```
# yum install python3-devel
(1/6): python3-rpm-generators-5-4.el8.noarch.rp  88 kB/s |  24 kB     00:00
(2/6): python36-devel-3.6.8-2.module+el8.1.0+33  57 kB/s |  16 kB     00:00
(3/6): python3-rpm-macros-3-37.el8.noarch.rpm    43 kB/s |  13 kB     00:00
(4/6): python-rpm-macros-3-37.el8.noarch.rpm     64 kB/s |  14 kB     00:00
(5/6): python-srpm-macros-3-37.el8.noarch.rpm    62 kB/s |  14 kB     00:00
(6/6): platform-python-devel-3.6.8-15.1.el8.x86 825 kB/s | 245 kB     00:00
```

Back to the non-root user:

```text
$ . venv3/bin/activate
(venv3) $ python pystan-test.py
...
<tiny server melts>
```

OK, well, that's better than before. I'll work on trying that again on a system that can handle it just to confirm it's fully working but the addition of the python3-devel bundle seems to have improved things significantly.

**Comment by sbonds** [comment]
It worked nicely on a 16GB server. It probably would have worked on an 8GB server or even 4GB.

**Comment by bletham** [comment]
Great to hear!
