### ISSUE TITLE
ERROR: Failed building wheel for fbprophet

### ISSUE THREAD

**Issue by cmougan** [facebook/prophet#1453]
While install fbprophet I get the following error.
I used -vvv to have the logs.
```
Last login: Sun Apr 26 10:22:12 on ttys000
Carloss-MacBook-Pro:~ cmougan$ pip install -vvv fbprophet
Non-user install because site-packages writeable
Created temporary directory: /private/var/folders/j6/tcx3t7vj4fs8rsb97cwg06nc0000gn/T/pip-ephem-wheel-cache-6nzjb28j
Created temporary directory: /private/var/folders/j6/tcx3t7vj4fs8rsb97cwg06nc0000gn/T/pip-req-tracker-ejvks8zi
Initialized build tracking at /private/var/folders/j6/tcx3t7vj4fs8rsb97cwg06nc0000gn/T/pip-req-tracker-ejvks8zi
Created build tracker: /private/var/folders/j6/tcx3t7vj4fs8rsb97cwg06nc0000gn/T/pip-req-tracker-ejvks8zi
Entered build tracker: /private/var/folders/j6/tcx3t7vj4fs8rsb97cwg06nc0000gn/T/pip-req-tracker-ejvks8zi
Created temporary directory: /private/var/folders/j6/tcx3t7vj4fs8rsb97cwg06nc0000gn/T/pip-install-xbbf3s4r
1 location(s) to search for versions of fbprophet:
* https://pypi.org/simple/fbprophet/
Fetching project page and analyzing links: https://pypi.org/simple/fbprophet/
Getting page https://pypi.org/simple/fbprophet/
Found index url https://pypi.org/simple
Getting credentials from keyring for https://pypi.org/simple
Getting credentials from keyring for pypi.org
Looking up "https://pypi.org/simple/fbprophet/" in the cache
Request header has "max_age" as 0, cache bypassed
Starting new HTTPS connection (1): pypi.org:443
https://pypi.org:443 "GET /simple/fbprophet/ HTTP/1.1" 304 0
  Found link https://files.pythonhosted.org/packages/b1/ba/237a6875e9a61dcef997399b988afedbbdea112ae5ef7e0ad99faca1e9f4/fbprophet-0.1.post1.tar.gz#sha256=b70808a1c58ec9883e07bf92deed51b44f572064057a35ee8409bca195ed41af (from https://pypi.org/simple/fbprophet/), version: 0.1.post1
  Found link https://files.pythonhosted.org/packages/bc/fe/836b0803b4d6fd321b76573b895deb2acbcbc79b97f65778beed5ebc8a3e/fbprophet-0.1.1.tar.gz#sha256=5be931cf0f2c73eb221b269241bb15be0860497511026fd34a7e4da76395f20e (from https://pypi.org/simple/fbprophet/), version: 0.1.1
  Found link https://files.pythonhosted.org/packages/30/75/aea84d0c83a86e496cd57d3e9b08d1b3944eab0cc0dd009347a3fd1b4420/fbprophet-0.2.tar.gz#sha256=da247d103e5c5aec8ea46ee5a3a56855c9e7c87ba744511e40ec859ac914d463 (from https://pypi.org/simple/fbprophet/), version: 0.2
  Found link https://files.pythonhosted.org/packages/20/a1/b71d86cc8176892d9cc3de9aad4c118a9d61f99eeee8ab82e9d10e19a82b/fbprophet-0.2.1.tar.gz#sha256=161ee0056b7073a59a052eefe0eb986a8f5ec78090578d5ca01cb78009dcc30e (from https://pypi.org/simple/fbprophet/), version: 0.2.1
  Found link https://files.pythonhosted.org/packages/08/da/5227997488b12b041f71d602ec63f5c755ec0fddcb76678c938b1034d7c7/fbprophet-0.3.post1.tar.gz#sha256=835473d200da6409495fca090de5d12024401936747d46f45abba33c30f7beb3 (from https://pypi.org/simple/fbprophet/), version: 0.3.post1
  Found link https://files.pythonhosted.org/packages/83/a1/a39be1675a62597e4c0d4fdaeb65b14752b8aa8afc92e90edd91614353ab/fbprophet-0.3.post2.tar.gz#sha256=4f51d3a81bf86fbbb8caeb707747e9ae22c7705aff36f2556b8d03149e2b0761 (from https://pypi.org/simple/fbprophet/), version: 0.3.post2
  Found link https://files.pythonhosted.org/packages/3e/93/32b258aa95a42d601a2b4da21f78a19869d0a33f568824b27a1677b0b9ce/fbprophet-0.4.tar.gz#sha256=f8482b0ed0706913e3096c9ff07f33f9302f85373ec450608ebdbb770f8fff54 (from https://pypi.org/simple/fbprophet/), version: 0.4
  Found link https://files.pythonhosted.org/packages/f4/62/fa222feb98576ab141e18b6201d8428c7a58109b41e131c5604df755c4f1/fbprophet-0.4.post1.tar.gz#sha256=dfc1eb2836dc609dc0075822d969e8d908b0e42219b44cfe40c544de7cb0561b (from https://pypi.org/simple/fbprophet/), version: 0.4.post1
  Found link https://files.pythonhosted.org/packages/9b/a1/fef4ce00acbc28e75c0d33f60c9777527c4295656903b00ac4c9525cef7f/fbprophet-0.4.post2.tar.gz#sha256=3576e5e40e3db4e2c71fa8a1e20dd55d449012844ac6a84e939a1cb1b9668e30 (from https://pypi.org/simple/fbprophet/), version: 0.4.post2
  Found link https://files.pythonhosted.org/packages/33/fb/ad98d46773929079657706e6b2b6e366ba6c282bc2397d8f9b0ea8e5614c/fbprophet-0.5.tar.gz#sha256=c67fde2845db52dbdb4becd312b271575ce1c804be666ed1eee94339c5a35127 (from https://pypi.org/simple/fbprophet/), version: 0.5
  Found link https://files.pythonhosted.org/packages/f7/86/4509e952f9724f084625e93e0bf8d8519b25c79029a0a916b0f996644c75/fbprophet-0.6.tar.gz#sha256=de7eaa16500e4dba69a0706906775cbe96668a6fe48354ee2fff820d9e6a899b (from https://pypi.org/simple/fbprophet/), version: 0.6
Given no hashes to check 11 links for project 'fbprophet': discarding no candidates
Using version 0.6 (newest of versions: 0.1.post1, 0.1.1, 0.2, 0.2.1, 0.3.post1, 0.3.post2, 0.4, 0.4.post1, 0.4.post2, 0.5, 0.6)
Collecting fbprophet
  Created temporary directory: /private/var/folders/j6/tcx3t7vj4fs8rsb97cwg06nc0000gn/T/pip-unpack-obypnlt4
  Getting credentials from keyring for files.pythonhosted.org
  Looking up "https://files.pythonhosted.org/packages/f7/86/4509e952f9724f084625e93e0bf8d8519b25c79029a0a916b0f996644c75/fbprophet-0.6.tar.gz" in the cache
  Current age based on date: 81678
  Ignoring unknown cache-control directive: immutable
  Freshness lifetime from max-age: 365000000
  The response is "fresh", returning cached response
  365000000 > 81678
  Using cached fbprophet-0.6.tar.gz (54 kB)
  Added fbprophet from https://files.pythonhosted.org/packages/f7/86/4509e952f9724f084625e93e0bf8d8519b25c79029a0a916b0f996644c75/fbprophet-0.6.tar.gz#sha256=de7eaa16500e4dba69a0706906775cbe96668a6fe48354ee2fff820d9e6a899b to build tracker '/private/var/folders/j6/tcx3t7vj4fs8rsb97cwg06nc0000gn/T/pip-req-tracker-ejvks8zi'
    Running setup.py (path:/private/var/folders/j6/tcx3t7vj4fs8rsb97cwg06nc0000gn/T/pip-install-xbbf3s4r/fbprophet/setup.py) egg_info for package fbprophet
    Running command python setup.py egg_info
    running egg_info
    creating /private/var/folders/j6/tcx3t7vj4fs8rsb97cwg06nc0000gn/T/pip-install-xbbf3s4r/fbprophet/pip-egg-info/fbprophet.egg-info
    writing /private/var/folders/j6/tcx3t7vj4fs8rsb97cwg06nc0000gn/T/pip-install-xbbf3s4r/fbprophet/pip-egg-info/fbprophet.egg-info/PKG-INFO
    writing dependency_links to /private/var/folders/j6/tcx3t7vj4fs8rsb97cwg06nc0000gn/T/pip-install-xbbf3s4r/fbprophet/pip-egg-info/fbprophet.egg-info/dependency_links.txt
    writing requirements to /private/var/folders/j6/tcx3t7vj4fs8rsb97cwg06nc0000gn/T/pip-install-xbbf3s4r/fbprophet/pip-egg-info/fbprophet.egg-info/requires.txt
    writing top-level names to /private/var/folders/j6/tcx3t7vj4fs8rsb97cwg06nc0000gn/T/pip-install-xbbf3s4r/fbprophet/pip-egg-info/fbprophet.egg-info/top_level.txt
    writing manifest file '/private/var/folders/j6/tcx3t7vj4fs8rsb97cwg06nc0000gn/T/pip-install-xbbf3s4r/fbprophet/pip-egg-info/fbprophet.egg-info/SOURCES.txt'
    reading manifest file '/private/var/folders/j6/tcx3t7vj4fs8rsb97cwg06nc0000gn/T/pip-install-xbbf3s4r/fbprophet/pip-egg-info/fbprophet.egg-info/SOURCES.txt'
    reading manifest template 'MANIFEST.in'
    no previously-included directories found matching 'fbprophet/stan_model'
    writing manifest file '/private/var/folders/j6/tcx3t7vj4fs8rsb97cwg06nc0000gn/T/pip-install-xbbf3s4r/fbprophet/pip-egg-info/fbprophet.egg-info/SOURCES.txt'
  Source in /private/var/folders/j6/tcx3t7vj4fs8rsb97cwg06nc0000gn/T/pip-install-xbbf3s4r/fbprophet has version 0.6, which satisfies requirement fbprophet from https://files.pythonhosted.org/packages/f7/86/4509e952f9724f084625e93e0bf8d8519b25c79029a0a916b0f996644c75/fbprophet-0.6.tar.gz#sha256=de7eaa16500e4dba69a0706906775cbe96668a6fe48354ee2fff820d9e6a899b
  Removed fbprophet from https://files.pythonhosted.org/packages/f7/86/4509e952f9724f084625e93e0bf8d8519b25c79029a0a916b0f996644c75/fbprophet-0.6.tar.gz#sha256=de7eaa16500e4dba69a0706906775cbe96668a6fe48354ee2fff820d9e6a899b from build tracker '/private/var/folders/j6/tcx3t7vj4fs8rsb97cwg06nc0000gn/T/pip-req-tracker-ejvks8zi'
Requirement already satisfied: Cython>=0.22 in ./anaconda3/lib/python3.6/site-packages (from fbprophet) (0.28.2)
Requirement already satisfied: cmdstanpy==0.4 in ./anaconda3/lib/python3.6/site-packages (from fbprophet) (0.4.0)
Requirement already satisfied: pystan>=2.14 in ./anaconda3/lib/python3.6/site-packages (from fbprophet) (2.19.1.1)
Requirement already satisfied: numpy>=1.10.0 in ./anaconda3/lib/python3.6/site-packages (from fbprophet) (1.16.2)
Requirement already satisfied: pandas>=0.23.4 in ./anaconda3/lib/python3.6/site-packages (from fbprophet) (0.25.3)
Requirement already satisfied: matplotlib>=2.0.0 in ./anaconda3/lib/python3.6/site-packages (from fbprophet) (3.0.3)
Requirement already satisfied: LunarCalendar>=0.0.9 in ./anaconda3/lib/python3.6/site-packages (from fbprophet) (0.0.9)
Requirement already satisfied: convertdate>=2.1.2 in ./anaconda3/lib/python3.6/site-packages (from fbprophet) (2.2.0)
Requirement already satisfied: holidays>=0.9.5 in ./anaconda3/lib/python3.6/site-packages (from fbprophet) (0.9.11)
Requirement already satisfied: setuptools-git>=1.2 in ./anaconda3/lib/python3.6/site-packages (from fbprophet) (1.2)
Requirement already satisfied: python-dateutil>=2.8.0 in ./anaconda3/lib/python3.6/site-packages (from fbprophet) (2.8.1)
Requirement already satisfied: pytz>=2017.2 in ./anaconda3/lib/python3.6/site-packages (from pandas>=0.23.4->fbprophet) (2018.4)
Requirement already satisfied: kiwisolver>=1.0.1 in ./anaconda3/lib/python3.6/site-packages (from matplotlib>=2.0.0->fbprophet) (1.0.1)
Requirement already satisfied: cycler>=0.10 in ./anaconda3/lib/python3.6/site-packages (from matplotlib>=2.0.0->fbprophet) (0.10.0)
Requirement already satisfied: pyparsing!=2.0.4,!=2.1.2,!=2.1.6,>=2.0.1 in ./anaconda3/lib/python3.6/site-packages (from matplotlib>=2.0.0->fbprophet) (2.2.0)
Requirement already satisfied: ephem>=3.7.5.3 in ./anaconda3/lib/python3.6/site-packages (from LunarCalendar>=0.0.9->fbprophet) (3.7.7.0)
Requirement already satisfied: pymeeus<=1,>=0.3.6 in ./anaconda3/lib/python3.6/site-packages (from convertdate>=2.1.2->fbprophet) (0.3.6)
Requirement already satisfied: six in ./anaconda3/lib/python3.6/site-packages (from holidays>=0.9.5->fbprophet) (1.11.0)
Requirement already satisfied: setuptools in ./anaconda3/lib/python3.6/site-packages (from kiwisolver>=1.0.1->matplotlib>=2.0.0->fbprophet) (45.0.0)
Building wheels for collected packages: fbprophet
  Created temporary directory: /private/var/folders/j6/tcx3t7vj4fs8rsb97cwg06nc0000gn/T/pip-wheel-4mgu7dwa
  Building wheel for fbprophet (setup.py) ...   Destination directory: /private/var/folders/j6/tcx3t7vj4fs8rsb97cwg06nc0000gn/T/pip-wheel-4mgu7dwa
  Running command /Users/cmougan/anaconda3/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/j6/tcx3t7vj4fs8rsb97cwg06nc0000gn/T/pip-install-xbbf3s4r/fbprophet/setup.py'"'"'; __file__='"'"'/private/var/folders/j6/tcx3t7vj4fs8rsb97cwg06nc0000gn/T/pip-install-xbbf3s4r/fbprophet/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /private/var/folders/j6/tcx3t7vj4fs8rsb97cwg06nc0000gn/T/pip-wheel-4mgu7dwa
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib
  creating build/lib/fbprophet
  creating build/lib/fbprophet/stan_model
  Importing matplotlib failed. Plotting will not work.
  INFO:pystan:COMPILING THE C++ CODE FOR MODEL anon_model_888a84912910fa0a45b9d614b75bb8a8 NOW.
  error: command 'gcc' failed with exit status 1
error
  ERROR: Failed building wheel for fbprophet
  Running setup.py clean for fbprophet
  Running command /Users/cmougan/anaconda3/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/j6/tcx3t7vj4fs8rsb97cwg06nc0000gn/T/pip-install-xbbf3s4r/fbprophet/setup.py'"'"'; __file__='"'"'/private/var/folders/j6/tcx3t7vj4fs8rsb97cwg06nc0000gn/T/pip-install-xbbf3s4r/fbprophet/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' clean --all
  running clean
  removing 'build/lib' (and everything under it)
  'build/bdist.macosx-10.7-x86_64' does not exist -- can't clean it
  'build/scripts-3.6' does not exist -- can't clean it
  removing 'build'
Failed to build fbprophet
Installing collected packages: fbprophet
  Created temporary directory: /private/var/folders/j6/tcx3t7vj4fs8rsb97cwg06nc0000gn/T/pip-record-rl3egqgn
    Running command /Users/cmougan/anaconda3/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/j6/tcx3t7vj4fs8rsb97cwg06nc0000gn/T/pip-install-xbbf3s4r/fbprophet/setup.py'"'"'; __file__='"'"'/private/var/folders/j6/tcx3t7vj4fs8rsb97cwg06nc0000gn/T/pip-install-xbbf3s4r/fbprophet/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /private/var/folders/j6/tcx3t7vj4fs8rsb97cwg06nc0000gn/T/pip-record-rl3egqgn/install-record.txt --single-version-externally-managed --compile --install-headers /Users/cmougan/anaconda3/include/python3.6m/fbprophet
    running install
    running build
    running build_py
    creating build
    creating build/lib
    creating build/lib/fbprophet
    creating build/lib/fbprophet/stan_model
    Importing matplotlib failed. Plotting will not work.
    INFO:pystan:COMPILING THE C++ CODE FOR MODEL anon_model_888a84912910fa0a45b9d614b75bb8a8 NOW.
    error: command 'gcc' failed with exit status 1
    Running setup.py install for fbprophet ... error
Cleaning up...
  Removing source in /private/var/folders/j6/tcx3t7vj4fs8rsb97cwg06nc0000gn/T/pip-install-xbbf3s4r/fbprophet
Removed build tracker: '/private/var/folders/j6/tcx3t7vj4fs8rsb97cwg06nc0000gn/T/pip-req-tracker-ejvks8zi'
ERROR: Command errored out with exit status 1: /Users/cmougan/anaconda3/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/j6/tcx3t7vj4fs8rsb97cwg06nc0000gn/T/pip-install-xbbf3s4r/fbprophet/setup.py'"'"'; __file__='"'"'/private/var/folders/j6/tcx3t7vj4fs8rsb97cwg06nc0000gn/T/pip-install-xbbf3s4r/fbprophet/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /private/var/folders/j6/tcx3t7vj4fs8rsb97cwg06nc0000gn/T/pip-record-rl3egqgn/install-record.txt --single-version-externally-managed --compile --install-headers /Users/cmougan/anaconda3/include/python3.6m/fbprophet Check the logs for full command output.
Exception information:
Traceback (most recent call last):
  File "/Users/cmougan/anaconda3/lib/python3.6/site-packages/pip/_internal/cli/base_command.py", line 186, in _main
    status = self.run(options, args)
  File "/Users/cmougan/anaconda3/lib/python3.6/site-packages/pip/_internal/commands/install.py", line 404, in run
    use_user_site=options.use_user_site,
  File "/Users/cmougan/anaconda3/lib/python3.6/site-packages/pip/_internal/req/__init__.py", line 71, in install_given_reqs
    **kwargs
  File "/Users/cmougan/anaconda3/lib/python3.6/site-packages/pip/_internal/req/req_install.py", line 829, in install
    scheme=scheme,
  File "/Users/cmougan/anaconda3/lib/python3.6/site-packages/pip/_internal/operations/install/legacy.py", line 72, in install
    cwd=install_req.unpacked_source_directory,
  File "/Users/cmougan/anaconda3/lib/python3.6/site-packages/pip/_internal/utils/subprocess.py", line 275, in runner
    spinner=spinner,
  File "/Users/cmougan/anaconda3/lib/python3.6/site-packages/pip/_internal/utils/subprocess.py", line 242, in call_subprocess
    raise InstallationError(exc_msg)
pip._internal.exceptions.InstallationError: Command errored out with exit status 1: /Users/cmougan/anaconda3/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/j6/tcx3t7vj4fs8rsb97cwg06nc0000gn/T/pip-install-xbbf3s4r/fbprophet/setup.py'"'"'; __file__='"'"'/private/var/folders/j6/tcx3t7vj4fs8rsb97cwg06nc0000gn/T/pip-install-xbbf3s4r/fbprophet/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /private/var/folders/j6/tcx3t7vj4fs8rsb97cwg06nc0000gn/T/pip-record-rl3egqgn/install-record.txt --single-version-externally-managed --compile --install-headers /Users/cmougan/anaconda3/include/python3.6m/fbprophet Check the logs for full command output.
Carloss-MacBook-Pro:~ cmougan$ 

```

**Comment by bletham** [comment]
`error: command 'gcc' failed with exit status 1` usually means that pystan isn't working. Could you check if it is by running this code?
```
import pystan
model_code = 'parameters {real y;} model {y ~ normal(0,1);}'
model = pystan.StanModel(model_code=model_code)  # this will take a minute
y = model.sampling(n_jobs=1).extract()['y']
y.mean()  # should be close to 0
```
If not, then the C++ toolchain likely isn't configured correctly, and the best resource will be the PyStan documentation on that for OSX.

**Comment by cuifengcn** [comment]
use pystan==2.18.0.0 may work.
