### ISSUE TITLE
ValueError: Invalid format '.' for '%' style

### ISSUE THREAD

**Issue by Aragonite-arch** [facebook/prophet#1510]
[INFO] launcher: Starting sanity checks
[INFO] launcher: Checking for Python 3.5+
[INFO] launcher: Checking console encoding
[INFO] launcher: Setting console encoding to UTF-8
[INFO] launcher: Ensuring we're in the right environment
[INFO] launcher: Adding local bins/ folder to path
[INFO] launcher: Required checks passed.
[INFO] launcher: Optional checks passed.
[INFO] launcher: Moving old musicbot log
Traceback (most recent call last):
  File "run.py", line 438, in <module>
    main()
  File "run.py", line 347, in main
    finalize_logging()
  File "run.py", line 179, in finalize_logging
    dlh.setFormatter(logging.Formatter('.'))
  File "C:\Users\(     )\AppData\Local\Programs\Python\Python38-32\lib\logging\__init__.py", line 576, in __init__
    self._style.validate()
  File "C:\Users\(     )\AppData\Local\Programs\Python\Python38-32\lib\logging\__init__.py", line 429, in validate
    raise ValueError("Invalid format '%s' for '%s' style" % (self._fmt, self.default_format[0]))
ValueError: Invalid format '.' for '%' style

What's wrong with this?

**Comment by bletham** [comment]
This looks like it's not related to this package.
