### ISSUE TITLE
Throwing "ModuleNotFoundError: No module named 'numpy' " during fbprophet installation

### ISSUE THREAD

**Issue by shyam-sreenivasan** [facebook/prophet#1551]
Trying to install fbprophet 0.6 and it keeps throwing similar errors for numpy, pystan and convertdate randomly.
Looks like prophet is expecting these modules to be installed obviously but somehow the prophet install begins before numpy is installed.

```
 Running setup.py install for fbprophet ... error
    ERROR: Command errored out with exit status 1:
     command: /home/cfx/PYTHONTEST374/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-vqt2t7we/fbprophet/setup.py'"'"'; __file__='"'"'/tmp/pip-install-vqt2t7we/fbprophet/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-3eqd04na/install-record.txt --single-version-externally-managed --home /tmp/pip-target-4jtx3jpl --compile --install-headers /home/cfx/PYTHONTEST374/include/site/python3.7/fbprophet
         cwd: /tmp/pip-install-vqt2t7we/fbprophet/
    Complete output (42 lines):
    running install
    running build
    running build_py
    creating build
    creating build/lib
    creating build/lib/fbprophet
    creating build/lib/fbprophet/stan_model
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-vqt2t7we/fbprophet/setup.py", line 148, in <module>
        """
      File "/home/cfx/PYTHONTEST374/lib/python3.7/site-packages/setuptools/__init__.py", line 145, in setup
        return distutils.core.setup(**attrs)
      File "/usr/local/lib/python3.7/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/usr/local/lib/python3.7/distutils/dist.py", line 966, in run_commands
        self.run_command(cmd)
      File "/usr/local/lib/python3.7/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/home/cfx/PYTHONTEST374/lib/python3.7/site-packages/setuptools/command/install.py", line 61, in run
        return orig.install.run(self)
      File "/usr/local/lib/python3.7/distutils/command/install.py", line 545, in run
        self.run_command('build')
      File "/usr/local/lib/python3.7/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/usr/local/lib/python3.7/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/usr/local/lib/python3.7/distutils/command/build.py", line 135, in run
        self.run_command(cmd_name)
      File "/usr/local/lib/python3.7/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)

```

```
 File "/tmp/pip-install-vqt2t7we/fbprophet/setup.py", line 48, in run
        build_models(target_dir)
      File "/tmp/pip-install-vqt2t7we/fbprophet/setup.py", line 36, in build_models
        from fbprophet.models import StanBackendEnum
      File "/tmp/pip-install-vqt2t7we/fbprophet/fbprophet/__init__.py", line 8, in <module>
        from fbprophet.forecaster import Prophet
      File "/tmp/pip-install-vqt2t7we/fbprophet/fbprophet/forecaster.py", line 14, in <module>
        import numpy as np
    ModuleNotFoundError: No module named 'numpy'

```

**Comment by bletham** [comment]
Sorry for the slow reply. Yes, in order to compile the models during setup, `setup.py` imports numpy/pystan/etc.:
https://github.com/facebook/prophet/blob/0d260699e4776c449703a957f08eca8013461a47/python/setup.py#L36

So the requirements are all build requirements and should be installed before installing fbprophet. You can see how we do that in Travis here:
https://github.com/facebook/prophet/blob/0d260699e4776c449703a957f08eca8013461a47/.travis.yml#L11

Note that if you try to install with pip, it will install the dependencies as needed (discussion in #401).

**Comment by mswilson4040** [comment]
I have numpy installed and mentioned in requirements.txt When I run `pip install fbprophet` (and conversely when my docker container runs pip install), the error is still present.

Everything still seems to work. It's just a lot of scary red text in a build where you don't expect it to be.
