### ISSUE TITLE
RuntimeError: Initialization failed (invalid value encountered in divide)

### ISSUE THREAD

**Issue by pramodty** [facebook/prophet#1568]
![image](https://user-images.githubusercontent.com/28916110/87041796-60f29f80-c210-11ea-8d49-058b1c8f1e71.png)

I have data like this.While passing this data to m.fit(data) getting error like above mentioned.
How should I fix this error ?

        no_of_days = int(no_of_days)
        df['Payment Date'] = pd.to_datetime(
            df['Payment Date'], format='%d %b %y')
        df = df.rename(columns={'Payment Date': 'ds', 'Quantity': 'y'})
        grouped = df.groupby(
            ['tar', 'zen', 'Id'])
        final = pd.DataFrame()
        for g in grouped.groups: 
            group = grouped.get_group(g).sort_values(by='ds')
            m = Prophet(daily_seasonality=False)
            try:
                print (group.head())
                # m.add_regressor('Temperature')
                m.fit(group) 
                future = m.make_future_dataframe(freq='D', periods=no_of_days)
                forecast = m.predict(future)

**Comment by pramodty** [comment]
invalid value encountered in true_divide

INFO:fbprophet:Disabling yearly seasonality. Run prophet with yearly_seasonality=True to override this.
INFO:fbprophet:Disabling weekly seasonality. Run prophet with weekly_seasonality=True to override this.
INFO:fbprophet:n_changepoints greater than number of observations. Using 1.
Rejecting initial value:
  Error evaluating the log probability at the initial value.
Exception: normal_lpdf: Random variable is -nan, but must not be nan!  (in 'unknown file name' at line 109)


Initialization between (-2, 2) failed after 1 attempts.
 Try specifying initial values, reducing ranges of constrained values, or reparameterizing the model.
WARNING:fbprophet:Optimization terminated abnormally. Falling back to Newton.
Rejecting initial value:
  Error evaluating the log probability at the initial value.
Exception: normal_lpdf: Random variable is -nan, but must not be nan!  (in 'unknown file name' at line 109)


Initialization between (-2, 2) failed after 1 attempts.
 Try specifying initial values, reducing ranges of constrained values, or reparameterizing the model.
Traceback (most recent call last):
  File "/root/venv3/lib/python3.6/site-packages/fbprophet/models.py", line 242, in fit
    params = self.model.optimizing(**args)
  File "/root/venv3/lib/python3.6/site-packages/pystan/model.py", line 581, in optimizing
    ret, sample = fit._call_sampler(stan_args)
  File "stanfit4anon_model_888a84912910fa0a45b9d614b75bb8a8_2747563871698454359.pyx", line 1046, in stanfit4anon_model_888a84912910fa0a45b9d614b75bb8a8_2747563871698454359.StanFit4Model._call_sampler
  File "stanfit4anon_model_888a84912910fa0a45b9d614b75bb8a8_2747563871698454359.pyx", line 406, in stanfit4anon_model_888a84912910fa0a45b9d614b75bb8a8_2747563871698454359._call_sampler
RuntimeError: Initialization failed.

Traceback (most recent call last):
  File "forecast_script.py", line 281, in run_fbp_for_all_categories
    pdb.set_trace()
  File "/root/venv3/lib/python3.6/site-packages/fbprophet/forecaster.py", line 1141, in fit
    self.params = self.stan_backend.fit(stan_init, dat, **kwargs)
  File "/root/venv3/lib/python3.6/site-packages/fbprophet/models.py", line 249, in fit
    params = self.model.optimizing(**args)
  File "/root/venv3/lib/python3.6/site-packages/pystan/model.py", line 581, in optimizing
    ret, sample = fit._call_sampler(stan_args)
  File "stanfit4anon_model_888a84912910fa0a45b9d614b75bb8a8_2747563871698454359.pyx", line 1046, in stanfit4anon_model_888a84912910fa0a45b9d614b75bb8a8_2747563871698454359.StanFit4Model._call_sampler
  File "stanfit4anon_model_888a84912910fa0a45b9d614b75bb8a8_2747563871698454359.pyx", line 406, in stanfit4anon_model_888a84912910fa0a45b9d614b75bb8a8_2747563871698454359._call_sampler
RuntimeError: Initialization failed.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "forecast_script.py", line 337, in <module>
    TimeseriesForecasting(options)
  File "forecast_script.py", line 31, in __init__
    self.main()
  File "forecast_script.py", line 314, in main
    data, self.GRANULAR_NAME, self.TARGET_COLUMN, self.NO_OF_DAYS)
  File "forecast_script.py", line 281, in run_fbp_for_all_categories
    pdb.set_trace()
  File "/root/venv3/lib/python3.6/site-packages/pandas/core/frame.py", line 2938, in __setitem__
    self._set_item(key, value)
  File "/root/venv3/lib/python3.6/site-packages/pandas/core/frame.py", line 3000, in _set_item
    value = self._sanitize_column(key, value)
  File "/root/venv3/lib/python3.6/site-packages/pandas/core/frame.py", line 3636, in _sanitize_column
    value = sanitize_index(value, self.index, copy=False)
  File "/root/venv3/lib/python3.6/site-packages/pandas/core/internals/construction.py", line 611, in sanitize_index
    raise ValueError("Length of values does not match length of index")
ValueError: Length of values does not match length of index

**Comment by bletham** [comment]
Sorry for the slow reply. The error is ultimately coming from the model failing to fit, and the reason it's failing to fit is because this type of data is very poorly suited for Prophet. What you have here are many observations all with the same timestamp (2019-04-03). To forecast this type of data with Prophet you will want to first aggregate the y's for each date: so, there will be a single row for 2019-04-03 and its y will be the sum of all of those in your current dataframe. The model will probably be able to fit those data.
