### ISSUE TITLE
Prophet' object has no attribute 'stan_backend

### ISSUE THREAD

**Issue by VinitSawant09** [facebook/prophet#1574]
Getting this error. Any fix ?

File "C:\Users\Mypc\PycharmProjects\COVID19India\venv\lib\site-packages\fbprophet\forecaster.py", line 154, in _load_stan_backend
logger.debug("Loaded stan backend: %s", self.stan_backend.get_type())
AttributeError: 'Prophet' object has no attribute 'stan_backend'

**Comment by bletham** [comment]
I think this can happen if compiling the model failed during install. Could you run this code, which should print out why the backend failed to load?
```Py
from fbprophet import Prophet
import logging
logger = logging.getLogger('fbprophet')
logger.setLevel(logging.DEBUG)

m = Prophet()
print(m.stan_backend)
```

**Comment by jzpotato** [comment]
I run your code，results are as follows： 
C:\Users\Administrator\anaconda3\python.exe C:/Users/Administrator/PycharmProjects/threehappiness/jzpr.py
DEBUG:fbprophet:Unable to load backend CMDSTANPY (no such file C:\Users\Administrator\anaconda3\lib\site-packages\fbprophet\stan_model\prophet_model.bin), trying the next one
deleting tmpfiles dir: C:\Users\ADMINI~1\AppData\Local\Temp\tmpau9nccd4
Traceback (most recent call last):
  File "C:/Users/Administrator/PycharmProjects/threehappiness/jzpr.py", line 6, in <module>
    m = Prophet()
  File "C:\Users\Administrator\anaconda3\lib\site-packages\fbprophet\forecaster.py", line 141, in __init__
    self._load_stan_backend(stan_backend)
  File "C:\Users\Administrator\anaconda3\lib\site-packages\fbprophet\forecaster.py", line 154, in _load_stan_backend
    logger.debug("Loaded stan backend: %s", self.stan_backend.get_type())
AttributeError: 'Prophet' object has no attribute 'stan_backend'

> I think this can happen if compiling the model failed during install. Could you run this code, which should print out why the backend failed to load?
> 
> ```python
> from fbprophet import Prophet
> import logging
> logger = logging.getLogger('fbprophet')
> logger.setLevel(logging.DEBUG)
> 
> m = Prophet()
> print(m.stan_backend)
> ```

**Comment by bletham** [comment]
Was there anything else printed out? I expect to also see the message "Trying to load backend CMDSTANPY", from here:
https://github.com/facebook/prophet/blob/0d260699e4776c449703a957f08eca8013461a47/python/fbprophet/forecaster.py#L147
did you by chance paste only the end of the printout?

In any case, it is for some reason unable to load the model. This is either because the model file is not there, or because it is failing to load the file that is there. Run this to see where the model file is supposed to be:
```Python
import pkg_resources
model_file = pkg_resources.resource_filename('fbprophet', 'stan_model/prophet_model.pkl')
print(model_file)
```
Does that file exist? How large is it?

Try to load it:
```Python
import pickle
with open(model_file, 'rb') as f:
    stan_model = pickle.load(f)
```
What happens?

**Comment by jzpotato** [comment]
> Was there anything else printed out? I expect to also see the message "Trying to load backend CMDSTANPY", from here:
> https://github.com/facebook/prophet/blob/0d260699e4776c449703a957f08eca8013461a47/python/fbprophet/forecaster.py#L147
> 
> 
> did you by chance paste only the end of the printout?
> In any case, it is for some reason unable to load the model. This is either because the model file is not there, or because it is failing to load the file that is there. Run this to see where the model file is supposed to be:
> 
> ```python
> import pkg_resources
> model_file = pkg_resources.resource_filename('fbprophet', 'stan_model/prophet_model.pkl')
> print(model_file)
> ```
> 
> Does that file exist? How large is it?
> 
> Try to load it:
> 
> ```python
> import pickle
> with open(model_file, 'rb') as f:
>     stan_model = pickle.load(f)
> ```
> 
> What happens?

Thank you for your reply. The problem may be related to the version of python. I reinstall the package  with anaconda in python 3.7.6. No such problems were found. when I install it in python 3.8.2, the problem is still there.

**Comment by bletham** [comment]
How did you install it in 3.8? I'm pretty sure there isn't a conda forge package in 3.8, was it through pip? I'm wondering if maybe it's something with the C++ toolchain in system python vs. in anaconda.

**Comment by jzpotato** [comment]
> How did you install it in 3.8? I'm pretty sure there isn't a conda forge package in 3.8, was it through pip? I'm wondering if maybe it's something with the C++ toolchain in system python vs. in anaconda.

I installed fbprophet in python 3.8 through pip，but encountered a lot of errors during the installation.

**Comment by ragyibrahimRNA** [comment]
I'm not sure that's really a solution. Downgrading to python 3.7 is not really an option for a production platform with hundreds of dependencies. Is there any plan to fix this for python 3.8?

**Comment by bletham** [comment]
@ragyibrahimRNA this does work now in Python3.8 (there is a conda forge package for py38). If you're having issues feel free to re-open this or open a new issue, and if you could answer my questions in https://github.com/facebook/prophet/issues/1574#issuecomment-663286531 that'd be helpful for trying to debug.

**Comment by aliyahmisri** [comment]
i have same error with python 3.9. is it expected or not? thanks in advance.

**Comment by GlenTiki** [comment]
This error has cropped up for my team, using python 3.7.

I noticed in the below that Prophet() needed to be called twice to get the expected debug output.

```
>>> from fbprophet import Prophet
>>> import logging
>>> logger = logging.getLogger('fbprophet')
>>> logger.setLevel(logging.DEBUG)
>>> m = Prophet()
DEBUG:fbprophet:Unable to load backend CMDSTANPY (no such file /conjura/deployments/h8162h7t9/venv/lib64/python3.7/site-packages/fbprophet/stan_model/prophet_model.bin), trying the next one
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/conjura/deployments/h8162h7t9/venv/lib64/python3.7/site-packages/fbprophet/forecaster.py", line 141, in __init__
    self._load_stan_backend(stan_backend)
  File "/conjura/deployments/h8162h7t9/venv/lib64/python3.7/site-packages/fbprophet/forecaster.py", line 154, in _load_stan_backend
    logger.debug("Loaded stan backend: %s", self.stan_backend.get_type())
AttributeError: 'Prophet' object has no attribute 'stan_backend'
>>> m = Prophet()
DEBUG:fbprophet:Trying to load backend: PYSTAN
DEBUG:fbprophet:Unable to load backend PYSTAN (No module named 'pystan'), trying the next one
DEBUG:fbprophet:Trying to load backend: CMDSTANPY
DEBUG:fbprophet:Unable to load backend CMDSTANPY (no such file /conjura/deployments/h8162h7t9/venv/lib64/python3.7/site-packages/fbprophet/stan_model/prophet_model.bin), trying the next one
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/conjura/deployments/h8162h7t9/venv/lib64/python3.7/site-packages/fbprophet/forecaster.py", line 141, in __init__
    self._load_stan_backend(stan_backend)
  File "/conjura/deployments/h8162h7t9/venv/lib64/python3.7/site-packages/fbprophet/forecaster.py", line 154, in _load_stan_backend
    logger.debug("Loaded stan backend: %s", self.stan_backend.get_type())
AttributeError: 'Prophet' object has no attribute 'stan_backend'
>>> print(m.stan_backend)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'm' is not defined
>>> import pkg_resources
>>> model_file = pkg_resources.resource_filename('fbprophet', 'stan_model/prophet_model.pkl')
>>> print(model_file)
/conjura/deployments/h8162h7t9/venv/lib64/python3.7/site-packages/fbprophet/stan_model/prophet_model.pkl
>>> import pickle
>>> with open(model_file, 'rb') as f:
...     stan_model = pickle.load(f)
... 
Traceback (most recent call last):
  File "<stdin>", line 2, in <module>
ModuleNotFoundError: No module named 'pystan'```

This was previously working last week, and now it's not. The build environment was updated in an unrelated manner, then this started failing. Using fb prophet 0.6.

**Comment by bletham** [comment]
@GlenTiki the issue you're seeing (`no module named 'pystan'`) is because the latest pystan (>=3.0) made not-backwards-compatible changes, including that it now has a different import name. See #1856. You need to install pystan 2.19.1.1 for things to work, and then re-install fbprophet.
```
pip remove fbprophet
pip install pystan==2.19.1.1
pip install fbprophet
```

**Comment by GlenTiki** [comment]
@bletham perfect, that worked great for me. Thanks! 😃

**Comment by matheus695p** [comment]
Do you guys have any production solution for this problem, changing python version is not an option?

PS: if you don't have it for tomorrow Georgina will kill me because she won't have the basis curves on her dashboard.

**Comment by RunchenSong** [comment]
I solved this issue by virtual env.
1.create a new virtual env
2.use conda cmd install all requirements

**Comment by Karen2188** [comment]
It would be great to have a solution to this error, it continues appearing event in the most recent versions
