### ISSUE TITLE
Fbprophet failed to build wheels on google cloud environment

### ISSUE THREAD

**Issue by mohnish7** [facebook/prophet#1585]
I am hoping to use fbprophet in a google cloud function, but fbprophet fails to build every time I try deploying the function. This is surprising because everything works perfectly fine locally.

On cloud functions, I am using a Python 3.7 environment. Here is my requirement.txt (two versions)

Version 1:
```
`cython
pystan
numpy
pandas==1.0.3
google-cloud-storage==1.29.0
fbprophet
geopy==1.22.0
google-cloud-bigquery==1.25.0`

```
Error with this version of requirements.txt

```
`Build failed: `pip_download_wheels` had stderr output:
    ERROR: Command errored out with exit status 1:
    command: /opt/python3.7/bin/python3.7 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-wheel-srnqu7b5/fbprophet/setup.py'"'"'; __file__='"'"'/tmp/pip-wheel-srnqu7b5/fbprophet/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-3_5khs54
    cwd: /tmp/pip-wheel-srnqu7b5/fbprophet/
    Complete output (40 lines):
    running bdist_wheel
    running build
    running build_py
    creating build
    creating build/lib
    creating build/lib/fbprophet
    creating build/lib/fbprophet/stan_model
    Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/tmp/pip-wheel-srnqu7b5/fbprophet/setup.py", line 148, in <module>
    """
    File "/opt/python3.7/lib/python3.7/site-packages/setuptools/__init__.py", line 140, in setup
    return distutils.core.setup(**attrs)
    File "/opt/python3.7/lib/python3.7/distutils/core.py", line 148, in setup
    dist.run_commands()
    File "/opt/python3.7/lib/python3.7/distutils/dist.py", line 966, in run_commands
    self.run_command(cmd)
    File "/opt/python3.7/lib/python3.7/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
    File "/opt/python3.7/lib/python3.7/site-packages/wheel/bdist_wheel.py", line 202, in run
    self.run_command('build')
    File "/opt/python3.7/lib/python3.7/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
    File "/opt/python3.7/lib/python3.7/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
    File "/opt/python3.7/lib/python3.7/distutils/command/build.py", line 135, in run
    self.run_command(cmd_name)
    File "/opt/python3.7/lib/python3.7/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
    File "/opt/python3.7/lib/python3.7/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
    File "/tmp/pip-wheel-srnqu7b5/fbprophet/setup.py", line 48, in run
    build_models(target_dir)
    File "/tmp/pip-wheel-srnqu7b5/fbprophet/setup.py", line 36, in build_models
    from fbprophet.models import StanBackendEnum
    File "/tmp/pip-wheel-srnqu7b5/fbprophet/fbprophet/__init__.py", line 8, in <module>
    from fbprophet.forecaster import Prophet
    File "/tmp/pip-wheel-srnqu7b5/fbprophet/fbprophet/forecaster.py", line 14, in <module>
    import numpy as np
    ModuleNotFoundError: No module named 'numpy'
    ----------------------------------------
    ERROR: Failed building wheel for fbprophet
    ERROR: Failed to build one or more wheels
    
    error: `pip_download_wheels` returned code: 1; Error ID: 618AA8E7`

```

I am also trying another approach based on [this stackoverflow answer,](https://stackoverflow.com/questions/58233081/python-google-cloud-function-deployment-failure-madmom-pip-package) but I'm not entirely sure if this works here:

Requirements.txt
```
`git+https://github.com/facebook/prophet#egg=fbprophet
numpy==1.18.4
pandas==1.0.3
google-cloud-storage==1.29.0
geopy==1.22.0
google-cloud-bigquery==1.25.0`
```

Error:
```
`Build failed: `pip_download_wheels` had stderr output:
Running command git clone -q https://github.com/facebook/prophet /tmp/pip-wheel-ke8onr01/fbprophet
ERROR: Command errored out with exit status 1:
command: /opt/python3.7/bin/python3.7 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-wheel-ke8onr01/fbprophet/setup.py'"'"'; __file__='"'"'/tmp/pip-wheel-ke8onr01/fbprophet/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-wheel-ke8onr01/fbprophet/pip-egg-info
cwd: /tmp/pip-wheel-ke8onr01/fbprophet/
Complete output (5 lines):
Traceback (most recent call last):
File "<string>", line 1, in <module>
File "/opt/python3.7/lib/python3.7/tokenize.py", line 447, in open
buffer = _builtin_open(filename, 'rb')
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/pip-wheel-ke8onr01/fbprophet/setup.py'
----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

error: `pip_download_wheels` returned code: 1; Error ID: 56DB6494`

```

Would appreciate any help!

**Comment by bletham** [comment]
For version 1:
The issue is the `numpy`, `pystan`, etc. are all build dependencies. So you'll need to make sure they are installed before it tries to install fbprophet. It looks like it's trying to build the wheel for fbprophet before `numpy` has been installed, which won't work.

Does anything happen after that error? This error will come up during a normal `pip` install if `numpy` is not installed, but it will then automatically install `numpy` etc. and re-try installing fbprophet (see #401). I take it here it isn't re-trying and it's actually just exiting in error? In that case you'll need to make sure all the dependencies are built before it tries to build the fbprophet wheel.

For version 2:
The problem is probably that the python code in the prophet git repo is in the `python` subdirectory, so you'd need to somehow be able to tell it to install from there (which is where setup.py is) and not from the root directory, which it appears to be trying to do. But this approach will also only work if `numpy`, `pystan`, etc. have been installed before it tries to install fbprophet, same as with version 1.

This is related to #1582 which just came up.

**Comment by mohnish7** [comment]
@bletham thanks for the response. The problem is that google cloud function just lets me submit a requirements.txt file along with the function to be executed, so there's no way that I can install numpy and any other dependencies before installing fbprophet. As a workaround, I am using Cloud Run, but would love to see an update in the future that solves this issue!

**Comment by claudiusalp** [comment]
Is there any update for this problem?

**Comment by mattschofield** [comment]
You can solve this with Cloud Build, assuming you're using that. You just have to do a bit of a dance during the build steps to make it work, like this:

```yaml
steps:
- name: 'docker.io/library/python:3.7'
  entrypoint: /bin/sh
  # Uninstall Pystan, install build dependencies of Pystan, install Pystan (build dep of Prophet), install Prophet (in requirements.txt)
  args: [-c, 'python -m pip uninstall pystan; python -m pip install convertdate==2.1.2 lunarcalendar==0.0.9 holidays==0.10.3 pgen tqdm cython pandas numpy==1.21.2 setuptools; python -m pip install pystan==2.19.1.1; python -m pip install -r requirements.txt']
  timeout: 1200s
- name: 'gcr.io/cloud-builders/gcloud'
  args: [
    'functions', 
    'deploy',
    '<YOUR_FUNCTION>',
    # ...
  ]
  dir: './'
options:
  # Installing Pystan and Prophet requires 4GB memory which the default cloudbuild instance doesn't have, so we bump
  machineType: "N1_HIGHCPU_8"
```

I also wrote a bit more detail on this on SO: https://stackoverflow.com/a/69271861/2056908
