### ISSUE TITLE
fbprophet install failed

### ISSUE THREAD

**Issue by BaoshengHeTR** [facebook/prophet#1684]
Hi. I am working under AWS sagemaker Python3 kernel. When I tried to install `fbprophet`, I had such errors:

```
  Building wheel for fbprophet (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /home/ec2-user/anaconda3/envs/python3/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-mt9_nyot/fbprophet/setup.py'"'"'; __file__='"'"'/tmp/pip-install-mt9_nyot/fbprophet/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-i65e_ydl
       cwd: /tmp/pip-install-mt9_nyot/fbprophet/
  Complete output (44 lines):
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib
  creating build/lib/fbprophet
  creating build/lib/fbprophet/stan_model
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/tmp/pip-install-mt9_nyot/fbprophet/setup.py", line 149, in <module>
      long_description_content_type='text/markdown',
    File "/home/ec2-user/anaconda3/envs/python3/lib/python3.6/site-packages/setuptools/__init__.py", line 144, in setup
      return distutils.core.setup(**attrs)
    File "/home/ec2-user/anaconda3/envs/python3/lib/python3.6/distutils/core.py", line 148, in setup
      dist.run_commands()
    File "/home/ec2-user/anaconda3/envs/python3/lib/python3.6/distutils/dist.py", line 955, in run_commands
      self.run_command(cmd)
    File "/home/ec2-user/anaconda3/envs/python3/lib/python3.6/distutils/dist.py", line 974, in run_command
      cmd_obj.run()
    File "/home/ec2-user/anaconda3/envs/python3/lib/python3.6/site-packages/wheel/bdist_wheel.py", line 223, in run
      self.run_command('build')
    File "/home/ec2-user/anaconda3/envs/python3/lib/python3.6/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/home/ec2-user/anaconda3/envs/python3/lib/python3.6/distutils/dist.py", line 974, in run_command
      cmd_obj.run()
    File "/home/ec2-user/anaconda3/envs/python3/lib/python3.6/distutils/command/build.py", line 135, in run
      self.run_command(cmd_name)
    File "/home/ec2-user/anaconda3/envs/python3/lib/python3.6/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/home/ec2-user/anaconda3/envs/python3/lib/python3.6/distutils/dist.py", line 974, in run_command
      cmd_obj.run()
    File "/tmp/pip-install-mt9_nyot/fbprophet/setup.py", line 48, in run
      build_models(target_dir)
    File "/tmp/pip-install-mt9_nyot/fbprophet/setup.py", line 36, in build_models
      from fbprophet.models import StanBackendEnum
    File "/tmp/pip-install-mt9_nyot/fbprophet/fbprophet/__init__.py", line 8, in <module>
      from fbprophet.forecaster import Prophet
    File "/tmp/pip-install-mt9_nyot/fbprophet/fbprophet/forecaster.py", line 17, in <module>
      from fbprophet.make_holidays import get_holiday_names, make_holidays_df
    File "/tmp/pip-install-mt9_nyot/fbprophet/fbprophet/make_holidays.py", line 14, in <module>
      import fbprophet.hdays as hdays_part2
    File "/tmp/pip-install-mt9_nyot/fbprophet/fbprophet/hdays.py", line 17, in <module>
      from holidays import WEEKEND, HolidayBase, Turkey
  ImportError: cannot import name 'Turkey'
  ----------------------------------------
  ERROR: Failed building wheel for fbprophet
  Running setup.py clean for fbprophet
Failed to build fbprophet
Installing collected packages: cmdstanpy, holidays, fbprophet
  Attempting uninstall: cmdstanpy
    Found existing installation: cmdstanpy 0.4.0
    Uninstalling cmdstanpy-0.4.0:
      Successfully uninstalled cmdstanpy-0.4.0
  Attempting uninstall: holidays
    Found existing installation: holidays 0.9.11
    Uninstalling holidays-0.9.11:
      Successfully uninstalled holidays-0.9.11
    Running setup.py install for fbprophet ... error
    ERROR: Command errored out with exit status 1:
     command: /home/ec2-user/anaconda3/envs/python3/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-mt9_nyot/fbprophet/setup.py'"'"'; __file__='"'"'/tmp/pip-install-mt9_nyot/fbprophet/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-b2so_arv/install-record.txt --single-version-externally-managed --compile --install-headers /home/ec2-user/anaconda3/envs/python3/include/python3.6m/fbprophet
         cwd: /tmp/pip-install-mt9_nyot/fbprophet/
    Complete output (9 lines):
    running install
    running build
    running build_py
    creating build
    creating build/lib
    creating build/lib/fbprophet
    creating build/lib/fbprophet/stan_model
    INFO:pystan:COMPILING THE C++ CODE FOR MODEL anon_model_dfdaf2b8ece8a02eb11f050ec701c0ec NOW.
    error: command 'gcc' failed with exit status 1
    ----------------------------------------
ERROR: Command errored out with exit status 1: /home/ec2-user/anaconda3/envs/python3/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-mt9_nyot/fbprophet/setup.py'"'"'; __file__='"'"'/tmp/pip-install-mt9_nyot/fbprophet/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-b2so_arv/install-record.txt --single-version-externally-managed --compile --install-headers /home/ec2-user/anaconda3/envs/python3/include/python3.6m/fbprophet Check the logs for full command output.
```

Hope someone can give me some clues. Thanks.

**Comment by bletham** [comment]
It looks like you need to upgrade the version of the `holidays` package to >=0.10.2. I'm not sure why that didn't happen automatically, but if you use pip to upgrade holidays before trying to install fbprophet it should work
```
pip install --upgrade holidays pystan
pip install fbprophet
```
This is the requirement, so not sure why that didn't get picked up:
https://github.com/facebook/prophet/blob/77da5b8c06d05d478af510198c685d454342db1f/python/requirements.txt#L9

**Comment by BaoshengHeTR** [comment]
> It looks like you need to upgrade the version of the `holidays` package to >=0.10.2. I'm not sure why that didn't happen automatically, but if you use pip to upgrade holidays before trying to install fbprophet it should work
> 
> ```
> pip install --upgrade holidays pystan
> pip install fbprophet
> ```
> 
> This is the requirement, so not sure why that didn't get picked up:
> https://github.com/facebook/prophet/blob/77da5b8c06d05d478af510198c685d454342db1f/python/requirements.txt#L9

In fact, I do have the updated `holidays`. But the install of `fbprophet` still failed.

**Comment by bletham** [comment]
Oh, sorry, I saw the `ImportError: cannot import name 'Turkey'` which was coming from an old version of holidays.  But it looks like that was updated later, and then install failed while compiling the model. Usually that means pystan isn't working. Could you check:
```Python
import pystan
model_code = 'parameters {real y;} model {y ~ normal(0,1);}'
model = pystan.StanModel(model_code=model_code)  # this will take a minute
y = model.sampling(n_jobs=1).extract()['y']
y.mean()  # should be close to 0
```

If that fails, then usually in Linux the issue would be that python-dev or build tools need to be installed.

**Comment by BaoshengHeTR** [comment]
> Oh, sorry, I saw the `ImportError: cannot import name 'Turkey'` which was coming from an old version of holidays. But it looks like that was updated later, and then install failed while compiling the model. Usually that means pystan isn't working. Could you check:
> 
> ```python
> import pystan
> model_code = 'parameters {real y;} model {y ~ normal(0,1);}'
> model = pystan.StanModel(model_code=model_code)  # this will take a minute
> y = model.sampling(n_jobs=1).extract()['y']
> y.mean()  # should be close to 0
> ```
> 
> If that fails, then usually in Linux the issue would be that python-dev or build tools need to be installed.

Thanks. Would you share the list of all dev tools required? Thanks.

**Comment by bletham** [comment]
The specific set of packages depends on the distro, but see the Linux section in https://facebook.github.io/prophet/docs/installation.html#python for some ideas.

**Comment by iraseidman** [comment]
After spending hours scouring the internet for answers to this question and similar questions like "ERROR: Command errored out with exit status 1: when installing "Facebook" "prophet"" what worked for me was quite simply using a sudo pip install at the terminal prompt:

`$ sudo pip install pystan==2.19.1.1 prophet`

After install using prophet instead of fbprophet:

`from prophet import Prophet`

Credit to GitHub issue 1874 - https://github.com/facebook/prophet/issues/1874
