### ISSUE TITLE
Update pystan in requirements

### ISSUE THREAD

**Issue by ahartikainen** [facebook/prophet#1856]
Currently latest pystan is 3.0.0 which is incompatible with 2.x.

https://pypi.org/project/pystan

Following PEP 440 could be used https://www.python.org/dev/peps/pep-0440/#compatible-release

    pystan~=2.14

**Comment by bletham** [comment]
Thanks for the heads up!

**Comment by LasseRegin** [comment]
I believe the latest compatible version would be `pystan~=2.19.1.1`. 

See https://github.com/facebook/prophet/commit/82f3399409b7646c49280688f59e5a3d2c936d39#diff-b72f6e5561c432513e240838ae1eeb3f85237fa3ed5d701ad4c3be2a55c57b9d

**Comment by qingchaowang** [comment]
yes exactly. I cannot install fbprophet now. I have to install pystan==2.19.1.1 first then can install fbprophet properly.

**Comment by waqas-zia-confiz** [comment]
We have been able to install fbprophet but still getting an error while fitting. Any idea how this can be fixed?

File "/databricks/spark/python/pyspark/serializers.py", line 177, in _read_with_length
    return self.loads(obj)
  File "/databricks/spark/python/pyspark/serializers.py", line 466, in loads
    return pickle.loads(obj, encoding=encoding)
  File "/local_disk0/.ephemeral_nfs/envs/pythonEnv-7daac45e-8dc6-4074-b2c2-8f85b1174384/lib/python3.7/site-packages/fbprophet/__init__.py", line 8, in <module>
    from fbprophet.forecaster import Prophet
  File "/local_disk0/.ephemeral_nfs/envs/pythonEnv-7daac45e-8dc6-4074-b2c2-8f85b1174384/lib/python3.7/site-packages/fbprophet/forecaster.py", line 17, in <module>
    from fbprophet.make_holidays import get_holiday_names, make_holidays_df
  File "/local_disk0/.ephemeral_nfs/envs/pythonEnv-7daac45e-8dc6-4074-b2c2-8f85b1174384/lib/python3.7/site-packages/fbprophet/make_holidays.py", line 14, in <module>
    import fbprophet.hdays as hdays_part2
  File "/local_disk0/.ephemeral_nfs/envs/pythonEnv-7daac45e-8dc6-4074-b2c2-8f85b1174384/lib/python3.7/site-packages/fbprophet/hdays.py", line 14, in <module>
    from lunarcalendar import Lunar, Converter
ModuleNotFoundError: No module named 'lunarcalendar''. Full traceback below:
Traceback (most recent call last):
  File "/databricks/spark/python/pyspark/serializers.py", line 177, in _read_with_length
    return self.loads(obj)
  File "/databricks/spark/python/pyspark/serializers.py", line 466, in loads
    return pickle.loads(obj, encoding=encoding)
  File "/local_disk0/.ephemeral_nfs/envs/pythonEnv-7daac45e-8dc6-4074-b2c2-8f85b1174384/lib/python3.7/site-packages/fbprophet/__init__.py", line 8, in <module>
    from fbprophet.forecaster import Prophet
  File "/local_disk0/.ephemeral_nfs/envs/pythonEnv-7daac45e-8dc6-4074-b2c2-8f85b1174384/lib/python3.7/site-packages/fbprophet/forecaster.py", line 17, in <module>
    from fbprophet.make_holidays import get_holiday_names, make_holidays_df
  File "/local_disk0/.ephemeral_nfs/envs/pythonEnv-7daac45e-8dc6-4074-b2c2-8f85b1174384/lib/python3.7/site-packages/fbprophet/make_holidays.py", line 14, in <module>
    import fbprophet.hdays as hdays_part2
  File "/local_disk0/.ephemeral_nfs/envs/pythonEnv-7daac45e-8dc6-4074-b2c2-8f85b1174384/lib/python3.7/site-packages/fbprophet/hdays.py", line 14, in <module>
    from lunarcalendar import Lunar, Converter
ModuleNotFoundError: No module named 'lunarcalendar'

**Comment by seanjtaylor** [comment]
We're pushing a new release with the updated pinned version very soon.

**Comment by mrshu** [comment]
Is this resolved by any chance already?

**Comment by tanercam** [comment]
Hi, how can I download the right version of pystan or any other necessary library to fit a time series model by using facebookprophet. Last year there was no problem. Yesterday I tried again but it could not be possible to fit the model. I have used also pystan==2.19.1.1. 
Does anyone know a working solution?

**Comment by tanercam** [comment]
> Currently latest pystan is 3.0.0 which is incompatible with 2.x.
> 
> https://pypi.org/project/pystan
> 
> Following PEP 440 could be used https://www.python.org/dev/peps/pep-0440/#compatible-release
> 
> ```
> pystan~=2.14
> ```

Hi, how can I download the right version of pystan or any other necessary library to fit a time series model by using facebookprophet. Last year there was no problem. Yesterday I tried again but it could not be possible to fit the model. I have used also pystan==2.19.1.1.
Does anyone know a working solution?
