### ISSUE TITLE
ModuleNotFoundError: No module named 'pystan' - Fedora 33

### ISSUE THREAD

**Issue by Shadmeister** [facebook/prophet#1876]
Hi,
I have read through the multiple entries in the existing (closed) error reports, and i am obtaining the same error. I have gone through some stack exchange processes and to no avail. The error i am obtaining is as follows :

````
Building wheels for collected packages: fbprophet
  Building wheel for fbprophet (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /usr/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-7mseaum6/fbprophet_b6f9a32419834bcf82dbfef4d006348f/setup.py'"'"'; __file__='"'"'/tmp/pip-install-7mseaum6/fbprophet_b6f9a32419834bcf82dbfef4d006348f/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-czw65e8k                                                                                                               
       cwd: /tmp/pip-install-7mseaum6/fbprophet_b6f9a32419834bcf82dbfef4d006348f/                                                                
  Complete output (38 lines):                                                                                                                    
  running bdist_wheel                                                                                                                            
  running build                                                                                                                                  
  running build_py                                                                                                                               
  creating build                                                                                                                                 
  creating build/lib                                                                                                                             
  creating build/lib/fbprophet                                                                                                                   
  creating build/lib/fbprophet/stan_model                                                                                                        
  Traceback (most recent call last):                                                                                                             
    File "<string>", line 1, in <module>                                                                                                         
    File "/tmp/pip-install-7mseaum6/fbprophet_b6f9a32419834bcf82dbfef4d006348f/setup.py", line 122, in <module>                                  
      setup(                                                                                                                                     
    File "/home/richard/.local/lib/python3.9/site-packages/setuptools/__init__.py", line 153, in setup                                           
      return distutils.core.setup(**attrs)                                                                                                       
    File "/usr/lib64/python3.9/distutils/core.py", line 148, in setup                                                                            
      dist.run_commands()                                                                                                                        
    File "/usr/lib64/python3.9/distutils/dist.py", line 966, in run_commands                                                                     
      self.run_command(cmd)                                                                                                                      
    File "/usr/lib64/python3.9/distutils/dist.py", line 985, in run_command                                                                      
      cmd_obj.run()                                                                                                                              
    File "/home/richard/.local/lib/python3.9/site-packages/wheel/bdist_wheel.py", line 299, in run                                               
      self.run_command('build')                                                                                                                  
    File "/usr/lib64/python3.9/distutils/cmd.py", line 313, in run_command                                                                       
      self.distribution.run_command(command)                                                                                                     
    File "/usr/lib64/python3.9/distutils/dist.py", line 985, in run_command                                                                      
      cmd_obj.run()                                                                                                                              
    File "/usr/lib64/python3.9/distutils/command/build.py", line 135, in run                                                                     
      self.run_command(cmd_name)                                                                                                                 
    File "/usr/lib64/python3.9/distutils/cmd.py", line 313, in run_command                                                                       
      self.distribution.run_command(command)                                                                                                     
    File "/usr/lib64/python3.9/distutils/dist.py", line 985, in run_command                                                                      
      cmd_obj.run()                                                                                                                              
    File "/tmp/pip-install-7mseaum6/fbprophet_b6f9a32419834bcf82dbfef4d006348f/setup.py", line 48, in run                                        
      build_models(target_dir)                                                                                                                   
    File "/tmp/pip-install-7mseaum6/fbprophet_b6f9a32419834bcf82dbfef4d006348f/setup.py", line 38, in build_models                               
      StanBackendEnum.get_backend_class(backend).build_model(target_dir, MODEL_DIR)                                                              
    File "/tmp/pip-install-7mseaum6/fbprophet_b6f9a32419834bcf82dbfef4d006348f/fbprophet/models.py", line 209, in build_model                    
      import pystan                                                                                                                              
  ModuleNotFoundError: No module named 'pystan'                                                                                                  
                                                                                               
  ERROR: Failed building wheel for fbprophet
  Running setup.py clean for fbprophet
Failed to build fbprophet
Installing collected packages: fbprophet
    Running setup.py install for fbprophet ... error
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-7mseaum6/fbprophet_b6f9a32419834bcf82dbfef4d006348f/setup.py'"'"'; __file__='"'"'/tmp/pip-install-7mseaum6/fbprophet_b6f9a32419834bcf82dbfef4d006348f/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-5z7ic438/install-record.txt --single-version-externally-managed --user --prefix= --compile --install-headers /home/richard/.local/include/python3.9/fbprophet                                                                                                      
         cwd: /tmp/pip-install-7mseaum6/fbprophet_b6f9a32419834bcf82dbfef4d006348f/                                                              
    Complete output (40 lines):                                                                                                                  
    running install                                                                                                                              
    running build                                                                                                                                
    running build_py                                                                                                                             
    creating build                                                                                                                               
    creating build/lib                                                                                                                           
    creating build/lib/fbprophet                                                                                                                 
    creating build/lib/fbprophet/stan_model
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-7mseaum6/fbprophet_b6f9a32419834bcf82dbfef4d006348f/setup.py", line 122, in <module>
        setup(
      File "/home/richard/.local/lib/python3.9/site-packages/setuptools/__init__.py", line 153, in setup
        return distutils.core.setup(**attrs)
      File "/usr/lib64/python3.9/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/usr/lib64/python3.9/distutils/dist.py", line 966, in run_commands
        self.run_command(cmd)
      File "/usr/lib64/python3.9/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/home/richard/.local/lib/python3.9/site-packages/setuptools/command/install.py", line 61, in run
        return orig.install.run(self)
      File "/usr/lib64/python3.9/distutils/command/install.py", line 557, in run
        self.run_command('build')
      File "/usr/lib64/python3.9/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/usr/lib64/python3.9/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/usr/lib64/python3.9/distutils/command/build.py", line 135, in run
        self.run_command(cmd_name)
      File "/usr/lib64/python3.9/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/usr/lib64/python3.9/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/tmp/pip-install-7mseaum6/fbprophet_b6f9a32419834bcf82dbfef4d006348f/setup.py", line 48, in run
        build_models(target_dir)
      File "/tmp/pip-install-7mseaum6/fbprophet_b6f9a32419834bcf82dbfef4d006348f/setup.py", line 38, in build_models
        StanBackendEnum.get_backend_class(backend).build_model(target_dir, MODEL_DIR)
      File "/tmp/pip-install-7mseaum6/fbprophet_b6f9a32419834bcf82dbfef4d006348f/fbprophet/models.py", line 209, in build_model
        import pystan
    ModuleNotFoundError: No module named 'pystan'
    ----------------------------------------
ERROR: Command errored out with exit status 1: /usr/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-7mseaum6/fbprophet_b6f9a32419834bcf82dbfef4d006348f/setup.py'"'"'; __file__='"'"'/tmp/pip-install-7mseaum6/fbprophet_b6f9a32419834bcf82dbfef4d006348f/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-5z7ic438/install-record.txt --single-version-externally-managed --user --prefix= --compile --install-headers /home/richard/.local/include/python3.9/fbprophet Check the logs for full command output.
````

I have installed, updated, uninstalled and reinstalled many packages which include fbprophet, pip, pystan, wheel using pip3, and removed the fedora version of python3-wheel and attempted to install fbprophet again, and still not working. 

I have checked the directory and pystan is installed :

 /home/richard/.local/lib/python3.9/site-packages/pystan-3.0.2.dist-info
/home/richard/.local/lib/python3.9/site-packages/stan

Upon the script closing, the temporary files in /tmp are deleted. 

For "/home/richard/.local/include/python3.9/fbprophet Check the logs for full command output" the include directory does not exist. 

Any guidance gratefully received. 
Thanks and regards,
Shadmeister.

**Comment by Shadmeister** [comment]
Possibly, i have located the issue - there is the directory :

pystan-3.0.2.dist-info

But there is not directory 

pystan

As per other installed libraries. So, this seems to be an installation error for pystan. I have copied "stan" to create "pystan" and the progressed error message is :

AttributeError: module 'pystan' has no attribute 'StanModel'

As such, for my installation, does it look like the installation of of pystan creating "stan" directory is failing despite pip showing no errors ?. 

Regards,
Shadmeister.

**Comment by Shadmeister** [comment]
Hi,
I checked out the pystan module which was revised to version 3.0.2, and as per the bug i raised on their github, there is a fix. The fix is to downgrade to the latest version 2 :

`pip3 install "pystan<3"`

This then allows fbprophet to install without issue. Bug report here [278](https://github.com/stan-dev/pystan/issues/278) and here [246](https://github.com/stan-dev/pystan/issues/246). 

The webpage about upgrading pystan from 2 to 3 is here [upgrading to 3.0](https://pystan.readthedocs.io/en/latest/upgrading.html#upgrading-to-3-0)

Regards,
Shadmeister.

**Comment by Shadmeister** [comment]
Closing issue as solved.
