### ISSUE TITLE
Fitting a model with mcmc_samples causes ModuleNotFoundError error

### ISSUE THREAD

**Issue by saiwing-yeung** [facebook/prophet#1889]
Fitting the Peyton Manning model for MAP works fine, but if I request for any MCMC samples, I'd get the following error.

```
>>> m = Prophet(mcmc_samples=10)
>>> m.fit(df_peyton)
INFO:fbprophet:Disabling daily seasonality. Run prophet with daily_seasonality=True to override this.
Process SpawnPoolWorker-1:
Traceback (most recent call last):
  File "/Users/saiwingy/anaconda3/envs/test_prophet/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/saiwingy/anaconda3/envs/test_prophet/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/saiwingy/anaconda3/envs/test_prophet/lib/python3.8/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/saiwingy/anaconda3/envs/test_prophet/lib/python3.8/multiprocessing/queues.py", line 358, in get
    return _ForkingPickler.loads(res)
ModuleNotFoundError: No module named 'stanfit4anon_model_dfdaf2b8ece8a02eb11f050ec701c0ec_3689584490073882110'
Process SpawnPoolWorker-2:
Traceback (most recent call last):
  File "/Users/saiwingy/anaconda3/envs/test_prophet/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/saiwingy/anaconda3/envs/test_prophet/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/saiwingy/anaconda3/envs/test_prophet/lib/python3.8/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/saiwingy/anaconda3/envs/test_prophet/lib/python3.8/multiprocessing/queues.py", line 358, in get
    return _ForkingPickler.loads(res)
ModuleNotFoundError: No module named 'stanfit4anon_model_dfdaf2b8ece8a02eb11f050ec701c0ec_3689584490073882110'
Process SpawnPoolWorker-3:
Traceback (most recent call last):
  File "/Users/saiwingy/anaconda3/envs/test_prophet/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/saiwingy/anaconda3/envs/test_prophet/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/saiwingy/anaconda3/envs/test_prophet/lib/python3.8/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/saiwingy/anaconda3/envs/test_prophet/lib/python3.8/multiprocessing/queues.py", line 358, in get
    return _ForkingPickler.loads(res)
ModuleNotFoundError: No module named 'stanfit4anon_model_dfdaf2b8ece8a02eb11f050ec701c0ec_3689584490073882110'
Process SpawnPoolWorker-4:
Traceback (most recent call last):
  File "/Users/saiwingy/anaconda3/envs/test_prophet/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/saiwingy/anaconda3/envs/test_prophet/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/saiwingy/anaconda3/envs/test_prophet/lib/python3.8/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/saiwingy/anaconda3/envs/test_prophet/lib/python3.8/multiprocessing/queues.py", line 358, in get
    return _ForkingPickler.loads(res)
ModuleNotFoundError: No module named 'stanfit4anon_model_dfdaf2b8ece8a02eb11f050ec701c0ec_3689584490073882110'
```

Here's my environment (`conda create -n test_prophet python fbprophet`)
```
# Name                    Version                   Build  Channel
arviz                     0.11.2             pyhd8ed1ab_1    conda-forge
blas                      1.0                         mkl
c-ares                    1.17.1               h0d85af4_1    conda-forge
ca-certificates           2020.12.5            h033912b_0    conda-forge
cctools                   949.0.1              h22b1bf0_1    conda-forge
cctools_osx-64            949.0.1              h5ba7a2e_1    conda-forge
certifi                   2020.12.5        py38h50d1736_1    conda-forge
cftime                    1.4.1            py38ha1b04c9_0    conda-forge
clang                     10.0.0          default_hf57f61e_0
clang_osx-64              10.0.0               h05bbb7f_0
clangxx                   10.0.0          default_hf57f61e_0
clangxx_osx-64            10.0.0               h05bbb7f_1
compiler-rt               10.0.0               h47ead80_0
compiler-rt_osx-64        10.0.0               hbcc88fd_0
convertdate               2.3.2              pyhd8ed1ab_0    conda-forge
curl                      7.76.1               h06286d4_1    conda-forge
cycler                    0.10.0                     py_2    conda-forge
cython                    0.29.23          py38ha048514_0    conda-forge
ephem                     3.7.7.1          py38h4d0b108_1    conda-forge
fbprophet                 0.7.1            py38h11c0d25_0    conda-forge
freetype                  2.10.4               h4cff582_1    conda-forge
hdf4                      4.2.13            hefd3b78_1005    conda-forge
hdf5                      1.10.6               hdbbcd12_0
hijri-converter           2.1.1              pyhd8ed1ab_0    conda-forge
holidays                  0.11.1             pyhd8ed1ab_0    conda-forge
jpeg                      9d                   hbcb3906_0    conda-forge
kiwisolver                1.3.1            py38hd9c93a9_1    conda-forge
korean_lunar_calendar     0.2.1              pyh9f0ad1d_0    conda-forge
krb5                      1.17.2               h60d9502_0    conda-forge
lcms2                     2.12                 h577c468_0    conda-forge
ld64                      530                           1    conda-forge
ld64_osx-64               530                  h3c32e8a_1    conda-forge
libcurl                   7.76.1               h8ef9fac_1    conda-forge
libcxx                    11.1.0               habf9029_0    conda-forge
libedit                   3.1.20191231         h0678c8f_2    conda-forge
libev                     4.33                 haf1e3a3_1    conda-forge
libffi                    3.3                  h046ec9c_2    conda-forge
libgfortran               3.0.1                         0    conda-forge
libllvm10                 10.0.1               h009f743_3    conda-forge
libnetcdf                 4.6.1                hfd9a460_3
libnghttp2                1.43.0               h07e645a_0    conda-forge
libpng                    1.6.37               h7cec526_2    conda-forge
libssh2                   1.9.0                h52ee1ee_6    conda-forge
libtiff                   4.2.0                h7c11950_1    conda-forge
libwebp-base              1.2.0                h0d85af4_2    conda-forge
llvm-openmp               10.0.0               h28b9765_0
lunarcalendar             0.0.9                      py_0    conda-forge
lz4-c                     1.9.3                h046ec9c_0    conda-forge
matplotlib-base           3.4.1            py38h6152e83_0    conda-forge
mkl                       2019.5                      281    conda-forge
mkl-service               2.3.0            py38h0b31af3_0    conda-forge
mkl_fft                   1.3.0            py38ha059aab_0
mkl_random                1.1.1            py38h959d312_0
ncurses                   6.2                  h2e338ed_4    conda-forge
netcdf4                   1.5.6            py38h1695cb1_0
numpy                     1.19.2           py38h456fd55_0
numpy-base                1.19.2           py38hcfb5961_0
olefile                   0.46               pyh9f0ad1d_1    conda-forge
openjpeg                  2.4.0                h6cbf5cd_0    conda-forge
openssl                   1.1.1k               h0d85af4_0    conda-forge
packaging                 20.9               pyh44b312d_0    conda-forge
pandas                    1.2.4            py38h1f261ad_0    conda-forge
pillow                    8.1.2            py38h83525de_1    conda-forge
pip                       21.1               pyhd8ed1ab_0    conda-forge
pymeeus                   0.5.10             pyhd8ed1ab_0    conda-forge
pyparsing                 2.4.7              pyh9f0ad1d_0    conda-forge
pystan                    2.19.1.1         py38h6be0db6_2    conda-forge
python                    3.8.8           h4e93d89_0_cpython    conda-forge
python-dateutil           2.8.1                      py_0    conda-forge
python_abi                3.8                      1_cp38    conda-forge
pytz                      2021.1             pyhd8ed1ab_0    conda-forge
readline                  8.1                  h05e3726_0    conda-forge
scipy                     1.6.2            py38h2515648_0
setuptools                49.6.0           py38h50d1736_3    conda-forge
six                       1.15.0             pyh9f0ad1d_0    conda-forge
sqlite                    3.35.5               h44b9ce1_0    conda-forge
tapi                      1000.10.8            h879752b_4    conda-forge
tk                        8.6.10               h0419947_1    conda-forge
tornado                   6.1              py38h5406a74_1    conda-forge
tqdm                      4.60.0             pyhd8ed1ab_0    conda-forge
typing_extensions         3.7.4.3                    py_0    conda-forge
wheel                     0.36.2             pyhd3deb0d_0    conda-forge
xarray                    0.17.0             pyhd8ed1ab_0    conda-forge
xz                        5.2.5                haf1e3a3_1    conda-forge
zlib                      1.2.11            h7795811_1010    conda-forge
zstd                      1.4.9                h582d3a0_0    conda-forge
```

Since I have pystan 2.x this might be a different issue than other similar ones.

**Comment by bletham** [comment]
I wonder if #1884 might be related to this too. Hopefully @tcuongd's suggestion works, but as a workaround, you could also do `m = Prophet(mcmc_samples=10, n_jobs=1)` to have it not use multiprocessing (likely at a cost of 4x the wall time).

**Comment by saiwing-yeung** [comment]
Thanks @tcuongd. Setting `multiprocessing.set_start_method("fork")` fixed it for me.
