### ISSUE TITLE
Installation error in Redhat8 - ImportError: /tmp/tmphwntgosg/stanfit4anon_model_dfdaf2b8ece8a02eb11f050ec701c0ec_5470104797752185321.cpython-36m-x86_64-linux-gnu.so: failed to map segment from shared object

### ISSUE THREAD

**Issue by SandeepaDevin** [facebook/prophet#2058]
gcc (GCC) 8.4.1 20200928 (Red Hat 8.4.1-1)
Copyright (C) 2018 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

I tried to install prophet=1.0.0 with pystan 2.18.0.0 and this error comes up.

    Running setup.py install for prophet ... error
    ERROR: Command errored out with exit status 1:
     command: /####/####/application/bin/python3 -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-0un6eglq/prophet_23d2b71fe24f40afbd3fa6258703e52c/setup.py'"'"'; __file__='"'"'/tmp/pip-install-0un6eglq/prophet_23d2b71fe24f40afbd3fa6258703e52c/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-r321pqxh/install-record.txt --single-version-externally-managed --compile --install-headers /###/####/application/include/site/python3.6/prophet
         cwd: /tmp/pip-install-0un6eglq/prophet_23d2b71fe24f40afbd3fa6258703e52c/
    Complete output (48 lines):
    running install
    running build
    running build_py
    creating build
    creating build/lib
    creating build/lib/prophet
    creating build/lib/prophet/stan_model
    Importing plotly failed. Interactive plots will not work.
    INFO:pystan:COMPILING THE C++ CODE FOR MODEL anon_model_dfdaf2b8ece8a02eb11f050ec701c0ec NOW.
    /###/####/application/lib64/python3.6/site-packages/Cython/Compiler/Main.py:369: FutureWarning: Cython directive 'language_level' not set, using 2 for now (Py2). This will change in a later release! File: /tmp/tmphwntgosg/stanfit4anon_model_dfdaf2b8ece8a02eb11f050ec701c0ec_5470104797752185321.pyx
      tree = Parsing.p_module(s, pxd, full_module_name)
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-0un6eglq/prophet_23d2b71fe24f40afbd3fa6258703e52c/setup.py", line 150, in <module>
        long_description_content_type='text/markdown',
      File "/####/####/application/lib64/python3.6/site-packages/setuptools/__init__.py", line 129, in setup
        return distutils.core.setup(**attrs)
      File "/usr/lib64/python3.6/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/usr/lib64/python3.6/distutils/dist.py", line 955, in run_commands
        self.run_command(cmd)
      File "/usr/lib64/python3.6/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/###/####/application/lib64/python3.6/site-packages/setuptools/command/install.py", line 61, in run
        return orig.install.run(self)
      File "/usr/lib64/python3.6/distutils/command/install.py", line 556, in run
        self.run_command('build')
      File "/usr/lib64/python3.6/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/usr/lib64/python3.6/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/usr/lib64/python3.6/distutils/command/build.py", line 135, in run
        self.run_command(cmd_name)
      File "/usr/lib64/python3.6/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/usr/lib64/python3.6/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/tmp/pip-install-0un6eglq/prophet_23d2b71fe24f40afbd3fa6258703e52c/setup.py", line 48, in run
        build_models(target_dir)
      File "/tmp/pip-install-0un6eglq/prophet_23d2b71fe24f40afbd3fa6258703e52c/setup.py", line 38, in build_models
        StanBackendEnum.get_backend_class(backend).build_model(target_dir, MODEL_DIR)
      File "/tmp/pip-install-0un6eglq/prophet_23d2b71fe24f40afbd3fa6258703e52c/prophet/models.py", line 233, in build_model
        sm = pystan.StanModel(model_code=model_code)
      File "/####/####/application/lib64/python3.6/site-packages/pystan/model.py", line 319, in __init__
        self.module = load_module(self.module_name, lib_dir)
      File "/####/####/application/lib64/python3.6/site-packages/pystan/model.py", line 50, in load_module
        return __import__(module_name)
    ImportError: /tmp/tmphwntgosg/stanfit4anon_model_dfdaf2b8ece8a02eb11f050ec701c0ec_5470104797752185321.cpython-36m-x86_64-linux-gnu.so: failed to map segment from shared object
    ----------------------------------------
```
ERROR: Command errored out with exit status 1: /####/####/application/bin/python3 -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-0un6eglq/prophet_23d2b71fe24f40afbd3fa6258703e52c/setup.py'"'"'; __file__='"'"'/tmp/pip-install-0un6eglq/prophet_23d2b71fe24f40afbd3fa6258703e52c/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-r321pqxh/install-record.txt --single-version-externally-managed --compile --install-headers /####/####/application/include/site/python3.6/prophet Check the logs for full command output.
```

**Comment by SandeepaDevin** [comment]
ImportError: /tmp/tmpmks2fenl/stanfit4anon_model_dfdaf2b8ece8a02eb11f050ec701c0ec_1521358898264254818.cpython-36m-x86_64-linux-gnu.so: failed to map segment from shared object

**Comment by SandeepaDevin** [comment]
Cleaned the /tmp directory
Then ran sudo mount -o remount,exec /tmp
Now prophet installed

**Comment by SandeepaDevin** [comment]
Cleaned the /tmp
Then ran sudo mount -o remount,exec /tmp
Now prophet installed
