### ISSUE TITLE
holidays version 0.14 breaks pip install

### ISSUE THREAD

**Issue by sonichi** [facebook/prophet#2193]
* python 3.8.13
* pip==22.1.2
* pystan==2.19.1.1

`pip install prophet`:

Building wheels for collected packages: prophet
  Building wheel for prophet (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [45 lines of output]
      running bdist_wheel
      running build
      running build_py
      creating build
      creating build/lib
      creating build/lib/prophet
      creating build/lib/prophet/stan_model
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-km1azrwp/prophet_b0bbdede9cd24e468860d990d27bd0d9/setup.py", line 123, in <module>
          setup(
        File "/usr/local/lib/python3.8/site-packages/setuptools/__init__.py", line 153, in setup
          return distutils.core.setup(**attrs)
        File "/usr/local/lib/python3.8/distutils/core.py", line 148, in setup
          dist.run_commands()
        File "/usr/local/lib/python3.8/distutils/dist.py", line 966, in run_commands
          self.run_command(cmd)
        File "/usr/local/lib/python3.8/distutils/dist.py", line 985, in run_command
          cmd_obj.run()
        File "/usr/local/lib/python3.8/site-packages/wheel/bdist_wheel.py", line 299, in run
          self.run_command('build')
        File "/usr/local/lib/python3.8/distutils/cmd.py", line 313, in run_command
          self.distribution.run_command(command)
        File "/usr/local/lib/python3.8/distutils/dist.py", line 985, in run_command
          cmd_obj.run()
        File "/usr/local/lib/python3.8/distutils/command/build.py", line 135, in run
          self.run_command(cmd_name)
        File "/usr/local/lib/python3.8/distutils/cmd.py", line 313, in run_command
          self.distribution.run_command(command)
        File "/usr/local/lib/python3.8/distutils/dist.py", line 985, in run_command
          cmd_obj.run()
        File "/tmp/pip-install-km1azrwp/prophet_b0bbdede9cd24e468860d990d27bd0d9/setup.py", line 48, in run
          build_models(target_dir)
        File "/tmp/pip-install-km1azrwp/prophet_b0bbdede9cd24e468860d990d27bd0d9/setup.py", line 36, in build_models
          from prophet.models import StanBackendEnum
        File "/tmp/pip-install-km1azrwp/prophet_b0bbdede9cd24e468860d990d27bd0d9/prophet/__init__.py", line 8, in <module>
          from prophet.forecaster import Prophet
        File "/tmp/pip-install-km1azrwp/prophet_b0bbdede9cd24e468860d990d27bd0d9/prophet/forecaster.py", line 17, in <module>
          from prophet.make_holidays import get_holiday_names, make_holidays_df
        File "/tmp/pip-install-km1azrwp/prophet_b0bbdede9cd24e468860d990d27bd0d9/prophet/make_holidays.py", line 14, in <module>
          import prophet.hdays as hdays_part2
        File "/tmp/pip-install-km1azrwp/prophet_b0bbdede9cd24e468860d990d27bd0d9/prophet/hdays.py", line 14, in <module>
          from lunarcalendar import Lunar, Converter
      ModuleNotFoundError: No module named 'lunarcalendar'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for prophet
  Running setup.py clean for prophet
Failed to build prophet
Installing collected packages: setuptools-git, korean-lunar-calendar, ephem, ujson, hijri-converter, Cython, pystan, LunarCalendar, holidays, cmdstanpy, prophet
  Running setup.py install for prophet ... error
  error: subprocess-exited-with-error
  
  × Running setup.py install for prophet did not run successfully.
  │ exit code: 1
  ╰─> [55 lines of output]
      running install
      running build
      running build_py
      creating build
      creating build/lib
      creating build/lib/prophet
      creating build/lib/prophet/stan_model
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-km1azrwp/prophet_b0bbdede9cd24e468860d990d27bd0d9/setup.py", line 123, in <module>
          setup(
        File "/usr/local/lib/python3.8/site-packages/setuptools/__init__.py", line 153, in setup
          return distutils.core.setup(**attrs)
        File "/usr/local/lib/python3.8/distutils/core.py", line 148, in setup
          dist.run_commands()
        File "/usr/local/lib/python3.8/distutils/dist.py", line 966, in run_commands
          self.run_command(cmd)
        File "/usr/local/lib/python3.8/distutils/dist.py", line 985, in run_command
          cmd_obj.run()
        File "/usr/local/lib/python3.8/site-packages/setuptools/command/install.py", line 61, in run
          return orig.install.run(self)
        File "/usr/local/lib/python3.8/distutils/command/install.py", line 545, in run
          self.run_command('build')
        File "/usr/local/lib/python3.8/distutils/cmd.py", line 313, in run_command
          self.distribution.run_command(command)
        File "/usr/local/lib/python3.8/distutils/dist.py", line 985, in run_command
          cmd_obj.run()
        File "/usr/local/lib/python3.8/distutils/command/build.py", line 135, in run
          self.run_command(cmd_name)
        File "/usr/local/lib/python3.8/distutils/cmd.py", line 313, in run_command
          self.distribution.run_command(command)
        File "/usr/local/lib/python3.8/distutils/dist.py", line 985, in run_command
          cmd_obj.run()
        File "/tmp/pip-install-km1azrwp/prophet_b0bbdede9cd24e468860d990d27bd0d9/setup.py", line 48, in run
          build_models(target_dir)
        File "/tmp/pip-install-km1azrwp/prophet_b0bbdede9cd24e468860d990d27bd0d9/setup.py", line 36, in build_models
          from prophet.models import StanBackendEnum
        File "/tmp/pip-install-km1azrwp/prophet_b0bbdede9cd24e468860d990d27bd0d9/prophet/__init__.py", line 8, in <module>
          from prophet.forecaster import Prophet
        File "/tmp/pip-install-km1azrwp/prophet_b0bbdede9cd24e468860d990d27bd0d9/prophet/forecaster.py", line 17, in <module>
          from prophet.make_holidays import get_holiday_names, make_holidays_df
        File "/tmp/pip-install-km1azrwp/prophet_b0bbdede9cd24e468860d990d27bd0d9/prophet/make_holidays.py", line 14, in <module>
          import prophet.hdays as hdays_part2
        File "/tmp/pip-install-km1azrwp/prophet_b0bbdede9cd24e468860d990d27bd0d9/prophet/hdays.py", line 17, in <module>
          from holidays import WEEKEND, HolidayBase, Turkey
        File "/usr/local/lib/python3.8/site-packages/holidays/__init__.py", line 11, in <module>
          from holidays.countries import *
        File "/usr/local/lib/python3.8/site-packages/holidays/countries/__init__.py", line 17, in <module>
          from .azerbaijan import Azerbaijan, AZ, AZE
        File "/usr/local/lib/python3.8/site-packages/holidays/countries/azerbaijan.py", line 16, in <module>
          from holidays.utils import _islamic_to_gre
        File "/usr/local/lib/python3.8/site-packages/holidays/utils.py", line 24, in <module>
          import holidays.financial
      ModuleNotFoundError: No module named 'holidays.financial'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: legacy-install-failure

× Encountered error while trying to install package.
╰─> prophet

The error is gone after forcing "holidays<0.14".

**Comment by dhuang** [comment]
+1 seeing this as well.

**Comment by tcuongd** [comment]
holidays>=0.14.2 should have fixed this issue.
