### ISSUE TITLE
access denied  to prophet/stan_model/prophet_model.bin

### ISSUE THREAD

**Issue by iamadouhassane** [facebook/prophet#2243]
Hello everyone,
 
Need your helps to resolve an issue when installing and  packaging prophet library to use it for aws lambda layer. 
I already do this work  twice with python3.5 and python3.6. But for now in python 3.9 ,
I have the problem **to access to prophet/stan_model/prophet_model.bin**  when calling prophet library in my aws lambda.
I try installation with pip3.9 and sudo pip3.9 but I have the same issue. But , i have good import because when i do

import prophet
print(dir(prophet))

**I have :**
(['Prophet', '__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', '__package__', '__path__', '__spec__', '__version__', 'diagnostics', 'forecaster', 'hdays', 'make_holidays', 'models', 'plot']

[ERROR] RuntimeError: Failed with error [Errno 13] Permission denied: '/tmp/prophet/prophet/stan_model/prophet_model.bin'

Traceback (most recent call last):
  File "/var/task/lambda_function.py", line 51, in lambda_handler
    import test_fb
  File "/var/task/test_fb.py", line 12, in <module>
    m.fit(df)
  File "/tmp/prophet/prophet/forecaster.py", line 1171, in fit
    self.params = self.stan_backend.fit(stan_init, dat, **kwargs)
  File "/tmp/prophet/prophet/models.py", line 110, in fit
    self.stan_fit = self.model.optimize(**args)
  File "/tmp/prophet/cmdstanpy/model.py", line 724, in optimize
    self._run_cmdstan(runset, dummy_chain_id, show_console=show_console)
  File "/tmp/prophet/cmdstanpy/model.py", line 1603, in _run_cmdstan
    raise RuntimeError(msg) from e

**Comment by ankup007** [comment]
hi @iamadouhassane were you able to solve this issue? I am facing the same issue.

**Comment by lisong891** [comment]
你好@iamadouhassane @ankup007 你能解决这个问题吗？我面临着同样的问题。

**Comment by iamadouhassane** [comment]
Sorry @ankup007  for my late i don't see your message
@lisong891 @ankup007  i resolve this problem by installing directly fbprophet in my lambda function. It is not the best way but the fact to use layer create a lot of issue

**Comment by iamadouhassane** [comment]
`
import sys, os, boto3, shutil
from subprocess import run, PIPE, STDOUT, check_output



def updated_and_install_libraries(instruction):
    if float(sys.executable.split("/")[-1].split('python')[-1:][0])>=3.8:
        result = run(instruction, stdout=PIPE, stderr=STDOUT, shell=True,text=True)
    else:
        result = run(instruction, stdout=PIPE, stderr=STDOUT, shell=True)
    print(result.stdout)


all_packages = {"prophet":"prophet"}
python_version = sys.executable.split("/")[-1]


for package_name in all_packages:
    updated_and_install_libraries(python_version + ' -m pip install ' + all_packages[package_name] + ' --upgrade -t ' + "/tmp/" + package_name+"/")


`

**Comment by lisong891** [comment]
Thank you for your help. I copied the prophet&nbsp; files from site packages under local Linux to the cloud server and encountered the same problem. I will try again using your method.


1021372616
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "facebook/prophet"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年11月7日(星期二) 晚上10:42
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [facebook/prophet] access denied  to prophet/stan_model/prophet_model.bin (Issue #2243)





 
Sorry @ankup007  for my late i don't see your message
 @lisong891 @ankup007  i resolve this problem by installing directly fbprophet in my lambda function. It is not the best way but the fact to use layer create a lot of issue
