### ISSUE TITLE
[Python] Error when running fit(): Library not loaded: '@rpath/libtbb.dylib'

### ISSUE THREAD

**Issue by e-gons** [facebook/prophet#2250]
When running `Prophet().fit()` on a Mac (Monterey `12.5.1`, Apple M1 Max Chip), I get the following error message:

```
cmdstanpy - ERROR - Chain [1] error: terminated by signal 6 Unknown error: -6
Traceback (most recent call last):
  File "/Users/xxx/xxx/xxx/xxx/xxx/xxx/tests/test_prophet.py", line 67, in <module>
    test_prophet()
  File "/Users/xxx/xxx/xxx/xxx/xxx/xxx/tests/test_prophet.py", line 29, in test_prophet
    model.fit(df)
  File "/Users/xxx/xxx/xxx/xxx/xxx/xxx/.venv/lib/python3.8/site-packages/prophet/forecaster.py", line 1171, in fit
    self.params = self.stan_backend.fit(stan_init, dat, **kwargs)
  File "/Users/xxx/xxx/xxx/xxx/xxx/xxx/.venv/lib/python3.8/site-packages/prophet/models.py", line 112, in fit
    raise e
  File "/Users/xxx/xxx/xxx/xxx/xxx/xxx/.venv/lib/python3.8/site-packages/prophet/models.py", line 102, in fit
    self.stan_fit = self.model.optimize(**args)
  File "/Users/xxx/xxx/xxx/xxx/xxx/xxx/.venv/lib/python3.8/site-packages/cmdstanpy/model.py", line 731, in optimize
    raise RuntimeError(msg)
RuntimeError: Error during optimization: console log output:

dyld[29330]: Library not loaded: '@rpath/libtbb.dylib'
  Referenced from: '/Users/xxx/xxx/xxx/xxx/xxx/xxx/.venv/lib/python3.8/site-packages/prophet/stan_model/prophet_model.bin'
  Reason: tried: '/private/var/folders/h2/rc68jj_17r1dp8c05qbhlr500000gn/T/pip-req-build-lk5m800e/build/lib.macosx-10.14-arm64-cpython-38/prophet/stan_model/cmdstan-2.26.1/stan/lib/stan_math/lib/tbb/libtbb.dylib' (no such file), '/private/var/folders/h2/rc68jj_17r1dp8c05qbhlr500000gn/T/pip-req-build-lk5m800e/build/lib.macosx-10.14-arm64-cpython-38/prophet/stan_model/cmdstan-2.26.1/stan/lib/stan_math/lib/tbb/libtbb.dylib' (no such file), '/usr/local/lib/libtbb.dylib' (no such file), '/usr/lib/libtbb.dylib' (no such file)
```

I ran my code in VSCode and used `poetry add prophet` to install prophet in my project's env. Any ideas or help are welcome.

**Comment by rjafarau** [comment]
The same issue on M1

**Comment by shawncao** [comment]
hit the same issue on my M1 laptop, however, 1.0 works for me, does 1.1 have a big advantage in perf compared to 1.0?

**Comment by simonhuwiler** [comment]
Same problem here. prophet `1.1` does not run on Mac M1, even on Python `3.8`. Is there a fix in planning?

But the configuration above 👆 with prophet `1.0` and Python `3.8` works.

**Comment by thewisenerd** [comment]
here's how I got this working with homebrew python@3.11, might be similar for venv and other homebrew versions

```
cd /opt/homebrew/lib/python3.11/site-packages/prophet/stan_model
install_name_tool -add_rpath @executable_path/cmdstan-2.26.1/stan/lib/stan_math/lib/tbb prophet_model.bin
```

https://gist.github.com/thewisenerd/52f937d01b06287ccf21a05a118e74ad

**Comment by bfung** [comment]
> here's how I got this working with homebrew python@3.11, might be similar for venv and other homebrew versions
> 
> ```
> cd /opt/homebrew/lib/python3.11/site-packages/prophet/stan_model
> install_name_tool -add_rpath @executable_path/cmdstan-2.26.1/stan/lib/stan_math/lib/tbb prophet_model.bin
> ```
> 
> https://gist.github.com/thewisenerd/52f937d01b06287ccf21a05a118e74ad

The above worked for me using `python 3.11.0 (installed using pyenv)`, `poetry==1.2.2`, `cmdstanpy==1.0.8`, `prophet==1.1.1`.  Instead of looking in the `homebrew` directory for `stan_model`, look at the virtualenv of where prophet was installed:

```
cd $(poetry env info --path)/lib/python3.11/site-packages/prophet/stan_model
install_name_tool -add_rpath @executable_path/cmdstan-2.26.1/stan/lib/stan_math/lib/tbb prophet_model.bin
```

**Comment by nabito** [comment]
Got it to work with conda env python 3.10, prophet 1.1.1 with the solution suggested by @thewisenerd Thx!

**Comment by AlFontal** [comment]
Got this working on `python 3.10`, and `prophet==1.1.2` on my M1 Pro Macbook using the last line of @thewisenerd's solution:

```bash
install_name_tool -add_rpath @executable_path/cmdstan-2.26.1/stan/lib/stan_math/lib/tbb prophet_model.bin
```

In my case I was using a `poetry` environment so I just had to go to my virtualenv's `prophet` installation folder.

**Comment by Lion-tang** [comment]
thx! @thewisenerd , it works for me on Mac M1 Monterey, python 3.9, prophet 1.1.1

**Comment by dadwin** [comment]
Having `python 3.9.16` and `prophet==1.1`, this solved the issue on M1: 

```
install_name_tool -add_rpath @executable_path/cmdstan-2.26.1/stan/lib/stan_math/lib/tbb   .venv/lib/python3.9/site-packages/prophet/stan_model/prophet_model.bin
```

and my tests passed successfully as on linux.
so it's broken on M1 but fixable, no need to downgrade `prophet`😎

**Comment by MBristle** [comment]
thx for the suggestions! The fix of @ [thewisenerd](https://github.com/thewisenerd) worked as suggested.

```
install_name_tool -add_rpath @executable_path/cmdstan-2.26.1/stan/lib/stan_math/lib/tbb ./venv/lib/python3.10/site-packages/prophet/stan_model/prophet_model.bin
```

fixed the issue with `python 3.10.8` and `prophet==1.1.2`

**Comment by kevin7lou** [comment]
thx for the suggestions! it works for me! 

> thx for the suggestions! The fix of [thewisenerd](https://github.com/thewisenerd) worked as suggested:
> 
> ```
> install_name_tool -add_rpath @executable_path/cmdstan-2.26.1/stan/lib/stan_math/lib/tbb ./venv/lib/python3.10/site-packages/prophet/stan_model/prophet_model.bin
> ```
> 
> Having `python 3.10.8` and `prophet==1.1.2` on a M1.

**Comment by kadirmalak** [comment]
I got it working on my Apple M2 Pro machine!

I had to fix 1 line after install and make 3 symlinks for not loaded libraries.

See the post:

https://stackoverflow.com/a/76264243/1396899

**Comment by fedebindi** [comment]
@abhishek-j16's solution worked for me as well (Apple M2, Python 3.10, Prophet 1.1.3)

**Comment by hunkargenc** [comment]
I'm having trouble working on Prophet because of this problem. Could you share the working library versions for M1 Ventura 13.5.1 and Python 11 version?

**Comment by patelnets** [comment]
I'm still having trouble
