### ISSUE TITLE
Propet CMDStanpy error - Procedure Entry Point Not Located

### ISSUE THREAD

**Issue by Haridut** [facebook/prophet#2255]
Platform : Windows 10
Python version : 3.8.8
Prophet : 1.1 (not fbprophet)

The 'cmdstanpy' and 'prophet' packages are successfully installed. But I am getting this error while running my model - "The procedure entry point _ZNt3bb19task_scheduler_init10initilaizeEiy could not be located in the dynamic link library D:/ProgramData/ Anaconda3/Lib/site-packages/prophet/stan_model/prophet_model.bin" 

Any suggestions? 
![image (2)](https://user-images.githubusercontent.com/20578797/187308498-6097b728-a23b-43ba-b92a-1e7ea3bf5562.png)

**Comment by Akash-Jariwala** [comment]
Hey @Haridut,
In order to solve this problem, you will have to keep 2 points under consideration.

1. This package will not work under **"$ Base"** environment. So first, you will have to create separate environment, and install prophet in newly created environment.
2. Then change your kernel from base to newly created environment's kernel.

### **CONCLUSION:** To use "prophet", you will have to change your environment from Base to any other environment. An perform your entire "prophet" related task in that particular environment.

**Comment by Zirraf** [comment]
I have the same problem.
I created an exe file using the pyinstaller with prophet, which works well on the main computer, but not on the subcomputer.

**Comment by Zirraf** [comment]
I solved this problem in my work.
It didn't work when I proceeded with the administrator account, but it worked when I created and ran a new account.
I hope it helps.

**Comment by HanlinGao** [comment]
I have the same problem when I ran a model.fit() in notebook.
And I was in my conda environment, but still met this problem

**Comment by kinga-k-farkas** [comment]
I got the same error and I tried to follow the suggested steps: I created a new conda environment and installed prophet.  I ran model.fit() in the new environment and I again got the prophet_model.bin - Entry Point Not Found error message

**Comment by josemiguelCalvache** [comment]
> Platform : Windows 10 Python version : 3.8.8 Prophet : 1.1 (not fbprophet)
> 
> The 'cmdstanpy' and 'prophet' packages are successfully installed. But I am getting this error while running my model - "The procedure entry point _ZNt3bb19task_scheduler_init10initilaizeEiy could not be located in the dynamic link library D:/ProgramData/ Anaconda3/Lib/site-packages/prophet/stan_model/prophet_model.bin"
> 
> Any suggestions? ![image (2)](https://user-images.githubusercontent.com/20578797/187308498-6097b728-a23b-43ba-b92a-1e7ea3bf5562.png)

I downgrade mi versión of fbprophet, and a library named cmdstanpy was downgraded also to version 0.9.5, that way function to me, hope it function to you

**Comment by m-hammad** [comment]
That's how I resolved the issue.
Python 3.9
Prophet 1.1.1

`pip install  cmdstanpy`
Then in the libs import section, I've added
`import cmdstanpy`
`cmdstanpy.install_cmdstan(compiler=True)`

**Comment by sksharma7** [comment]
> Hey @Haridut, In order to solve this problem, you will have to keep 2 points under consideration.
> 
>     1. This package will not work under **"$ Base"** environment. So first, you will have to create separate environment, and install prophet in newly created environment.
> 
>     2. Then change your kernel from base to newly created environment's kernel.
> 
> 
> ### **CONCLUSION:** To use "prophet", you will have to change your environment from Base to any other environment (or create new one). And perform your entire "prophet" related task in that particular environment.
> 
> @Haridut , let me know whether it works for you or not.

I created new environment and installed prophet in that environment but still I am getting the same issue.

**Comment by sksharma7** [comment]
Finally what worked for me :

on conda prompt activate the environment using 

`conda activate envname`

then I ran this as per documentation https://mc-stan.org/cmdstanpy/installation.html

`conda install -c conda-forge cmdstanpy`

and import cmdstanpy

**Comment by fingoldo** [comment]
> `import cmdstanpy`
> `cmdstanpy.install_cmdstan(compiler=True)`

Amazing, thanks! Works from Jupyter notebook under WIndows after your fix.

**Comment by jaeil6557** [comment]
지금도 prophet 모듈이 포함된 ~.py를 pyinstaller로 exe를 빌드하여 실행하면 오류가 나네요.
어떻게 해결해야 되죠?
오류 내용은 다음과 같습니다.

(myenv) D:\프로그램\COINAUTO>cd dist

(myenv) D:\프로그램\COINAUTO\dist>test2
Installing CmdStan version: 2.32.0
Install directory: C:\Users\user\.cmdstan
17:05:01 - cmdstanpy - INFO - Add C++ toolchain to $PATH: C:\Users\user\.cmdstan\RTools40
CmdStan version 2.32.0 already installed
Traceback (most recent call last):
  File "test2.py", line 32, in <module>
  File "test2.py", line 20, in predict_price
  File "prophet\forecaster.py", line 143, in __init__
  File "prophet\forecaster.py", line 156, in _load_stan_backend
AttributeError: 'Prophet' object has no attribute 'stan_backend'
[33108] Failed to execute script 'test2' due to unhandled exception!
