### ISSUE TITLE
Error while running prophet with latest 1.1.2 version

### ISSUE THREAD

**Issue by hemajv** [facebook/prophet#2354]
With the new 1.1.2 release, I am facing a runtime error while training the prophet model as follows:

![Screenshot 2023-01-25 at 10 29 13 AM](https://user-images.githubusercontent.com/7343099/214651411-5dd071af-1a2a-4966-a6b1-eaca7c103929.png)

I did not have this issue in the previous version.

**Comment by tcuongd** [comment]
Thanks for reporting! What OS are you running?

**Comment by daniellevinson** [comment]
Getting the same error. Running on RHEL 7.9.
Downgrading to 1.1.1 works fine.
Also, when I run 1.1.2 locally with docker (base image `python:3.9-slim-buster`) it does not happen. Might be root user permissions, I'm not sure.
@hemajv @Roymprog were you guys able to resolve?

```
09-02-2023 19:44:47.244 [56609] DEBUG cmdstanpy - input tempfile: /tmp/tmpx5yef8r2/hqex_k6d.json
09-02-2023 19:44:47.259 [56609] DEBUG cmdstanpy - input tempfile: /tmp/tmpx5yef8r2/zxzwhvpz.json
09-02-2023 19:44:47.261 [56609] DEBUG cmdstanpy - idx 0
09-02-2023 19:44:47.261 [56609] DEBUG cmdstanpy - running CmdStan, num_threads: None
09-02-2023 19:44:47.261 [56609] DEBUG cmdstanpy - CmdStan args: ['/home/y/var/venv/lib/python3.9/site-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=43135', 'data', 'file=/tmp/tmpx5yef8r2/hqex_k6d.json', 'init=/tmp/tmpx5yef8r2/zxzwhvpz.json', 'output', 'file=/tmp/tmpx5yef8r2/prophet_modelxd347zfh/prophet_model-20230209194447.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
19:44:47 - cmdstanpy - INFO - Chain [1] start processing
09-02-2023 19:44:47.261 [56609] INFO cmdstanpy - Chain [1] start processing
19:44:47 - cmdstanpy - INFO - Chain [1] done processing
09-02-2023 19:44:47.274 [56609] INFO cmdstanpy - Chain [1] done processing
19:44:47 - cmdstanpy - ERROR - Chain [1] error: terminated by signal 11 Unknown error -11
09-02-2023 19:44:47.274 [56609] ERROR cmdstanpy - Chain [1] error: terminated by signal 11 Unknown error -11
09-02-2023 19:44:47.275 [56609] WARNING prophet.models - Optimization terminated abnormally. Falling back to Newton.
09-02-2023 19:44:47.275 [56609] DEBUG cmdstanpy - input tempfile: /tmp/tmpx5yef8r2/ua8xqxlx.json
09-02-2023 19:44:47.290 [56609] DEBUG cmdstanpy - input tempfile: /tmp/tmpx5yef8r2/m_6x_tmx.json
09-02-2023 19:44:47.291 [56609] DEBUG cmdstanpy - idx 0
09-02-2023 19:44:47.292 [56609] DEBUG cmdstanpy - running CmdStan, num_threads: None
09-02-2023 19:44:47.292 [56609] DEBUG cmdstanpy - CmdStan args: ['/home/y/var/venv/lib/python3.9/site-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=68082', 'data', 'file=/tmp/tmpx5yef8r2/ua8xqxlx.json', 'init=/tmp/tmpx5yef8r2/m_6x_tmx.json', 'output', 'file=/tmp/tmpx5yef8r2/prophet_model93q8yxye/prophet_model-20230209194447.csv', 'method=optimize', 'algorithm=newton', 'iter=10000']
19:44:47 - cmdstanpy - INFO - Chain [1] start processing
09-02-2023 19:44:47.292 [56609] INFO cmdstanpy - Chain [1] start processing
19:44:47 - cmdstanpy - INFO - Chain [1] done processing
09-02-2023 19:44:47.302 [56609] INFO cmdstanpy - Chain [1] done processing
19:44:47 - cmdstanpy - ERROR - Chain [1] error: terminated by signal 11 Unknown error -11
09-02-2023 19:44:47.302 [56609] ERROR cmdstanpy - Chain [1] error: terminated by signal 11 Unknown error -11
```

**Comment by pcoccoli** [comment]
Same problem here: 1.1.2 fails; 1.1.1 succeeds.
Red Hat Enterprise Linux 8.7
Python 3.9.2

**Comment by pcoccoli** [comment]
FWIW the error looks the same as #2227 and #2245 except the signal number is different in those; presumably it's because those are Windows and this is a Linux.

**Comment by RobKwiatkowski** [comment]
The same problem: 1.1.2 fails, downgrading to 1.1.1 solves the problem and everything works just fine.
Python 3.8
Linux

**Comment by YuanchenZhu2020** [comment]
Same problem here: 1.1.2 fails
OS: Windows 11
Python 3.8.10

**Comment by YuanchenZhu2020** [comment]
Same problem here: 1.1.2 fails
OS: Windows 11
Python 3.8.10

**Comment by vhphan** [comment]
Same problem.
Linux. Python 3.9 and Python 3.10
Downgrading to 1.1.1 solves the problem.

**Comment by tsuting** [comment]
Same problem, both 1.1.1 and 1.1.2 failed. 

If I change the `growth = flat`, it would be fine.

```python

from prophet import Prophet
import pandas as pd

model = Prophet(
    interval_width=0.95,
    growth="linear",
    seasonality_mode="multiplicative",
    yearly_seasonality=False,
    daily_seasonality=False,
    weekly_seasonality=False,
)
model.fit(
    pd.DataFrame(
        {
            "y": [5478, -2869],
            "ds": pd.date_range(start="2018-04-01", end="2018-05-01", freq="MS"),
        }
    )
)
```

**Comment by yc3993** [comment]
Same problem, downgrading to 1.1.1 works
Python 3.11.3

**Comment by ntomova** [comment]
Did anyone figure out how to fix it?

**Getting the same error on Mac:**

20:58:23 - cmdstanpy - INFO - Chain [1] start processing
20:58:23 - cmdstanpy - INFO - Chain [1] done processing
20:58:23 - cmdstanpy - ERROR - Chain [1] error: terminated by signal 11 Unknown error -11
Optimization terminated abnormally. Falling back to Newton.
20:58:23 - cmdstanpy - INFO - Chain [1] start processing
20:58:23 - cmdstanpy - INFO - Chain [1] done processing
20:58:23 - cmdstanpy - ERROR - Chain [1] error: terminated by signal 11 Unknown error -11
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
/opt/miniconda/lib/python3.7/site-packages/prophet/models.py in fit(self, stan_init, stan_data, **kwargs)
     95         try:
---> 96             self.stan_fit = self.model.optimize(**args)
     97         except RuntimeError as e:

/opt/miniconda/lib/python3.7/site-packages/cmdstanpy/model.py in optimize(self, data, seed, inits, output_dir, sig_figs, save_profile, algorithm, init_alpha, tol_obj, tol_rel_obj, tol_grad, tol_rel_grad, tol_param, history_size, iter, save_iterations, require_converged, show_console, refresh, time_fmt, timeout)
    737             else:
--> 738                 raise RuntimeError(msg)
    739         mle = CmdStanMLE(runset)

RuntimeError: Error during optimization! Command '/opt/miniconda/lib/python3.7/site-packages/prophet/stan_model/prophet_model.bin random seed=87376 data file=/tmp/tmps0semu9k/phvifpcq.json init=/tmp/tmps0semu9k/tkb85dwb.json output file=/tmp/tmps0semu9k/prophet_modeldlk7m4z1/prophet_model-20230429205823.csv method=optimize algorithm=lbfgs iter=10000' failed: 

During handling of the above exception, another exception occurred:

RuntimeError                              Traceback (most recent call last)
/tmp/ipykernel_47853/1873488016.py in <module>
----> 1 model = p.fit(data)

/opt/miniconda/lib/python3.7/site-packages/prophet/forecaster.py in fit(self, df, **kwargs)
   1179             self.params = self.stan_backend.sampling(stan_init, dat, self.mcmc_samples, **kwargs)
   1180         else:
-> 1181             self.params = self.stan_backend.fit(stan_init, dat, **kwargs)
   1182 
   1183         self.stan_fit = self.stan_backend.stan_fit

/opt/miniconda/lib/python3.7/site-packages/prophet/models.py in fit(self, stan_init, stan_data, **kwargs)
    101             logger.warning('Optimization terminated abnormally. Falling back to Newton.')
    102             args['algorithm'] = 'Newton'
--> 103             self.stan_fit = self.model.optimize(**args)
    104         params = self.stan_to_dict_numpy(
    105             self.stan_fit.column_names, self.stan_fit.optimized_params_np)

/opt/miniconda/lib/python3.7/site-packages/cmdstanpy/model.py in optimize(self, data, seed, inits, output_dir, sig_figs, save_profile, algorithm, init_alpha, tol_obj, tol_rel_obj, tol_grad, tol_rel_grad, tol_param, history_size, iter, save_iterations, require_converged, show_console, refresh, time_fmt, timeout)
    736                 get_logger().warning(msg)
    737             else:
--> 738                 raise RuntimeError(msg)
    739         mle = CmdStanMLE(runset)
    740         return mle

RuntimeError: Error during optimization! Command '/opt/miniconda/lib/python3.7/site-packages/prophet/stan_model/prophet_model.bin random seed=59279 data file=/tmp/tmps0semu9k/z82vkfsj.json init=/tmp/tmps0semu9k/74ezmatd.json output file=/tmp/tmps0semu9k/prophet_model77xtt8l9/prophet_model-20230429205823.csv method=optimize algorithm=newton iter=10000' failed:

**Comment by Aegean-C** [comment]
Same problem here: 1.1.2 fails
OS: Windows 10
Python 3.8.13

**Comment by imad24** [comment]
Same Problem here: 1.1.2 Fails and 1.1.1 Works.
OS: CentOS Linux 8
Python: 3.8.16

What's interesting is that it **works both for 1.1.2** and 1.1.1 if I use a different OS
for instance OS: Debian GNU/Linux 11 (bullseye)

For more context I use a Docker Image (with exactly the same sha) so I'm wondering if the problem dosn't come from the hosting OS ?

**Comment by shiikiii** [comment]
Same problem on unix vm:

13:49:08 - cmdstanpy - INFO - Chain [1] start processing
13:49:09 - cmdstanpy - INFO - Chain [1] done processing
13:49:09 - cmdstanpy - ERROR - Chain [1] error: terminated by signal 11 Unknown error -11
Optimization terminated abnormally. Falling back to Newton.
13:49:09 - cmdstanpy - INFO - Chain [1] start processing
13:49:09 - cmdstanpy - INFO - Chain [1] done processing
13:49:09 - cmdstanpy - ERROR - Chain [1] error: terminated by signal 11 Unknown error -11
Traceback (most recent call last):
  File "/opt/rh/rh-python38/root/usr/local/lib64/python3.8/site-packages/prophet/models.py", line 90, in fit
    self.stan_fit = self.model.optimize(**args)
  File "/opt/rh/rh-python38/root/usr/local/lib/python3.8/site-packages/cmdstanpy/model.py", line 738, in optimize
    raise RuntimeError(msg)
RuntimeError: Error during optimization! Command '/opt/rh/rh-python38/root/usr/local/lib64/python3.8/site-packages/prophet/stan_model/prophet_model.bin random seed=89781 data file=/tmp/tmpntgza1wt/5ydvewx9.json init=/tmp/tmpntgza1wt/sep5x5a8.json output file=/tmp/tmpntgza1wt/prophet_modelap8olkd8/prophet_model-20230704134908.csv method=optimize algorithm=lbfgs iter=10000' failed:

Downgraded back to 1.1.1 with holidays==0.18.0, works.

**Comment by dave12221** [comment]
save problem~, solved by: prophet==1.1.1  holidays==0.18.0
python 3.8.13, linux

**Comment by eangolaharman** [comment]
> 

Same issue. solve by prophet=1.1.1 holidays==0.18.0
python 3.8.13, ubuntu

**Comment by pengfei-chen** [comment]
> save problem~, solved by: prophet==1.1.1 holidays==0.18.0 python 3.8.13, linux

thanks , it works

**Comment by aks43725** [comment]
Downgrading prophet, cmdstanpy, and holidays don't work for me... https://github.com/facebook/prophet/issues/2227 gives me a solution that works:

```python
import cmdstanpy
cmdstanpy.install_cmdstan()
# cmdstanpy.install_cmdstan(compiler=True)  # for Windows
```

**Comment by mdeshmu** [comment]
when will this be fixed?

**Comment by imad24** [comment]
> > has anyone got any solution for this? when will this be fixed?
> 
> I was really looking forward to a fix for the 1.1.5 version (released yesterday 10/10/23), but it seems like we'll have to wait for the next updates.
> 
> Especially considering all the work that has been done from 1.1.1 ==> 1.1.5.

Sorry for the misleading info. I'm no longer having the problem with version 1.1.5
I'm using Prophet in a Docker container running on WSL.
The error occurs on versions 1.1.2/1.1.3/1.1.4 but everything **works well** when upgrading to version 1.1.5

Not sure though if it fixes the problem on every environement (Other Linux distros, Apple M1/M2).

**Comment by zhuzhuyan93** [comment]
why prophet has sososo much proplems, its so hard to use

**Comment by tvdboom** [comment]
same issue persists on prophet version 1.1.5 with holidays v0.41 on Windows Python 3.10. Any update on his issue?

**Comment by KonradIEO** [comment]
I have the same problem on Windows, python 3.12.7, prophet==1.1.6. Downgrading to 3.11 doesn't help.

**Comment by sykhan88** [comment]
Had the same problem on linux and downgrading to 1.1.1 solved it. But would love to see a solution to this in the latest version!!!
