### ISSUE TITLE
 error: subprocess-exited-with-error 

### ISSUE THREAD

**Issue by Veselov3** [facebook/prophet#2368]
C:\WINDOWS\system32>pip install WxPython --pre
Collecting WxPython
  Using cached wxPython-4.2.0.tar.gz (71.0 MB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [12 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\User\AppData\Local\Temp\pip-install-fwmzg42n\wxpython_a50359e94edf449c811d35bd510c71ce\setup.py", line 27, in <module>
          from buildtools.config import Config, msg, opj, runcmd, canGetSOName, getSOName
        File "C:\Users\User\AppData\Local\Temp\pip-install-fwmzg42n\wxpython_a50359e94edf449c811d35bd510c71ce\buildtools\config.py", line 30, in <module>
          from attrdict import AttrDict
        File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\site-packages\attrdict\__init__.py", line 5, in <module>
          from attrdict.mapping import AttrMap
        File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\site-packages\attrdict\mapping.py", line 4, in <module>
          from collections import Mapping
      ImportError: cannot import name 'Mapping' from 'collections' (C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\collections\__init__.py)
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

**Comment by WardBrian** [comment]
This issue seems to be with wxPython
