### ISSUE TITLE
Error when installing fbprophet with pystan version 3.3.0 on Kaggle notebook

### ISSUE THREAD

**Issue by md-al-imran-abir** [facebook/prophet#2409]
I first installed `pystan` using pip and then tried to install `fbprophet` but got the following error. However, when I installed version 2.19.1.1 of `pystan`, `fbprophet` was installed without error. Why is this happening? The error message:
```
Building wheels for collected packages: fbprophet
  Building wheel for fbprophet (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [39 lines of output]
      running bdist_wheel
      running build
      running build_py
      creating build
      creating build/lib
      creating build/lib/fbprophet
      creating build/lib/fbprophet/stan_model
      Traceback (most recent call last):
        File "<string>", line 36, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-kvv2k4ke/fbprophet_d1f46b36adda44fc9c84f3d41ce91fe2/setup.py", line 149, in <module>
          long_description_content_type='text/markdown',
        File "/opt/conda/lib/python3.7/site-packages/setuptools/__init__.py", line 153, in setup
          return distutils.core.setup(**attrs)
        File "/opt/conda/lib/python3.7/distutils/core.py", line 148, in setup
          dist.run_commands()
        File "/opt/conda/lib/python3.7/distutils/dist.py", line 966, in run_commands
          self.run_command(cmd)
        File "/opt/conda/lib/python3.7/distutils/dist.py", line 985, in run_command
          cmd_obj.run()
        File "/opt/conda/lib/python3.7/site-packages/wheel/bdist_wheel.py", line 325, in run
          self.run_command("build")
        File "/opt/conda/lib/python3.7/distutils/cmd.py", line 313, in run_command
          self.distribution.run_command(command)
        File "/opt/conda/lib/python3.7/distutils/dist.py", line 985, in run_command
          cmd_obj.run()
        File "/opt/conda/lib/python3.7/distutils/command/build.py", line 135, in run
          self.run_command(cmd_name)
        File "/opt/conda/lib/python3.7/distutils/cmd.py", line 313, in run_command
          self.distribution.run_command(command)
        File "/opt/conda/lib/python3.7/distutils/dist.py", line 985, in run_command
          cmd_obj.run()
        File "/tmp/pip-install-kvv2k4ke/fbprophet_d1f46b36adda44fc9c84f3d41ce91fe2/setup.py", line 48, in run
          build_models(target_dir)
        File "/tmp/pip-install-kvv2k4ke/fbprophet_d1f46b36adda44fc9c84f3d41ce91fe2/setup.py", line 38, in build_models
          StanBackendEnum.get_backend_class(backend).build_model(target_dir, MODEL_DIR)
        File "/tmp/pip-install-kvv2k4ke/fbprophet_d1f46b36adda44fc9c84f3d41ce91fe2/fbprophet/models.py", line 209, in build_model
          import pystan
      ModuleNotFoundError: No module named 'pystan'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for fbprophet
  Running setup.py clean for fbprophet
Failed to build fbprophet
Installing collected packages: cmdstanpy, fbprophet
  Attempting uninstall: cmdstanpy
    Found existing installation: cmdstanpy 1.1.0
    Uninstalling cmdstanpy-1.1.0:
      Successfully uninstalled cmdstanpy-1.1.0
  Running setup.py install for fbprophet ... error
  error: subprocess-exited-with-error
  
  × Running setup.py install for fbprophet did not run successfully.
  │ exit code: 1
  ╰─> [43 lines of output]
      running install
      /opt/conda/lib/python3.7/site-packages/setuptools/command/install.py:37: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
        setuptools.SetuptoolsDeprecationWarning,
      running build
      running build_py
      creating build
      creating build/lib
      creating build/lib/fbprophet
      creating build/lib/fbprophet/stan_model
      Traceback (most recent call last):
        File "<string>", line 36, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-kvv2k4ke/fbprophet_d1f46b36adda44fc9c84f3d41ce91fe2/setup.py", line 149, in <module>
          long_description_content_type='text/markdown',
        File "/opt/conda/lib/python3.7/site-packages/setuptools/__init__.py", line 153, in setup
          return distutils.core.setup(**attrs)
        File "/opt/conda/lib/python3.7/distutils/core.py", line 148, in setup
          dist.run_commands()
        File "/opt/conda/lib/python3.7/distutils/dist.py", line 966, in run_commands
          self.run_command(cmd)
        File "/opt/conda/lib/python3.7/distutils/dist.py", line 985, in run_command
          cmd_obj.run()
        File "/opt/conda/lib/python3.7/site-packages/setuptools/command/install.py", line 68, in run
          return orig.install.run(self)
        File "/opt/conda/lib/python3.7/distutils/command/install.py", line 545, in run
          self.run_command('build')
        File "/opt/conda/lib/python3.7/distutils/cmd.py", line 313, in run_command
          self.distribution.run_command(command)
        File "/opt/conda/lib/python3.7/distutils/dist.py", line 985, in run_command
          cmd_obj.run()
        File "/opt/conda/lib/python3.7/distutils/command/build.py", line 135, in run
          self.run_command(cmd_name)
        File "/opt/conda/lib/python3.7/distutils/cmd.py", line 313, in run_command
          self.distribution.run_command(command)
        File "/opt/conda/lib/python3.7/distutils/dist.py", line 985, in run_command
          cmd_obj.run()
        File "/tmp/pip-install-kvv2k4ke/fbprophet_d1f46b36adda44fc9c84f3d41ce91fe2/setup.py", line 48, in run
          build_models(target_dir)
        File "/tmp/pip-install-kvv2k4ke/fbprophet_d1f46b36adda44fc9c84f3d41ce91fe2/setup.py", line 38, in build_models
          StanBackendEnum.get_backend_class(backend).build_model(target_dir, MODEL_DIR)
        File "/tmp/pip-install-kvv2k4ke/fbprophet_d1f46b36adda44fc9c84f3d41ce91fe2/fbprophet/models.py", line 209, in build_model
          import pystan
      ModuleNotFoundError: No module named 'pystan'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: legacy-install-failure

× Encountered error while trying to install package.
╰─> fbprophet

note: This is an issue with the package mentioned above, not pip.
hint: See above for output from the failure.
```

N.B. I faced a similar problem on Colab also.

**Comment by md-al-imran-abir** [comment]
Oh, I see! I should use the `prophet` module instead of the `fbprophet` one. Unfortunately, the book I am reading used this module. So, it's an error from their side and so, I am closing this issue.

**Comment by Richardalphonse** [comment]
I am having the same issue while installing the Pystan and fbprophet packages in the colab

**Comment by md-al-imran-abir** [comment]
> I am having the same issue while installing the Pystan and fbprophet packages in the colab

Have you found a solution?

As you have not provided any details, I am assuming you tried something like `import fbprophet`. Try using `import prophet` instead.

**Comment by amineergin** [comment]
> > I am having the same issue while installing the Pystan and fbprophet packages in the colab
> 
> Have you found a solution?
> 
> As you have not provided any details, I am assuming you tried something like `import fbprophet`. Try using `import prophet` instead.

Thank you so much
