### ISSUE TITLE
fbprophet installing error

### ISSUE THREAD

**Issue by shreeganesha2001** [facebook/prophet#2569]
When iam installing fbprophet iam getting below error
Building wheels for collected packages: fbprophet
  Building wheel for fbprophet (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [42 lines of output]
      /tmp/pip-install-4g7uehcu/fbprophet_7a999db12e7e4181b5a07254eeb91ea7/setup.py:10: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
        from pkg_resources import (
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-4g7uehcu/fbprophet_7a999db12e7e4181b5a07254eeb91ea7/setup.py", line 122, in <module>
          setup(
        File "/opt/conda/lib/python3.10/site-packages/setuptools/__init__.py", line 103, in setup
          return distutils.core.setup(**attrs)
        File "/opt/conda/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 185, in setup
          return run_commands(dist)
        File "/opt/conda/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
          dist.run_commands()
        File "/opt/conda/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
          self.run_command(cmd)
        File "/opt/conda/lib/python3.10/site-packages/setuptools/dist.py", line 963, in run_command
          super().run_command(command)
        File "/opt/conda/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/opt/conda/lib/python3.10/site-packages/wheel/bdist_wheel.py", line 368, in run
          self.run_command("build")
        File "/opt/conda/lib/python3.10/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
          self.distribution.run_command(command)
        File "/opt/conda/lib/python3.10/site-packages/setuptools/dist.py", line 963, in run_command
          super().run_command(command)
        File "/opt/conda/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/opt/conda/lib/python3.10/site-packages/setuptools/_distutils/command/build.py", line 131, in run
          self.run_command(cmd_name)
        File "/opt/conda/lib/python3.10/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
          self.distribution.run_command(command)
        File "/opt/conda/lib/python3.10/site-packages/setuptools/dist.py", line 963, in run_command
          super().run_command(command)
        File "/opt/conda/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/tmp/pip-install-4g7uehcu/fbprophet_7a999db12e7e4181b5a07254eeb91ea7/setup.py", line 48, in run
          build_models(target_dir)
        File "/tmp/pip-install-4g7uehcu/fbprophet_7a999db12e7e4181b5a07254eeb91ea7/setup.py", line 38, in build_models
          StanBackendEnum.get_backend_class(backend).build_model(target_dir, MODEL_DIR)
        File "/tmp/pip-install-4g7uehcu/fbprophet_7a999db12e7e4181b5a07254eeb91ea7/fbprophet/models.py", line 209, in build_model
          import pystan
      ModuleNotFoundError: No module named 'pystan'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for fbprophet
  Running setup.py clean for fbprophet
Failed to build fbprophet
ERROR: Could not build wheels for fbprophet, which is required to install pyproject.toml-based projects
Note: you may need to restart the kernel to use updated packages.

**Comment by muhammed-hisham-T** [comment]
You can use Prophet instead of fbprophet
They have changed the name
