### ISSUE TITLE
Incompatible with numpy or unupdated library

### ISSUE THREAD

**Issue by jero98772** [facebook/prophet#2617]
i get this error  in python 3.12.4 in linux manjaro machine
with numpy at 2.1.1

```
Importing plotly failed. Interactive plots will not work.
Traceback (most recent call last):
  File "/tmp/test.py", line 1, in <module>
    from prophet import Prophet
  File "/tmp/prophet-env/lib/python3.12/site-packages/prophet/__init__.py", line 7, in <module>
    from prophet.forecaster import Prophet
  File "/tmp/prophet-env/lib/python3.12/site-packages/prophet/forecaster.py", line 28, in <module>
    class Prophet(object):
  File "/tmp/prophet-env/lib/python3.12/site-packages/prophet/forecaster.py", line 459, in Prophet
    ) -> NDArray[np.float_]:
                 ^^^^^^^^^
  File "/tmp/prophet-env/lib/python3.12/site-packages/numpy/__init__.py", line 400, in __getattr__
    raise AttributeError(
AttributeError: `np.float_` was removed in the NumPy 2.0 release. Use `np.float64` instead.


```

with this code simple code
```

from prophet import Prophet

```

i think the library is not updated

**Comment by tisba** [comment]
Fixed in https://github.com/facebook/prophet/pull/2592
