### ISSUE TITLE
Numpy Import Error During Installation

### ISSUE THREAD

**Issue by jyo64** [facebook/prophet#2646]
When I try to install Propher, I get the below error:
```
Building wheels for collected packages: fbprophet
  Building wheel for fbprophet (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Building wheel for fbprophet (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [77 lines of output]
      <string>:10: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
      <string>:19: SetuptoolsDeprecationWarning: The test command is disabled and references to it are deprecated.
      !!

              ********************************************************************************
              Please remove any references to `setuptools.command.test` in all supported versions of the affected package.

              This deprecation is overdue, please update your project and remove deprecated
              calls to avoid build errors in the future.
              ********************************************************************************

      !!
      /tmp/pip-build-env-ye1c6acp/overlay/lib/python3.11/site-packages/setuptools/_distutils/dist.py:261: UserWarning: Unknown distribution option: 'test_suite'
        warnings.warn(msg)
      running bdist_wheel
      running build
      running build_py
      creating build/lib/fbprophet/stan_model
      Traceback (most recent call last):
        File "/home/jyo/kddm2/venv/lib64/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/home/jyo/kddm2/venv/lib64/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/home/jyo/kddm2/venv/lib64/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 251, in build_wheel
          return _build_backend().build_wheel(wheel_directory, config_settings,
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-ye1c6acp/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 438, in build_wheel
          return _build(['bdist_wheel', '--dist-info-dir', str(metadata_directory)])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-ye1c6acp/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 426, in _build
          return self._build_with_temp_dir(
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-ye1c6acp/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 407, in _build_with_temp_dir
          self.run_setup()
        File "/tmp/pip-build-env-ye1c6acp/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 522, in run_setup
          super().run_setup(setup_script=setup_script)
        File "/tmp/pip-build-env-ye1c6acp/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 320, in run_setup
          exec(code, locals())
        File "<string>", line 122, in <module>
        File "/tmp/pip-build-env-ye1c6acp/overlay/lib/python3.11/site-packages/setuptools/__init__.py", line 117, in setup
          return distutils.core.setup(**attrs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-ye1c6acp/overlay/lib/python3.11/site-packages/setuptools/_distutils/core.py", line 183, in setup
          return run_commands(dist)
                 ^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-ye1c6acp/overlay/lib/python3.11/site-packages/setuptools/_distutils/core.py", line 199, in run_commands
          dist.run_commands()
        File "/tmp/pip-build-env-ye1c6acp/overlay/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 954, in run_commands
          self.run_command(cmd)
        File "/tmp/pip-build-env-ye1c6acp/overlay/lib/python3.11/site-packages/setuptools/dist.py", line 995, in run_command
          super().run_command(command)
        File "/tmp/pip-build-env-ye1c6acp/overlay/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 973, in run_command
          cmd_obj.run()
        File "/tmp/pip-build-env-ye1c6acp/overlay/lib/python3.11/site-packages/setuptools/command/bdist_wheel.py", line 381, in run
          self.run_command("build")
        File "/tmp/pip-build-env-ye1c6acp/overlay/lib/python3.11/site-packages/setuptools/_distutils/cmd.py", line 316, in run_command
          self.distribution.run_command(command)
        File "/tmp/pip-build-env-ye1c6acp/overlay/lib/python3.11/site-packages/setuptools/dist.py", line 995, in run_command
          super().run_command(command)
        File "/tmp/pip-build-env-ye1c6acp/overlay/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 973, in run_command
          cmd_obj.run()
        File "/tmp/pip-build-env-ye1c6acp/overlay/lib/python3.11/site-packages/setuptools/_distutils/command/build.py", line 135, in run
          self.run_command(cmd_name)
        File "/tmp/pip-build-env-ye1c6acp/overlay/lib/python3.11/site-packages/setuptools/_distutils/cmd.py", line 316, in run_command
          self.distribution.run_command(command)
        File "/tmp/pip-build-env-ye1c6acp/overlay/lib/python3.11/site-packages/setuptools/dist.py", line 995, in run_command
          super().run_command(command)
        File "/tmp/pip-build-env-ye1c6acp/overlay/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 973, in run_command
          cmd_obj.run()
        File "<string>", line 48, in run
        File "<string>", line 36, in build_models
        File "/tmp/pip-install-_8pfiw_9/fbprophet_5b240083d2ca474a984ad0f4a6c16512/fbprophet/__init__.py", line 8, in <module>
          from fbprophet.forecaster import Prophet
        File "/tmp/pip-install-_8pfiw_9/fbprophet_5b240083d2ca474a984ad0f4a6c16512/fbprophet/forecaster.py", line 14, in <module>
          import numpy as np
      ModuleNotFoundError: No module named 'numpy'
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for fbprophet
Failed to build fbprophet
```

I already tried installing Numpy and re-running the script. But this still doesn't work.

**Comment by jyo64** [comment]
Was fixed by running:
```
python -m pip install prophet
```
