### ISSUE TITLE
Installing with PyPI - Errno 39

### ISSUE THREAD

**Issue by andmib** [facebook/prophet#301]
I'm trying to update fbprophet in my Docker container based on Debian GNU/Linux 8 (jessie).

I get the following error when I run `pip install -U fbprophet`:
```
Exception:
Traceback (most recent call last):
  File "/opt/conda/lib/python3.6/shutil.py", line 544, in move
    os.rename(src, real_dst)
OSError: [Errno 18] Invalid cross-device link: '/opt/conda/lib/python3.6/site-packages/numpy' -> '/tmp/pip-_b5qhid2-uninstall/opt/conda/lib/python3.6/site-packages/numpy'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/conda/lib/python3.6/site-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/opt/conda/lib/python3.6/site-packages/pip/commands/install.py", line 342, in run
    prefix=options.prefix_path,
  File "/opt/conda/lib/python3.6/site-packages/pip/req/req_set.py", line 778, in install
    requirement.uninstall(auto_confirm=True)
  File "/opt/conda/lib/python3.6/site-packages/pip/req/req_install.py", line 754, in uninstall
    paths_to_remove.remove(auto_confirm)
  File "/opt/conda/lib/python3.6/site-packages/pip/req/req_uninstall.py", line 115, in remove
    renames(path, new_path)
  File "/opt/conda/lib/python3.6/site-packages/pip/utils/__init__.py", line 267, in renames
    shutil.move(old, new)
  File "/opt/conda/lib/python3.6/shutil.py", line 556, in move
    rmtree(src)
  File "/opt/conda/lib/python3.6/shutil.py", line 480, in rmtree
    _rmtree_safe_fd(fd, path, onerror)
  File "/opt/conda/lib/python3.6/shutil.py", line 422, in _rmtree_safe_fd
    onerror(os.rmdir, fullname, sys.exc_info())
  File "/opt/conda/lib/python3.6/shutil.py", line 420, in _rmtree_safe_fd
    os.rmdir(name, dir_fd=topfd)
OSError: [Errno 39] Directory not empty: '__pycache__'
```

Any suggestions?

**Comment by bletham** [comment]
This seems to be an issue with pip when /tmp/ is on a separate filesystem (due to being a virtual environment):
https://groups.google.com/forum/#!topic/python-virtualenv/GPXAi9WZKIs

In the thread there they suggest a workaround by setting the TMPDIR environment variable that should work. Also seen here:
https://community.webfaction.com/questions/2287/upgrading-django-from-104-to-114-in-pinax-07-on-webfaction-produces-oserror

**Comment by bletham** [comment]
I'm going to close this since it does seem to be external to Prophet, but feel free to re-open if you're still having issues with this.

**Comment by binary1230** [comment]
connecting dots for future travelers, if anyone's experiencing this on virtualbox running a linux guest with a vboxfs share from the host, there's a virtualbox bug causing this same error with pip 

https://www.virtualbox.org/ticket/8761

**Comment by chance2021** [comment]
Here is the solution which works for me...
```
pip3 install pyclean 
cd /opt/conda/lib/python3.6/
sudo pyclean -v . 
```
