### ISSUE TITLE
flask-spyne installation error

### ISSUE THREAD

**Issue by AnanthababuA** [facebook/prophet#437]
hi

i am trying to install on flask-spyne & then displaying error message. how i can solve this problem..

(venv) babu@babu-ananth ~ $ pip install flask-spyne
Collecting flask-spyne
  Using cached Flask-Spyne-0.3.1.tar.gz
Requirement already satisfied: flask in ./venv/lib/python3.5/site-packages (from flask-spyne)
Collecting spyne (from flask-spyne)
  Using cached spyne-2.12.14.tar.gz
Collecting sec-wall (from flask-spyne)
  Using cached sec-wall-1.2.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-f256tvwd/sec-wall/setup.py", line 30, in <module>
        packages = find_packages(b"src"),
      File "/home/babu/venv/lib/python3.5/site-packages/setuptools/__init__.py", line 60, in find
        cls._build_filter(*include)))
      File "/home/babu/venv/lib/python3.5/site-packages/setuptools/__init__.py", line 76, in _find_packages_iter
        package = rel_path.replace(os.path.sep, '.')
    TypeError: a bytes-like object is required, not 'str'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-f256tvwd/sec-wall/

**Comment by bletham** [comment]
This is a different package.
