### ISSUE TITLE
pip install paramiko error

### ISSUE THREAD

**Issue by rajapraveen1021** [facebook/prophet#453]
Hi all,

When trying to install paramiko, using 'pip install paramiko', I get the error :
command python setup.py egg_info failed with error code 1 in /tmp/pip_build_root/pynacl
Can anyone suggest??

Error Logs:
----------------------------------------
Cleaning up...
  Removing temporary dir /tmp/pip_build_root...
Command python setup.py egg_info failed with error code 1 in /tmp/pip_build_root/pynacl
Exception information:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/pip/basecommand.py", line 122, in main
    status = self.run(options, args)
  File "/usr/lib/python2.7/dist-packages/pip/commands/install.py", line 278, in run
    requirement_set.prepare_files(finder, force_root_egg_info=self.bundle, bundle=self.bundle)
  File "/usr/lib/python2.7/dist-packages/pip/req.py", line 1230, in prepare_files
    req_to_install.run_egg_info()
  File "/usr/lib/python2.7/dist-packages/pip/req.py", line 326, in run_egg_info
    command_desc='python setup.py egg_info')
  File "/usr/lib/python2.7/dist-packages/pip/util.py", line 715, in call_subprocess
    % (command_desc, proc.returncode, cwd))
InstallationError: Command python setup.py egg_info failed with error code 1 in /tmp/pip_build_root/pynacl

~

**Comment by bletham** [comment]
This is for a different package.

**Comment by Shaddoh** [comment]
Hello, Same error message on python2.6.
I need to get paramiko 2.3.2 installed
