### ISSUE TITLE
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-hop2iuus/jcconv/

### ISSUE THREAD

**Issue by vsnetvn** [facebook/prophet#491]
I get this error when I run:

```
root@ubuntu:~# pip install -r /opt/odoo/requirements.txt 
Collecting Babel==2.3.4 (from -r /opt/odoo/requirements.txt (line 1))
  Using cached Babel-2.3.4-py2.py3-none-any.whl
Collecting decorator==4.0.10 (from -r /opt/odoo/requirements.txt (line 2))
  Using cached decorator-4.0.10-py2.py3-none-any.whl
Collecting docutils==0.12 (from -r /opt/odoo/requirements.txt (line 3))
  Using cached docutils-0.12-py3-none-any.whl
Collecting ebaysdk==2.1.4 (from -r /opt/odoo/requirements.txt (line 4))
  Using cached ebaysdk-2.1.4.tar.gz
Collecting feedparser==5.2.1 (from -r /opt/odoo/requirements.txt (line 5))
  Using cached feedparser-5.2.1.tar.bz2
Collecting gevent==1.1.2 (from -r /opt/odoo/requirements.txt (line 6))
  Using cached gevent-1.1.2-cp35-cp35m-manylinux1_x86_64.whl
Collecting greenlet==0.4.10 (from -r /opt/odoo/requirements.txt (line 7))
  Using cached greenlet-0.4.10-cp35-cp35m-manylinux1_x86_64.whl
Collecting jcconv==0.2.3 (from -r /opt/odoo/requirements.txt (line 8))
  Using cached jcconv-0.2.3.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-hop2iuus/jcconv/setup.py", line 17
        print "unit tests have failed!"
                                      ^
    SyntaxError: Missing parentheses in call to 'print'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-hop2iuus/jcconv/
```

What am I doing wrong?
I am on ubuntu 16.04

**Comment by bletham** [comment]
This appears to be for a different project than this issue tracker, I'd recommend posting in their issue tracker, which looks like this one: https://github.com/odoo/odoo
