### ISSUE TITLE
Prophet hangs when input dataframe's ds column is a non nanosecond timestamp format

### ISSUE THREAD

**Issue by leafonsword** [facebook/prophet#495]
Prophet support nanosecond timestamp format,so this test input csv works ok:
```
ds,y
1521537900000000000,2219.76
1521538200000000000,2309.4666666666667
1521538500000000000,2285.71
1521538800000000000,2297.4766666666665
1521539100000000000,2244.4466666666667
1521539400000000000,2264.7066666666665
1521539700000000000,2188.2933333333335
1521540000000000000,2731.826666666667
1521540300000000000,2650.81
1521540600000000000,2457.45
1521540900000000000,2384.596666666667
1521541200000000000,2380.6466666666665
1521541500000000000,2315.3
1521541800000000000,2373.14
1521542100000000000,2358.71
1521542400000000000,2327.516666666667
1521542700000000000,2093.05
1521543000000000000,2055.673333333333
1521543300000000000,2051.1866666666665
1521543600000000000,2164.15
1521543900000000000,2057.5133333333333
1521544200000000000,1948.69
1521544500000000000,1954.7866666666666
1521544800000000000,1961.4333333333334
1521545100000000000,1876.1366666666668
1521545400000000000,1974.2333333333333
1521545700000000000,1940.6866666666667
1521546000000000000,1900.63
1521546300000000000,1926.4666666666667
1521546600000000000,1924.2433333333333
1521546900000000000,1841.4766666666667
1521547200000000000,2077.963333333333
1521547500000000000,2129.5533333333333
1521547800000000000,2022.84
1521548100000000000,2004.5533333333333
1521548400000000000,2032.7433333333333
1521548700000000000,1974.7433333333333
1521549000000000000,2063.7066666666665
1521549300000000000,2030.0566666666666
1521549600000000000,2007.1933333333334
1521549900000000000,1816.38
1521550200000000000,1868.1
1521550500000000000,1776.84
1521550800000000000,1954.2933333333333
1521551100000000000,1864.6033333333332
1521551400000000000,1734.5566666666666
1521551700000000000,1743.8966666666668
1521552000000000000,1795.2866666666666
1521552300000000000,1724.2866666666666
1521552600000000000,1799.5733333333333
1521552900000000000,1785.7733333333333
1521553200000000000,1770.7333333333333
1521553500000000000,1723.2233333333334
1521553800000000000,1746.8066666666666
1521554100000000000,1680.15
1521554400000000000,1910.14
1521554700000000000,1923.6933333333334
1521555000000000000,1896.0966666666666
1521555300000000000,1893.6966666666667
1521555600000000000,1897.1433333333334
1521555900000000000,1829.3433333333332
1521556200000000000,1902.1866666666667
1521556500000000000,1830.0866666666666
1521556800000000000,1786.2133333333334
1521557100000000000,1597.5266666666666
1521557400000000000,1641.11
1521557700000000000,1584.5433333333333
1521558000000000000,1641.3
1521558300000000000,1613.0866666666666
1521558600000000000,1547.2133333333334
1521558900000000000,1522.8166666666666
1521559200000000000,1523.01
1521559500000000000,1483.7733333333333
1521559800000000000,1542.8933333333334
1521560100000000000,1538.6366666666668
1521560400000000000,1482.8333333333333
1521560700000000000,1436.3266666666666
1521561000000000000,1841.41
1521561300000000000,1449.65
1521561600000000000,1896.8266666666666
1521561900000000000,1710.41
1521562200000000000,1525.1766666666667
1521562500000000000,1472.2133333333334
1521562800000000000,1474.1533333333334
1521563100000000000,1421.61
1521563400000000000,2143.36
1521563700000000000,2321.366666666667
1521564000000000000,2351.64
1521564300000000000,2306.06
```

<img width="986" alt="default" src="https://user-images.githubusercontent.com/1754580/38594732-4c17bec8-3d7a-11e8-953f-08c59342264d.png">

But if I transform  former input csv to microsecond timestamp format:
```
ds,y
1521537900,2219.76
1521538200,2309.4666666666667
1521538500,2285.71
1521538800,2297.4766666666665
1521539100,2244.4466666666667
1521539400,2264.7066666666665
1521539700,2188.2933333333335
1521540000,2731.826666666667
1521540300,2650.81
1521540600,2457.45
1521540900,2384.596666666667
1521541200,2380.6466666666665
1521541500,2315.3
1521541800,2373.14
1521542100,2358.71
1521542400,2327.516666666667
1521542700,2093.05
1521543000,2055.673333333333
1521543300,2051.1866666666665
1521543600,2164.15
1521543900,2057.5133333333333
1521544200,1948.69
1521544500,1954.7866666666666
1521544800,1961.4333333333334
1521545100,1876.1366666666668
1521545400,1974.2333333333333
1521545700,1940.6866666666667
1521546000,1900.63
1521546300,1926.4666666666667
1521546600,1924.2433333333333
1521546900,1841.4766666666667
1521547200,2077.963333333333
1521547500,2129.5533333333333
1521547800,2022.84
1521548100,2004.5533333333333
1521548400,2032.7433333333333
1521548700,1974.7433333333333
1521549000,2063.7066666666665
1521549300,2030.0566666666666
1521549600,2007.1933333333334
1521549900,1816.38
1521550200,1868.1
1521550500,1776.84
1521550800,1954.2933333333333
1521551100,1864.6033333333332
1521551400,1734.5566666666666
1521551700,1743.8966666666668
1521552000,1795.2866666666666
1521552300,1724.2866666666666
1521552600,1799.5733333333333
1521552900,1785.7733333333333
1521553200,1770.7333333333333
1521553500,1723.2233333333334
1521553800,1746.8066666666666
1521554100,1680.15
1521554400,1910.14
1521554700,1923.6933333333334
1521555000,1896.0966666666666
1521555300,1893.6966666666667
1521555600,1897.1433333333334
1521555900,1829.3433333333332
1521556200,1902.1866666666667
1521556500,1830.0866666666666
1521556800,1786.2133333333334
1521557100,1597.5266666666666
1521557400,1641.11
1521557700,1584.5433333333333
1521558000,1641.3
1521558300,1613.0866666666666
1521558600,1547.2133333333334
1521558900,1522.8166666666666
1521559200,1523.01
1521559500,1483.7733333333333
1521559800,1542.8933333333334
1521560100,1538.6366666666668
1521560400,1482.8333333333333
1521560700,1436.3266666666666
1521561000,1841.41
1521561300,1449.65
1521561600,1896.8266666666666
1521561900,1710.41
1521562200,1525.1766666666667
1521562500,1472.2133333333334
1521562800,1474.1533333333334
1521563100,1421.61
1521563400,2143.36
1521563700,2321.366666666667
1521564000,2351.64
1521564300,2306.06
```
Then prophet will hang, terminal shows:
```
......
Initial log joint probability = -3.25666
    Iter      log prob        ||dx||      ||grad||       alpha      alpha0  # evals  Notes
      82       186.024    7.4305e-09       49.4259      0.2542     0.02542      129
Optimization terminated normally:
  Convergence detected: absolute parameter change was below tolerance

```

<img width="798" alt="default" src="https://user-images.githubusercontent.com/1754580/38595139-8cc23b40-3d7c-11e8-8aad-178e138c06ff.png">

**Comment by bletham** [comment]
Thanks for including the data!
Prophet uses the pandas datetime format for the `ds` column, and sometimes that converts in unexpected ways. The specific code used is `df['ds'] = pd.to_datetime(df['ds'])`.

For the first dataset (19 digit numbers), this is converted like so:
```
                   ds            y
0 2018-03-20 09:25:00  2219.760000
1 2018-03-20 09:30:00  2309.466667
2 2018-03-20 09:35:00  2285.710000
3 2018-03-20 09:40:00  2297.476667
4 2018-03-20 09:45:00  2244.446667
```
So, 5 minutes between each point.

For the second dataset (10 digit numbers), this is converted like:
```
                             ds            y
0 1970-01-01 00:00:01.521537900  2219.760000
1 1970-01-01 00:00:01.521538200  2309.466667
2 1970-01-01 00:00:01.521538500  2285.710000
3 1970-01-01 00:00:01.521538800  2297.476667
4 1970-01-01 00:00:01.521539100  2244.446667
```
So, 3e-7 seconds between each point.

You should definitely make sure that `pd.to_datetime` is giving you the conversion you expect.
This issue should probably be discussed in the documentation.

Anyway, I wouldn't expect Prophet to freeze for either of these so hopefully we can get to the bottom of that. If I do
```
m = Prophet()
m.fit(df)
fcst = m.predict()
```
for either of these dataframes, it actually works for me and produces the same y's because seasonality ends up being disabled for both. Could you post the arguments you passed to `Prophet` so I can try to reproduce the freeze?

**Comment by bletham** [comment]
I see, with future days I get the error
```
>>> forecast = m.predict(future)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.5/dist-packages/fbprophet-0.2.1-py3.5.egg/fbprophet/forecaster.py", line 876, in predict
    intervals = self.predict_uncertainty(df)
  File "/usr/local/lib/python3.5/dist-packages/fbprophet-0.2.1-py3.5.egg/fbprophet/forecaster.py", line 1104, in predict_uncertainty
    sim_values = self.sample_posterior_predictive(df)
  File "/usr/local/lib/python3.5/dist-packages/fbprophet-0.2.1-py3.5.egg/fbprophet/forecaster.py", line 1068, in sample_posterior_predictive
    sim = self.sample_model(df, seasonal_features, i)
  File "/usr/local/lib/python3.5/dist-packages/fbprophet-0.2.1-py3.5.egg/fbprophet/forecaster.py", line 1131, in sample_model
    trend = self.sample_predictive_trend(df, iteration)
  File "/usr/local/lib/python3.5/dist-packages/fbprophet-0.2.1-py3.5.egg/fbprophet/forecaster.py", line 1176, in sample_predictive_trend
    changepoint_ts_new = sorted(np.random.uniform(1, T, n_changes))
  File "mtrand.pyx", line 1307, in mtrand.RandomState.uniform
  File "mtrand.pyx", line 242, in mtrand.cont2_array_sc
MemoryError
```
The issue is that we sample future trend changepoints based on the time resolution of the history. Because of the bad time formatting the time resolution of the history is 3e-7s, but the future is 7 days so it is a very large set of points  from which it is sampling the future changepoints.

This should be made more robust to fine time resolution with a long future.

**Comment by jheffez** [comment]
Having same issue with latest version. fbprophet==0.3.post2. Getting same error when doing forcast.

```
Dataset:
tail:
      ds         y
873  873  1.032904
874  874  0.665769
875  875  1.038095
876  876  0.817874
877  877  0.977097
878  878  0.941759
879  879  1.017852
880  880  0.961370
881  881  1.054307
882  882  1.100658

print (future.tail(11))
			   ds
882 1970-01-01 00:00:00.000000882
883 1970-01-02 00:00:00.000000882
884 1970-01-03 00:00:00.000000882
885 1970-01-04 00:00:00.000000882
886 1970-01-05 00:00:00.000000882
887 1970-01-06 00:00:00.000000882
888 1970-01-07 00:00:00.000000882
889 1970-01-08 00:00:00.000000882
890 1970-01-09 00:00:00.000000882
891 1970-01-10 00:00:00.000000882
892 1970-01-11 00:00:00.000000882


---------------------------------------------------------------------------
MemoryError                               Traceback (most recent call last)
<ipython-input-21-8bd6275b8ead> in <module>
      7 
      8 #forecast the data for future data
----> 9 forecast = m.predict(future)
     10 # forecast[['ds', 'yhat', 'yhat_lower', 'yhat_upper']].tail()
     11 

/home/jakeh66/py/36env/lib64/python3.6/site-packages/fbprophet/forecaster.py in predict(self, df)
   1040         df['trend'] = self.predict_trend(df)
   1041         seasonal_components = self.predict_seasonal_components(df)
-> 1042         intervals = self.predict_uncertainty(df)
   1043 
   1044         # Drop columns except ds, cap, floor, and trend

/home/jakeh66/py/36env/lib64/python3.6/site-packages/fbprophet/forecaster.py in predict_uncertainty(self, df)
   1242         Dataframe with uncertainty intervals.
   1243         """
-> 1244         sim_values = self.sample_posterior_predictive(df)
   1245 
   1246         lower_p = 100 * (1.0 - self.interval_width) / 2

/home/jakeh66/py/36env/lib64/python3.6/site-packages/fbprophet/forecaster.py in sample_posterior_predictive(self, df)
   1206                     iteration=i,
   1207                     s_a=component_cols['additive_terms'],
-> 1208                     s_m=component_cols['multiplicative_terms'],
   1209                 )
   1210                 for key in sim_values:

/home/jakeh66/py/36env/lib64/python3.6/site-packages/fbprophet/forecaster.py in sample_model(self, df, seasonal_features, iteration, s_a, s_m)
   1271         Dataframe with trend and yhat, each like df['t'].
   1272         """
-> 1273         trend = self.sample_predictive_trend(df, iteration)
   1274 
   1275         beta = self.params['beta'][iteration]

/home/jakeh66/py/36env/lib64/python3.6/site-packages/fbprophet/forecaster.py in sample_predictive_trend(self, df, iteration)
   1311             n_changes = 0
   1312         if n_changes > 0:
-> 1313             changepoint_ts_new = 1 + np.random.rand(n_changes) * (T - 1)
   1314             changepoint_ts_new.sort()
   1315         else:

mtrand.pyx in mtrand.RandomState.rand()

mtrand.pyx in mtrand.RandomState.random_sample()

mtrand.pyx in mtrand.cont0_array()

MemoryError: ```

**Comment by Rym96** [comment]
I am having the same issue 
I applied to my date are converted with  pd.to_datetime(my_data['ds'])
Did you find a way to fix it ? 

alueError                                Traceback (most recent call last)
<ipython-input-18-6a35f92430e7> in <module>()
      1 futur = data_prophet.make_future_dataframe(periods=365 * 2, freq='D')
----> 2 dvlptstaff_forecast = data_prophet.predict(futur)

/opt/conda/lib/python3.6/site-packages/fbprophet/forecaster.py in predict(self, df)
   1040         df['trend'] = self.predict_trend(df)
   1041         seasonal_components = self.predict_seasonal_components(df)
-> 1042         intervals = self.predict_uncertainty(df)
   1043 
   1044         # Drop columns except ds, cap, floor, and trend

/opt/conda/lib/python3.6/site-packages/fbprophet/forecaster.py in predict_uncertainty(self, df)
   1242         Dataframe with uncertainty intervals.
   1243         """
-> 1244         sim_values = self.sample_posterior_predictive(df)
   1245 
   1246         lower_p = 100 * (1.0 - self.interval_width) / 2

/opt/conda/lib/python3.6/site-packages/fbprophet/forecaster.py in sample_posterior_predictive(self, df)
   1206                     iteration=i,
   1207                     s_a=component_cols['additive_terms'],
-> 1208                     s_m=component_cols['multiplicative_terms'],
   1209                 )
   1210                 for key in sim_values:

/opt/conda/lib/python3.6/site-packages/fbprophet/forecaster.py in sample_model(self, df, seasonal_features, iteration, s_a, s_m)
   1274 
   1275         beta = self.params['beta'][iteration]
-> 1276         Xb_a = np.matmul(seasonal_features.values, beta * s_a) * self.y_scale
   1277         Xb_m = np.matmul(seasonal_features.values, beta * s_m)
   1278 

/opt/conda/lib/python3.6/site-packages/pandas/core/series.py in __array_wrap__(self, result, context)
    646         """
    647         return self._constructor(result, index=self.index,
--> 648                                  copy=False).__finalize__(self)
    649 
    650     def __array_prepare__(self, result, context=None):

/opt/conda/lib/python3.6/site-packages/pandas/core/series.py in __init__(self, data, index, dtype, name, copy, fastpath)
    260                             'Length of passed values is {val}, '
    261                             'index implies {ind}'
--> 262                             .format(val=len(data), ind=len(index)))
    263                 except TypeError:
    264                     pass

ValueError: Length of passed values is 737, index implies 20
