### ISSUE TITLE
Error "ValueError: Invalid frequency: 3600"

### ISSUE THREAD

**Issue by tutnes** [facebook/prophet#502]
Trying to do this:
`payment = payment.rename(columns={'Time': 'ds', 'Operations': 'y'})
payment_prophet = fbprophet.Prophet(changepoint_prior_scale=0.01)
payment_prophet.fit(payment)

payment_forecast = payment_prophet.make_future_dataframe(periods=2, freq=60*60, include_history=False)`

But getting this error:

`INFO:fbprophet.forecaster:Disabling yearly seasonality. Run prophet with yearly_seasonality=True to override this.
Traceback (most recent call last):
  File "C:\Users\tarje\AppData\Local\Programs\Python\Python36-32\lib\site-packages\pandas\tseries\frequencies.py", line 469, in to_offset
    splitted = re.split(opattern, freq)
  File "C:\Users\tarje\AppData\Local\Programs\Python\Python36-32\lib\re.py", line 212, in split
    return _compile(pattern, flags).split(string, maxsplit)
TypeError: expected string or bytes-like object

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\github\predict-py\predv2.py", line 22, in <module>
    payment_forecast = payment_prophet.make_future_dataframe(periods=2, freq=60*60, include_history=False)
  File "C:\Users\tarje\AppData\Local\Programs\Python\Python36-32\lib\site-packages\fbprophet\forecaster.py", line 1221, in make_future_dataframe
    freq=freq)
  File "C:\Users\tarje\AppData\Local\Programs\Python\Python36-32\lib\site-packages\pandas\core\indexes\datetimes.py", line 2057, in date_range
    closed=closed, **kwargs)
  File "C:\Users\tarje\AppData\Local\Programs\Python\Python36-32\lib\site-packages\pandas\util\_decorators.py", line 118, in wrapper
    return func(*args, **kwargs)
  File "C:\Users\tarje\AppData\Local\Programs\Python\Python36-32\lib\site-packages\pandas\core\indexes\datetimes.py", line 292, in __new__
    freq = to_offset(freq)
  File "C:\Users\tarje\AppData\Local\Programs\Python\Python36-32\lib\site-packages\pandas\util\_decorators.py", line 118, in wrapper
    return func(*args, **kwargs)
  File "C:\Users\tarje\AppData\Local\Programs\Python\Python36-32\lib\site-packages\pandas\tseries\frequencies.py", line 494, in to_offset
    raise ValueError(_INVALID_FREQ_ERROR.format(freq))
ValueError: Invalid frequency: 3600`

Running version:
`C:\github\pstools>pip show fbprophet
Name: fbprophet
Version: 0.2.1
Summary: Automatic Forecasting Procedure
Home-page: https://facebook.github.io/prophet/
Author: Sean J. Taylor <sjt@fb.com>, Ben Letham <bletham@fb.com>
Author-email: sjt@fb.com
License: BSD
Location: c:\users\tarje\appdata\local\programs\python\python36-32\lib\site-packages
Requires: pandas, matplotlib, pystan
Required-by:`

**Comment by tutnes** [comment]
Ok,

I found the documentation on Pandas. 
https://pandas.pydata.org/pandas-docs/stable/timeseries.html#offset-aliases
