### ISSUE TITLE
one data data frequency 20 second

### ISSUE THREAD

**Issue by rds99** [facebook/prophet#540]
Hi 
Is Prophet appropriate for one day data sampled every 20 seconds, need to forecast 60 to 300 seconds ahead?
Any worked out examples for similar time scale would be helpful, thanks

**Comment by bletham** [comment]
The closest example that I have, which you've probably seen, is the example with 2 months of 5-minute resolution in https://facebook.github.io/prophet/docs/non-daily_data.html. 

The actual time resolution doesn't matter at all (Prophet is a continuous-time model), the only thing you'd have to consider would be that it could get pretty slow if you were trying to throw too much data at it. The example in the documentation has 18,000 data points and works fine. 20 second resolution for one day would be 4,000 data points, so that shouldn't be an issue at all. And 60 to 300 seconds predictions would not be an issue either.

**Comment by rds99** [comment]
thanks,
I looked at that example you mentioned, looks like a close proxy. For some reason I cant install pystan for windows, looks like compiler issues. Could you kindly help
when i do
import pystan
model_code = 'parameters {real y;} model {y ~ normal(0,1);}'
model = pystan.StanModel(model_code=model_code)
y = model.sampling(n_jobs=1).extract()['y']
y.mean()  # with luck the result will be near 0

i get error as follows

INFO:pystan:COMPILING THE C++ CODE FOR MODEL anon_model_5944b02c79788fa0db5b3a93728ca2bf NOW.
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\python\microconda\lib\site-packages\pystan\model.py", line 313, in __init__
    build_extension.run()
  File "C:\python\microconda\lib\distutils\command\build_ext.py", line 339, in run
    self.build_extensions()
  File "C:\python\microconda\lib\distutils\command\build_ext.py", line 448, in build_extensions
    self._build_extensions_serial()
  File "C:\python\microconda\lib\distutils\command\build_ext.py", line 473, in _build_extensions_serial
    self.build_extension(ext)
  File "C:\python\microconda\lib\distutils\command\build_ext.py", line 533, in build_extension
    depends=ext.depends)
  File "C:\python\microconda\lib\distutils\_msvccompiler.py", line 345, in compile
    self.initialize()
  File "C:\python\microconda\lib\distutils\_msvccompiler.py", line 238, in initialize
    vc_env = _get_vc_env(plat_spec)
  File "C:\python\microconda\lib\distutils\_msvccompiler.py", line 134, in _get_vc_env
    raise DistutilsPlatformError("Unable to find vcvarsall.bat")
distutils.errors.DistutilsPlatformError: Unable to find vcvarsall.bat
>>> y = model.sampling(n_jobs=1).extract()['y']
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'model' is not defined
>>> y.mean()  # with luck the result will be near 0
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'y' is not defined

i have installed microsoft visual studio compiler and
mingw-w64

**Comment by bletham** [comment]
@rds99 check out #511 about getting Pystan working in windows, someone got it working there and their comments may be helpful.

**Comment by bletham** [comment]
I take it distutils.cfg is
```
[build]
mingw32
```
?
Besides that I'm not sure I can be of much help, I have not tried the mingw32 install myself.

**Comment by rds99** [comment]
yes i created distutils.cfg with that entry.
Thanks for your inputs, will keep trying

**Comment by bletham** [comment]
I think the question of supporting the data frequency has been resolved so I'll close the issue, but feel free to open a new one if there are additional install issues.
