### ISSUE TITLE
PyStan fit._call_sampler error when using multiplicative seasonalities with logistic growth 

### ISSUE THREAD

**Issue by shaidams64** [facebook/prophet#582]
Hi, I'm trying to fit a logistic growth model on two years of daily transactions data which looks like this: 
![b](https://user-images.githubusercontent.com/13664507/41941712-a952db28-7951-11e8-81c6-bc97add7fa07.png)

I have set the floor to 0 for logistic growth and set the seasonality mode to multiplicative in order to get positive forecasts but when I try fitting the model with this parameters I get the following error:
params = {'seasonality_prior_scale': 100, 'growth': 'logistic', 'yearly_seasonality': 'auto', 'interval_width': 0.95, 'n_changepoints': 3, 'holidays': None, 'weekly_seasonality': 'auto', 'changepoints': None, 'holidays_prior_scale': 10, 'mcmc_samples': 0, 'changepoint_prior_scale': 0.1, 'daily_seasonality': 'auto', 'uncertainty_samples': 1000}
error:
```
--> 156         m.fit (df)
    157         return m
    158 

~/.local/lib/python3.5/site-packages/fbprophet/forecaster.py in fit(self, df, **kwargs)
   1005                 params = model.optimizing(
   1006                     dat, init=stan_init, iter=1e4, algorithm='Newton',
-> 1007                     **kwargs
   1008                 )
   1009             for par in params:

~/.local/lib/python3.5/site-packages/pystan/model.py in optimizing(self, data, seed, init, sample_file, algorithm, verbose, as_vector, **kwargs)
    508         stan_args = pystan.misc._get_valid_stan_args(stan_args)
    509 
--> 510         ret, sample = fit._call_sampler(stan_args)
    511         pars = pystan.misc._par_vector2dict(sample['par'], m_pars, p_dims)
    512         if not as_vector:

stanfit4anon_model_861b75c6337e237650a61ae58c4385ef_7068190602506785692.pyx in stanfit4anon_model_861b75c6337e237650a61ae58c4385ef_7068190602506785692.StanFit4Model._call_sampler()

stanfit4anon_model_861b75c6337e237650a61ae58c4385ef_7068190602506785692.pyx in stanfit4anon_model_861b75c6337e237650a61ae58c4385ef_7068190602506785692._call_sampler()

RuntimeError: Exception: Exception: multiply: B[1] is -nan, but must not be nan!  (in 'unknown file name' at line 56)
  (in 'unknown file name' at line 119)
```
Can anyone guess what's causing this problem? I very much appreciate your help!

**Comment by shaidams64** [comment]
Here's the complete log:
```Initial log joint probability = -17.1971
    Iter      log prob        ||dx||      ||grad||       alpha      alpha0  # evals  Notes 
      20       1345.92   0.000767201       20.0255   5.992e-05       0.001       65  LS failed, Hessian reset 
      30       1346.04   0.000745544       12.4073   2.644e-05       0.001      158  LS failed, Hessian reset 
      40       1346.08   0.000131708       15.5719   9.948e-06       0.001      227  LS failed, Hessian reset 
      46       1346.09   2.47038e-06       7.43589   1.739e-07       0.001      273  LS failed, Hessian reset 
      47       1346.09   2.47038e-06       7.43589   2.064e-07       0.001      326  LS failed, Hessian reset 
Optimization terminated with error: 
  Line search failed to achieve a sufficient decrease, no more progress can be made

Initial log joint probability = -973.156
Iteration  1. Log joint probability =    644.477. Improved by 1617.63.
Iteration  2. Log joint probability =    677.356. Improved by 32.8788.
Iteration  3. Log joint probability =    1140.44. Improved by 463.082.
Iteration  4. Log joint probability =    1262.94. Improved by 122.499.
Iteration  5. Log joint probability =    1286.16. Improved by 23.2272.
Iteration  6. Log joint probability =        nan. Improved by nan.
Iteration  7. Log joint probability =    -1e+100. Improved by nan.
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/fbprophet/forecaster.py", line 1003, in fit
    dat, init=stan_init, iter=1e4, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pystan/model.py", line 510, in optimizing
    ret, sample = fit._call_sampler(stan_args)
  File "stanfit4anon_model_861b75c6337e237650a61ae58c4385ef_4841596752596378506.pyx", line 876, in stanfit4anon_model_861b75c6337e237650a61ae58c4385ef_4841596752596378506.StanFit4Model._call_sampler
  File "stanfit4anon_model_861b75c6337e237650a61ae58c4385ef_4841596752596378506.pyx", line 401, in stanfit4anon_model_861b75c6337e237650a61ae58c4385ef_4841596752596378506._call_sampler
RuntimeError: Something went wrong after call_sampler.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/taherehmasoumi/cdwbLocal/data/workbench/modules/CDWB_Python/submodules/AnomalyDetection/tsforecast/script.py", line 62, in <module>
    best_params, cv_err = forecasting.optimize_prophet_params(df, time_grain='day', param_dict=param_dict, error_metric='MASE')
  File "/Users/taherehmasoumi/cdwbLocal/data/workbench/modules/CDWB_Python/submodules/AnomalyDetection/tsforecast/forecasting.py", line 228, in optimize_prophet_params
    m_f = fit_model(df,**params )
  File "/Users/taherehmasoumi/cdwbLocal/data/workbench/modules/CDWB_Python/submodules/AnomalyDetection/tsforecast/forecasting.py", line 156, in fit_model
    m.fit (df)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/fbprophet/forecaster.py", line 1007, in fit
    **kwargs
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pystan/model.py", line 510, in optimizing
    ret, sample = fit._call_sampler(stan_args)
  File "stanfit4anon_model_861b75c6337e237650a61ae58c4385ef_4841596752596378506.pyx", line 876, in stanfit4anon_model_861b75c6337e237650a61ae58c4385ef_4841596752596378506.StanFit4Model._call_sampler
  File "stanfit4anon_model_861b75c6337e237650a61ae58c4385ef_4841596752596378506.pyx", line 401, in stanfit4anon_model_861b75c6337e237650a61ae58c4385ef_4841596752596378506._call_sampler
RuntimeError: Exception: Exception: multiply: B[1] is nan, but must not be nan!  (in 'unknown file name' at line 56)
  (in 'unknown file name' at line 119)


Process finished with exit code 1
```
Thanks a lot in advance!

**Comment by shaidams64** [comment]
@bletham thanks a lot for your helpful response, here's the dataset for your review:
[b_df.csv.zip](https://github.com/facebook/prophet/files/2139209/b_df.csv.zip)

I'm mostly interested to know why this error does not happen with additive seasonalities but is thrown with multiplicative seasonality. I'd like to know how to avoid this type of error in general since I'm automizing model hyper parameter optimizing and fitting  and wouldn't be able to handle such errors on the fly, 
thanks again for your help!

**Comment by bletham** [comment]
I think you should be able to try/except to catch the RuntimeError on the fly and just flag those hyperparameters as bad, but I'll check it out with the data and see what can be done.

**Comment by bletham** [comment]
I'm trying to figure out what was causing this to fail but am actually not able to produce the failure myself. I'm running
```
from fbprophet import Prophet
df = pd.read_csv('b_df.csv')
params = {'seasonality_prior_scale': 100, 'growth': 'logistic', 'yearly_seasonality': 'auto', 'interval_width': 0.95, 'n_changepoints': 3, 'holidays': None, 'weekly_seasonality': 'auto', 'changepoints': None, 'holidays_prior_scale': 10, 'mcmc_samples': 0, 'changepoint_prior_scale': 0.1, 'daily_seasonality': 'auto', 'uncertainty_samples': 1000, 'seasonality_mode': 'multiplicative'}

m = Prophet(**params)
m.fit(df)
```
and the optimization is terminating normally. Does that produce the failure for you, or are some of the params wrong?

**Comment by bletham** [comment]
I'm going to close this since I'm unable to replicate, but if anyone else runs into this issue please re-open.

**Comment by caseyjconger** [comment]
I've actually been getting this as well. I may not be able to share the data though.

**Comment by bletham** [comment]
@caseyjconger can you post the full traceback that you're seeing?

**Comment by Marmeladenbrot** [comment]
Got the same error while doing HPO with hyperpot. Can't give out the data.

System:

- Windows 10 x64 Professional 1903
- Python 3.8.5 x64
- miniconda
- python packages all up-2-date (can give a list of installed packages/versions if someone tells me how)

Code:

```
space = {
    "growth": hp.choice("growth", ["linear", "logistic"]),
    "changepoints": None,
    "n_changepoints": 25,
    "changepoint_range": hp.quniform("changepoint_range", 0.01, 1.0, 0.5),
    "yearly_seasonality": "auto",
    "weekly_seasonality": "auto",
    "daily_seasonality": "auto",
    "holidays": holidayDE,
    "seasonality_mode": hp.choice("seasonality_mode", ["additive", "multiplicative"]),
    "seasonality_prior_scale": hp.quniform(
        "seasonality_prior_scale", 0.001, 10.00, 0.01
    ),
    "holidays_prior_scale": hp.quniform("holidays_prior_scale", 0.001, 10.00, 1),
    "changepoint_prior_scale": hp.quniform(
        "changepoint_prior_scale", 0.001, 10.00, 0.005
    ),
    "mcmc_samples": 0,
    "interval_width": 0.8,
    "uncertainty_samples": 0,
}
# %%
trials_counter = 0


def loss_func(params):
    global trials_counter
    trials_counter = trials_counter + 1
    params = {
        "growth": params["growth"],
        "changepoints": params["changepoints"],
        "n_changepoints": params["n_changepoints"],
        "changepoint_range": params["changepoint_range"],
        "yearly_seasonality": params["yearly_seasonality"],
        "weekly_seasonality": params["weekly_seasonality"],
        "daily_seasonality": params["daily_seasonality"],
        "holidays": params["holidays"],
        "seasonality_mode": params["seasonality_mode"],
        "seasonality_prior_scale": params["seasonality_prior_scale"],
        "changepoint_prior_scale": params["changepoint_prior_scale"],
        "mcmc_samples": params["mcmc_samples"],
        "interval_width": params["interval_width"],
        "uncertainty_samples": params["uncertainty_samples"],
    }

    m = Prophet(**params)
    m.fit(df)
    df_cv = cross_validation(
        m,
        initial="366 days",
        period="30.5 days",
        horizon="61 days",
        parallel="threads",
    )
    df_p = performance_metrics(df_cv, metrics=["rmse"], rolling_window=1)

    if trials_counter % 100 == 0:
        dump(trials, "trials.joblib")

    return df_p["rmse"].values.tolist()[0]


# %%
ALGO = partial(tpe.suggest, n_EI_candidates=5000, gamma=0.5, n_startup_jobs=-1)
RANDOM_STATE = 42
trials = Trials()  # trials will contain logging information
# trials = load("trials.joblib")
MAX_EVALS = 500_000

best = fmin(
    fn=loss_func,  # function to optimize
    space=space,  # hyperparameter space
    algo=ALGO,  # optimization algorithm, hyperotp will select its parameters automatically
    max_evals=MAX_EVALS,  # maximum number of iterations
    trials=trials,  # logging
    # fixing random state for the reproducibility
    rstate=np.random.RandomState(RANDOM_STATE),
)
```


Stacktrace:

```
RuntimeError                              Traceback (most recent call last)
~\Miniconda3\envs\basis\lib\site-packages\fbprophet\models.py in fit(self, stan_init, stan_data, **kwargs)
    244         try:
--> 245             self.stan_fit = self.model.optimizing(**args)
    246         except RuntimeError:

~\Miniconda3\envs\basis\lib\site-packages\pystan\model.py in optimizing(self, data, seed, init, sample_file, algorithm, verbose, as_vector, **kwargs)
    580 
--> 581         ret, sample = fit._call_sampler(stan_args)
    582         pars = pystan.misc._par_vector2dict(sample['par'], m_pars, p_dims)

stanfit4anon_model_f5236004a3fd5b8429270d00efcc0cf9_9045703871880297330.pyx in stanfit4anon_model_f5236004a3fd5b8429270d00efcc0cf9_9045703871880297330.StanFit4Model._call_sampler()

stanfit4anon_model_f5236004a3fd5b8429270d00efcc0cf9_9045703871880297330.pyx in stanfit4anon_model_f5236004a3fd5b8429270d00efcc0cf9_9045703871880297330._call_sampler()

RuntimeError: Initialization failed.

During handling of the above exception, another exception occurred:

RuntimeError                              Traceback (most recent call last)
c:\Users\REDACTED\Documents\REDACTED\Projekte\2020\REDACTED\src\Absatz\prophet_hpo.py in 
      119 MAX_EVALS = 500_000
      120 
----> 121 best = fmin(
      122     fn=loss_func,  # function to optimize
      123     space=space,  # hyperparameter space

~\Miniconda3\envs\basis\lib\site-packages\hyperopt\fmin.py in fmin(fn, space, algo, max_evals, timeout, loss_threshold, trials, rstate, allow_trials_fmin, pass_expr_memo_ctrl, catch_eval_exceptions, verbose, return_argmin, points_to_evaluate, max_queue_len, show_progressbar)
    467 
    468     if allow_trials_fmin and hasattr(trials, "fmin"):
--> 469         return trials.fmin(
    470             fn,
    471             space,

~\Miniconda3\envs\basis\lib\site-packages\hyperopt\base.py in fmin(self, fn, space, algo, max_evals, timeout, loss_threshold, max_queue_len, rstate, verbose, pass_expr_memo_ctrl, catch_eval_exceptions, return_argmin, show_progressbar)
    669         from .fmin import fmin
    670 
--> 671         return fmin(
    672             fn,
    673             space,

~\Miniconda3\envs\basis\lib\site-packages\hyperopt\fmin.py in fmin(fn, space, algo, max_evals, timeout, loss_threshold, trials, rstate, allow_trials_fmin, pass_expr_memo_ctrl, catch_eval_exceptions, verbose, return_argmin, points_to_evaluate, max_queue_len, show_progressbar)
    507 
    508     # next line is where the fmin is actually executed
--> 509     rval.exhaust()
    510 
    511     if return_argmin:

~\Miniconda3\envs\basis\lib\site-packages\hyperopt\fmin.py in exhaust(self)
    328     def exhaust(self):
    329         n_done = len(self.trials)
--> 330         self.run(self.max_evals - n_done, block_until_done=self.asynchronous)
    331         self.trials.refresh()
    332         return self

~\Miniconda3\envs\basis\lib\site-packages\hyperopt\fmin.py in run(self, N, block_until_done)
    284                 else:
    285                     # -- loop over trials and do the jobs directly
--> 286                     self.serial_evaluate()
    287 
    288                 self.trials.refresh()

~\Miniconda3\envs\basis\lib\site-packages\hyperopt\fmin.py in serial_evaluate(self, N)
    163                 ctrl = base.Ctrl(self.trials, current_trial=trial)
    164                 try:
--> 165                     result = self.domain.evaluate(spec, ctrl)
    166                 except Exception as e:
    167                     logger.error("job exception: %s" % str(e))

~\Miniconda3\envs\basis\lib\site-packages\hyperopt\base.py in evaluate(self, config, ctrl, attach_attachments)
    892                 print_node_on_error=self.rec_eval_print_node_on_error,
    893             )
--> 894             rval = self.fn(pyll_rval)
    895 
    896         if isinstance(rval, (float, int, np.number)):

c:\Users\REDACTED\Documents\REDACTED\Projekte\2020\REDACTED\src\Absatz\prophet_hpo.py in loss_func(params)
     96 
     97     m = Prophet(**params)
---> 98     m.fit(df)
     99     df_cv = cross_validation(
     100         m,

~\Miniconda3\envs\basis\lib\site-packages\fbprophet\forecaster.py in fit(self, df, **kwargs)
   1164             self.params = self.stan_backend.sampling(stan_init, dat, self.mcmc_samples, **kwargs)
   1165         else:
-> 1166             self.params = self.stan_backend.fit(stan_init, dat, **kwargs)
   1167 
   1168         # If no changepoints were requested, replace delta with 0s

~\Miniconda3\envs\basis\lib\site-packages\fbprophet\models.py in fit(self, stan_init, stan_data, **kwargs)
    250             )
    251             args['algorithm'] = 'Newton'
--> 252             self.stan_fit = self.model.optimizing(**args)
    253 
    254         params = dict()

~\Miniconda3\envs\basis\lib\site-packages\pystan\model.py in optimizing(self, data, seed, init, sample_file, algorithm, verbose, as_vector, **kwargs)
    579         stan_args = pystan.misc._get_valid_stan_args(stan_args)
    580 
--> 581         ret, sample = fit._call_sampler(stan_args)
    582         pars = pystan.misc._par_vector2dict(sample['par'], m_pars, p_dims)
    583         if not as_vector:

stanfit4anon_model_f5236004a3fd5b8429270d00efcc0cf9_9045703871880297330.pyx in stanfit4anon_model_f5236004a3fd5b8429270d00efcc0cf9_9045703871880297330.StanFit4Model._call_sampler()

stanfit4anon_model_f5236004a3fd5b8429270d00efcc0cf9_9045703871880297330.pyx in stanfit4anon_model_f5236004a3fd5b8429270d00efcc0cf9_9045703871880297330._call_sampler()

RuntimeError: Initialization failed

```

**Comment by bletham** [comment]
The logistic growth trend involves taking an `exp()` that can cause numerical issues during optimization if the model is badly misspecified, which is probably what's happening here because some of the parameter values are quite extreme. I'd recommend not using HPO to select the trend; if you expect your time series to saturate at a known capacity then use logistic trend, otherwise use the default.

The range of [0.01, 1.0] for `changepoint_range` is wider than I'd recommend. The purpose of this parameter is just to prevent overfitting to trend changes at the very end of the history. A value like 0.01 means there will be no trend changes, and the better way to get that behavior will be through tight regularization on the changepoint_prior_scale. See https://facebook.github.io/prophet/docs/diagnostics.html#hyperparameter-tuning for a list of all of the hyperparameters with some recommendations on what to tune and on what ranges.
