### ISSUE TITLE
fail to plot cross validation metric with latest pandas version

### ISSUE THREAD

**Issue by little-yoki** [facebook/prophet#591]
I installed fbprophet with version 3.0post2 and pandas with version 2.3.1, and I failed to call method Prophet.plot_cross_validation_metric().
To be specific, when I called `plot_cross_validation_metric(df_cv, metric='mape')`, I got the following error:

Traceback (most recent call last):

>   File "D:/NETEASE/test/predict.py", line 47, in <module>
    fig3 = plot_cross_validation_metric(df_cv, metric='mape')
  File "D:\NETEASE\test\venv\lib\site-packages\fbprophet\plot.py", line 464, in plot_cross_validation_metric
    x_plt = df_none['horizon'].astype('timedelta64[ns]').astype(int) / float(dt_conversions[i])
  File "D:\NETEASE\test\venv\lib\site-packages\pandas\util\_decorators.py", line 177, in wrapper
    return func(*args, **kwargs)
  File "D:\NETEASE\test\venv\lib\site-packages\pandas\core\generic.py", line 4997, in astype
    **kwargs)
  File "D:\NETEASE\test\venv\lib\site-packages\pandas\core\internals.py", line 3714, in astype
    return self.apply('astype', dtype=dtype, **kwargs)
  File "D:\NETEASE\test\venv\lib\site-packages\pandas\core\internals.py", line 3581, in apply
    applied = getattr(b, f)(**kwargs)
  File "D:\NETEASE\test\venv\lib\site-packages\pandas\core\internals.py", line 575, in astype
    **kwargs)
  File "D:\NETEASE\test\venv\lib\site-packages\pandas\core\internals.py", line 664, in _astype
    values = astype_nansafe(values.ravel(), dtype, copy=True)
  File "D:\NETEASE\test\venv\lib\site-packages\pandas\core\dtypes\cast.py", line 696, in astype_nansafe
    to_dtype=dtype))
TypeError: cannot astype a timedelta from [timedelta64[ns]] to [int32]

I checked the source code of Prophet.plot_cross_validation_metric() and I found the issue:
`x_plt = df_none['horizon'].astype('timedelta64[ns]').astype(int) / float(dt_conversions[i])`,
which is line 464 in plot.py.
Since timedelta64[ns] is 64bit, and astype(int) will convert variable into type int32, so this conversion cannot be finished. I think It should probably be `astype('int64')` instead of `astype(int)`.

**Comment by bletham** [comment]
This looks like the issue fixed by https://github.com/facebook/prophet/pull/577, which implements the solution you proposed. It hasn't been pushed to PyPI yet, so in the meantime you can get the fix by installing the current version from github.
