### ISSUE TITLE
"python setup.py egg_info" failed with error code 1 in c:\users\sudat\appdata\local\temp\pip-install-zwm3mk\astropysics\

### ISSUE THREAD

**Issue by SudatKhan** [facebook/prophet#653]
When I try to do "pip install astropysics" on python 2.7.14 I keep getting this error

pip install astropysics
Collecting astropysics
  Using cached https://files.pythonhosted.org/packages/ae/a3/9546c31d377a4905a51bb038f4886d52f45219b7216abb0bf1aca2bbdb5d/Astropysics-1.0.tar.gz
    Complete output from command python setup.py egg_info:
    Downloading http://pypi.python.org/packages/source/d/distribute/distribute-0.6.10.tar.gz
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "c:\users\sudat\appdata\local\temp\pip-install-zwm3mk\astropysics\setup.py", line 7, in <module>
        use_setuptools()
      File "distribute_setup.py", line 145, in use_setuptools
        return _do_download(version, download_base, to_dir, download_delay)
      File "distribute_setup.py", line 124, in _do_download
        to_dir, download_delay)
      File "distribute_setup.py", line 193, in download_setuptools
        src = urlopen(url)
      File "c:\users\sudat\python\lib\urllib2.py", line 154, in urlopen
        return opener.open(url, data, timeout)
      File "c:\users\sudat\python\lib\urllib2.py", line 435, in open
        response = meth(req, response)
      File "c:\users\sudat\python\lib\urllib2.py", line 548, in http_response
        'http', request, response, code, msg, hdrs)
      File "c:\users\sudat\python\lib\urllib2.py", line 473, in error
        return self._call_chain(*args)
      File "c:\users\sudat\python\lib\urllib2.py", line 407, in _call_chain
        result = func(*args)
      File "c:\users\sudat\python\lib\urllib2.py", line 556, in http_error_default
        raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
    urllib2.HTTPError: HTTP Error 403: SSL is required

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in c:\users\sudat\appdata\local\temp\pip-install-zwm3mk\astropysics\

**Comment by bletham** [comment]
I'm going to close this since it is unrelated to this package.
