### ISSUE TITLE
MemoryError: "can't allocate region set a breakpoint in malloc_error_break to debug"

### ISSUE THREAD

**Issue by heoa** [facebook/prophet#675]
I am running the demo in Python3 on macOS Sierra 10.12.6

```
import pandas as pd
from fbprophet import Prophet
df = pd.read_csv('Data/mydata.csv', sep="\t")
m = Prophet(yearly_seasonality=True, weekly_seasonality=True, daily_seasonality=True)
m.fit(df)
future = m.make_future_dataframe(periods=365)
forecast = m.predict(future)
forecast[['ds', 'yhat', 'yhat_lower', 'yhat_upper']].tail()
fig1 = m.plot(forecast)
fig1.savefig('forecast.png')
fig2 = m.plot_components(forecast)
fig2.savefig('plot_components.png')
```

and the error

```
$ python prophet_test_fb.py 
/Users/h/anaconda3/lib/python3.6/site-packages/pystan/misc.py:399: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  elif np.issubdtype(np.asarray(v).dtype, float):
Initial log joint probability = -66.8453
    Iter      log prob        ||dx||      ||grad||       alpha      alpha0  # evals  Notes 
      99       3054.76    0.00355962       75.0649           1           1      135   
    Iter      log prob        ||dx||      ||grad||       alpha      alpha0  # evals  Notes 
     124       3054.94   0.000103368       71.6774   7.477e-07       0.001      205  LS failed, Hessian reset 
     148       3054.96   2.12413e-06       52.3169   4.048e-08       0.001      279  LS failed, Hessian reset 
     158       3054.96   1.04251e-06       59.9258   2.094e-08       0.001      329  LS failed, Hessian reset 
     165       3054.96   1.33425e-07       55.4782           1           1      342   
Optimization terminated normally: 
  Convergence detected: relative gradient magnitude is below tolerance
python(76679,0x7fffcd1553c0) malloc: *** mach_vm_map(size=205319148257280) failed (error code=3)
*** error: can't allocate region
*** set a breakpoint in malloc_error_break to debug
Traceback (most recent call last):
  File "prophet_test_fb.py", line 19, in <module>
    forecast = m.predict(future)
  File "/Users/hhh/anaconda3/lib/python3.6/site-packages/fbprophet/forecaster.py", line 1042, in predict
    intervals = self.predict_uncertainty(df)
  File "/Users/hhh/anaconda3/lib/python3.6/site-packages/fbprophet/forecaster.py", line 1244, in predict_uncertainty
    sim_values = self.sample_posterior_predictive(df)
  File "/Users/hhh/anaconda3/lib/python3.6/site-packages/fbprophet/forecaster.py", line 1208, in sample_posterior_predictive
    s_m=component_cols['multiplicative_terms'],
  File "/Users/hhh/anaconda3/lib/python3.6/site-packages/fbprophet/forecaster.py", line 1273, in sample_model
    trend = self.sample_predictive_trend(df, iteration)
  File "/Users/hhh/anaconda3/lib/python3.6/site-packages/fbprophet/forecaster.py", line 1313, in sample_predictive_trend
    changepoint_ts_new = 1 + np.random.rand(n_changes) * (T - 1)
  File "mtrand.pyx", line 1363, in mtrand.RandomState.rand
  File "mtrand.pyx", line 861, in mtrand.RandomState.random_sample
  File "mtrand.pyx", line 167, in mtrand.cont0_array
MemoryError
```

**Can someone help me to resolve this?**

**Comment by bletham** [comment]
It seems to be running out of RAM when doing the simulations for the future trend uncertainty. There are a few places this might be happening, could you answer a couple questions:

* What version of fbprophet are you using?
```
import fbprophet
fbprophet.__version__
```
There was a change in 0.3 that eliminates one particular source of memory issues in future trend uncertainty.

* How many rows are in your future dataframe?

**Comment by bletham** [comment]
I'm hoping this was resolved, but if anyone is still having this issue please re-open and hopefully we can determine why the RAM usage was so high.

**Comment by heoa** [comment]
The fb_prophet version is 0.3.

```
$ python test.py 
0.3
$ pip install fbprophet
Requirement already satisfied: fbprophet in /Users/hhh/anaconda3/lib/python3.6/site-packages (0.3.post2)
```

and still getting the error

```
/Users/myUser/anaconda3/lib/python3.6/site-packages/pystan/misc.py:399: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  elif np.issubdtype(np.asarray(v).dtype, float):
Initial log joint probability = -66.8453
    Iter      log prob        ||dx||      ||grad||       alpha      alpha0  # evals  Notes 
      99       2054.76    0.00355962       75.0649           1           1      135   
    Iter      log prob        ||dx||      ||grad||       alpha      alpha0  # evals  Notes 
     124       2054.94   0.000103368       71.6774   7.477e-07       0.001      205  LS failed, Hessian reset 
     148       2054.96   2.12413e-06       52.3169   4.048e-08       0.001      279  LS failed, Hessian reset 
     158       2054.96   1.04251e-06       59.9258   2.094e-08       0.001      329  LS failed, Hessian reset 
     165       2054.96   1.33425e-07       55.4782           1           1      342   
Optimization terminated normally: 
  Convergence detected: relative gradient magnitude is below tolerance
python(56420,0x7fffcd1553c0) malloc: *** mach_vm_map(size=205319166889984) failed (error code=3)
*** error: can't allocate region
*** set a breakpoint in malloc_error_break to debug
Traceback (most recent call last):
  File "prophet_test_fb.py", line 19, in <module>
    forecast = m.predict(future)
  File "/Users/myUser/anaconda3/lib/python3.6/site-packages/fbprophet/forecaster.py", line 1042, in predict
    intervals = self.predict_uncertainty(df)
  File "/Users/myUser/anaconda3/lib/python3.6/site-packages/fbprophet/forecaster.py", line 1244, in predict_uncertainty
    sim_values = self.sample_posterior_predictive(df)
  File "/Users/myUser/anaconda3/lib/python3.6/site-packages/fbprophet/forecaster.py", line 1208, in sample_posterior_predictive
    s_m=component_cols['multiplicative_terms'],
  File "/Users/myUser/anaconda3/lib/python3.6/site-packages/fbprophet/forecaster.py", line 1273, in sample_model
    trend = self.sample_predictive_trend(df, iteration)
  File "/Users/myUser/anaconda3/lib/python3.6/site-packages/fbprophet/forecaster.py", line 1313, in sample_predictive_trend
    changepoint_ts_new = 1 + np.random.rand(n_changes) * (T - 1)
  File "mtrand.pyx", line 1363, in mtrand.RandomState.rand
  File "mtrand.pyx", line 861, in mtrand.RandomState.random_sample
  File "mtrand.pyx", line 167, in mtrand.cont0_array
MemoryError
```

The  file has 1300 lines.

**Comment by heoa** [comment]
@bletham can you reopen this? This is still unsolved.

**Comment by bletham** [comment]
Is the 1300 rows the length of the history dataframe being given to `fit`, or the length of the `future` dataframe being given to `predict`? The latter length is the one that would matter here.

What arguments are you using to `Prophet()`? Any changes to `changepoints` or `uncertainty_samples`?

Is there any chance you could attach the data so I could look into what is happening in this dataset in more detail?

I'm surprised to see memory issues with 1300 rows. The examples in the documentation have more rows than that - are you able to fit this dataset or does it run into memory issues also?
https://github.com/facebook/prophet/blob/master/examples/example_wp_log_peyton_manning.csv

**Comment by kmacalpine** [comment]
@bletham I am having the same issue. 715 rows. I have run similar datasets without issues.

**Comment by bletham** [comment]
Is there any chance you can upload the dataset so I can try to reproduce? That seems like far too small a dataset to cause memory issues.

**Comment by kmacalpine** [comment]
@bletham Here you go. 
[dataset130.xlsx](https://github.com/facebook/prophet/files/2823006/dataset130.xlsx)

**Comment by bletham** [comment]
OK, I see what the issue is. Internally, fbprophet uses pandas to convert the ds column to a timestamp. When I export the spreadsheet to csv and do
```
>>> import pandas as pd
>>> df = pd.read_csv('dataset130.csv')
>>> df['ds'] = pd.to_datetime(df['ds'])
>>> df.head()
                             ds         y
0 1970-01-01 00:00:00.020170101  9.051813
1 1970-01-01 00:00:00.020170102  9.200290
2 1970-01-01 00:00:00.020170103  9.153876
3 1970-01-01 00:00:00.020170104  9.019180
4 1970-01-01 00:00:00.020170105  9.170455
```
you can see that the `ds` column is being treated by pandas as nanoseconds. This is because it is missing the hyphens (like `2017-01-01`) that would cause pandas to correctly interpret it as YYYY-MM-DD.

This causes a memory issue because basically we are fitting the model to a time series that lasts a matter of nanoseconds, and then making predictions for days out, which induces a very large number of potential future changepoints when estimating future trend uncertainty.

The R versions is much stricter and requires specifically YYYY-MM-DD. In Py we try to be less strict and let pandas infer the date formatting, but sometimes that can go poorly like here. We make this more strict in the future, perhaps have it throw an error if the column can be cast to int (which I think is the situation in which pd treats it as nanoseconds).

**Comment by kmacalpine** [comment]
Ah okay. Yes, formatting the dates worked. Thank you so much for your help!

**Comment by bletham** [comment]
Pushed to PyPI
