### ISSUE TITLE
holidays 0.9.9 breaks fbprophet

### ISSUE THREAD

**Issue by louisguitton** [facebook/prophet#792]
`holidays=0.9.8` works and when upgrading to `holidays=0.9.9`, it fails with the following stacktrace:
```python
  File "/my_project/src/models/train_model.py", line 3, in <module>
    import fbprophet
  File "/my_project/venv/lib/python3.7/site-packages/fbprophet/__init__.py", line 8, in <module>
    from fbprophet.forecaster import Prophet
  File "/my_project/venv/lib/python3.7/site-packages/fbprophet/forecaster.py", line 23, in <module>
    from fbprophet.make_holidays import get_holiday_names, make_holidays_df
  File "/my_project/venv/lib/python3.7/site-packages/fbprophet/make_holidays.py", line 17, in <module>
    import fbprophet.hdays as hdays_part2
  File "/my_project/venv/lib/python3.7/site-packages/fbprophet/hdays.py", line 13, in <module>
    from holidays import HolidayBase, MONDAY, WEEKEND, rd, easter
ImportError: cannot import name 'MONDAY' from 'holidays' (/my_project/venv/lib/python3.7/site-packages/holidays.py)
```

**Comment by louisguitton** [comment]
the new `holidays` version was released 3 hours ago https://pypi.org/project/holidays/#history

**Comment by louisguitton** [comment]
https://github.com/facebook/prophet/pull/791

**Comment by dkrantz** [comment]
i am getting the same error:

Traceback (most recent call last):
  File "Daily_Dashboard.py", line 291, in <module>
    temp_series = get_forecast(i,kind)
  File "Daily_Dashboard.py", line 192, in get_forecast
    from fbprophet import Prophet
  File "/usr/local/lib/python2.7/site-packages/fbprophet/__init__.py", line 8, in <module>
    from fbprophet.forecaster import Prophet
  File "/usr/local/lib/python2.7/site-packages/fbprophet/forecaster.py", line 23, in <module>
    from fbprophet.make_holidays import get_holiday_names, make_holidays_df
  File "/usr/local/lib/python2.7/site-packages/fbprophet/make_holidays.py", line 17, in <module>
    import fbprophet.hdays as hdays_part2
  File "/usr/local/lib/python2.7/site-packages/fbprophet/hdays.py", line 13, in <module>
    from holidays import HolidayBase, MONDAY, WEEKEND, rd, easter
ImportError: cannot import name MONDAY

**Comment by louisguitton** [comment]
To circumvent it, either you wait for https://github.com/facebook/prophet/pull/791 to be merged,
Or you force the holidays package to use a version that doesn't brake prophet: 
```
pip install holidays==0.9.8 fbprophet
```

**Comment by Gordonei** [comment]
I suppose alternatively, you could download [my PR branch](https://github.com/Gordonei/prophet/tree/wip/use-right-holiday-const) and rebuild and install prophet from source. But that might be more trouble than its worth.
