### ISSUE TITLE
Cap cannot be 0 when using  logistic growth

### ISSUE THREAD

**Issue by lppier** [facebook/prophet#807]
Hi, 

I am using prophet like this : 
```
        m = Prophet(**opts, changepoint_range=0.8, changepoint_prior_scale=0.12, growth='logistic',
                    seasonality_mode='additive')
```
and my dataset is as attached. 
[df_daily.zip](https://github.com/facebook/prophet/files/2754136/df_daily.zip)

I'm getting the following errors. 
```
Rejecting initial value:
  Error evaluating the log probability at the initial value.
Exception: normal_lpdf: Random variable is -nan(ind), but must not be nan!  (in 'unknown file name' at line 149)
Rejecting initial value:
  Error evaluating the log probability at the initial value.
Exception: normal_lpdf: Random variable is -nan(ind), but must not be nan!  (in 'unknown file name' at line 149)
Rejecting initial value:
  Error evaluating the log probability at the initial value.
Exception: normal_lpdf: Random variable is -nan(ind), but must not be nan!  (in 'unknown file name' at line 149)
Rejecting initial value:
  Error evaluating the log probability at the initial value.
Exception: normal_lpdf: Random variable is -nan(ind), but must not be nan!  (in 'unknown file name' at line 149)
 
(repeats many times) 

Traceback (most recent call last):
  File "C:\Users\pier_lim\AppData\Local\Continuum\anaconda3\envs\ana\lib\site-packages\fbprophet\forecaster.py", line 1003, in fit
    dat, init=stan_init, iter=1e4, **kwargs)
  File "C:\Users\pier_lim\AppData\Local\Continuum\anaconda3\envs\ana\lib\site-packages\pystan\model.py", line 510, in optimizing
    ret, sample = fit._call_sampler(stan_args)
  File "stanfit4anon_model_db8febf10f23d7fa27a62fbcfd7f17b2_8347890744695566330.pyx", line 876, in stanfit4anon_model_db8febf10f23d7fa27a62fbcfd7f17b2_8347890744695566330.StanFit4Model._call_sampler
  File "stanfit4anon_model_db8febf10f23d7fa27a62fbcfd7f17b2_8347890744695566330.pyx", line 401, in stanfit4anon_model_db8febf10f23d7fa27a62fbcfd7f17b2_8347890744695566330._call_sampler
RuntimeError: Initialization failed.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<input>", line 24, in <module>
  File "C:\Users\pier_lim\AppData\Local\Continuum\anaconda3\envs\ana\lib\site-packages\fbprophet\forecaster.py", line 1007, in fit
    **kwargs
  File "C:\Users\pier_lim\AppData\Local\Continuum\anaconda3\envs\ana\lib\site-packages\pystan\model.py", line 510, in optimizing
    ret, sample = fit._call_sampler(stan_args)
  File "stanfit4anon_model_db8febf10f23d7fa27a62fbcfd7f17b2_8347890744695566330.pyx", line 876, in stanfit4anon_model_db8febf10f23d7fa27a62fbcfd7f17b2_8347890744695566330.StanFit4Model._call_sampler
  File "stanfit4anon_model_db8febf10f23d7fa27a62fbcfd7f17b2_8347890744695566330.pyx", line 401, in stanfit4anon_model_db8febf10f23d7fa27a62fbcfd7f17b2_8347890744695566330._call_sampler
RuntimeError: Initialization failed.
```
I have experimented and I I've found that if I set cap to 1 instead of 0 as in some of the rows in the dataset, the problem goes away and I can carry out my steps as per normal. Likely a divide by 0 bug?

**Comment by bletham** [comment]
Thanks for testing this corner case :-)

The issue is that the logistic growth curve also has an implicit floor of 0, so in this case we are setting cap = floor (see the sentence beneath the first figure on https://facebook.github.io/prophet/docs/saturating_forecasts.html#forecasting-growth).

This isn't a bug per se since it should error in this situation, but the error should be more descriptive.

In this particular case you can fix it by just setting `df['floor']` to something less than `df['cap']` (and less than the lowest portion of your data).

**Comment by bletham** [comment]
Yes, you can set the floor to a negative number. It will only significantly effect the predictions of points whose value is near the floor value, since that is where you will see the saturation (see e.g. https://en.wikipedia.org/wiki/Logistic_function which has floor = 0).

**Comment by bletham** [comment]
Pushed to PyPI and CRAN
