### ISSUE TITLE
Prophet Installation issue

### ISSUE THREAD

**Issue by rajanat** [facebook/prophet#880]
Hi 

I am getting the below error when iimport prophet.

import prophet
Traceback (most recent call last):

  File "<ipython-input-23-c1760209c559>", line 1, in <module>
    import prophet

  File "F:\Anaconda3\lib\site-packages\prophet\__init__.py", line 4, in <module>
    from prophet.app import Prophet  # NOQA

  File "F:\Anaconda3\lib\site-packages\prophet\app.py", line 3, in <module>
    from prophet.analyze import Analysis

  File "F:\Anaconda3\lib\site-packages\prophet\analyze.py", line 2, in <module>
    from prophet.utils.formatters import dict_to_table

  File "F:\Anaconda3\lib\site-packages\prophet\utils\__init__.py", line 1, in <module>
    from prophet.utils.tradingcalendar import trading_days  # NOQA

  File "F:\Anaconda3\lib\site-packages\prophet\utils\tradingcalendar.py", line 242, in <module>
    non_trading_days = get_non_trading_days(start, end)

  File "F:\Anaconda3\lib\site-packages\prophet\utils\tradingcalendar.py", line 240, in get_non_trading_days
    return pd.DatetimeIndex(non_trading_days)

  File "F:\Anaconda3\lib\site-packages\pandas\core\indexes\datetimes.py", line 399, in __new__
    yearfirst=yearfirst)

  File "F:\Anaconda3\lib\site-packages\pandas\core\tools\datetimes.py", line 463, in to_datetime
    cache_array = _maybe_cache(arg, format, cache, tz, _convert_listlike)

  File "F:\Anaconda3\lib\site-packages\pandas\core\tools\datetimes.py", line 61, in _maybe_cache
    cache_array = Series()

  File "F:\Anaconda3\lib\site-packages\pandas\core\series.py", line 216, in __init__
    data, index = self._init_dict(data, index, dtype)

  File "F:\Anaconda3\lib\site-packages\pandas\core\series.py", line 317, in _init_dict
    s = Series(values, index=keys, dtype=dtype)

  File "F:\Anaconda3\lib\site-packages\pandas\core\series.py", line 183, in __init__
    index = _ensure_index(index)

  File "F:\Anaconda3\lib\site-packages\pandas\core\indexes\base.py", line 4974, in _ensure_index
    return Index(index_like)

  File "F:\Anaconda3\lib\site-packages\pandas\core\indexes\base.py", line 280, in __new__
    if is_interval_dtype(data) or is_interval_dtype(dtype):

  File "F:\Anaconda3\lib\site-packages\pandas\core\dtypes\common.py", line 510, in is_interval_dtype
    return IntervalDtype.is_dtype(arr_or_dtype)

  File "F:\Anaconda3\lib\site-packages\pandas\core\dtypes\dtypes.py", line 725, in is_dtype
    return super(IntervalDtype, cls).is_dtype(dtype)

TypeError: super(type, obj): obj must be an instance or subtype of type

request to kindly help on the above issue

regards
Raj

**Comment by bletham** [comment]
In Python, the name of the time series forecasting package is `fbprophet`. It looks like here you installed `prophet`, which is for portfolio management.

If you're trying to install the forecasting software, then `conda install fbprophet` will do it. If you're trying to install the portfolio management software, then you'll have to ask over at their repo.
