### ISSUE TITLE
Not able to install junos-eznc on cent os 7

### ISSUE THREAD

**Issue by vkumar007** [facebook/prophet#902]
Python 2.6 version 
Below is the output i get when i tried to install junos-eznc 
#pip install --upgrade junos-eznc
You are using pip version 7.1.0, however version 19.0.3 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
Collecting junos-eznc
  Using cached https://files.pythonhosted.org/packages/00/b5/3d6d2d572789421b71d2bd7e3bae843db504cad59415bf817c7b9075aad6/junos_eznc-2.2.0-py2.py3-none-any.whl
Collecting pyserial (from junos-eznc)
  Using cached https://files.pythonhosted.org/packages/0d/e4/2a744dd9e3be04a0c0907414e2a01a7c88bb3915cbe3c8cc06e209f59c30/pyserial-3.4-py2.py3-none-any.whl
Collecting paramiko>=1.15.2 (from junos-eznc)
  Using cached https://files.pythonhosted.org/packages/cf/ae/94e70d49044ccc234bfdba20114fa947d7ba6eb68a2e452d89b920e62227/paramiko-2.4.2-py2.py3-none-any.whl
Collecting PyYAML>=3.10 (from junos-eznc)
  Using cached https://files.pythonhosted.org/packages/9f/2c/9417b5c774792634834e730932745bc09a7d36754ca00acf1ccd1ac2594d/PyYAML-5.1.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 20, in <module>
      File "/tmp/pip-build-WIOnss/PyYAML/setup.py", line 91, in <module>
        from wheel.bdist_wheel import bdist_wheel
      File "/usr/lib/python2.6/site-packages/wheel/bdist_wheel.py", line 298
        option for option in metadata.get('license_files', ('', ''))[1].split()
                 ^
    SyntaxError: invalid syntax

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-WIOnss/PyYAML 

+++++++++++++++++++++++++++++++++++++++++++++++++++++++
**I have tried with upgrading PIP from 7.1.0 to 19.0.3 as well but after that i will get new error.** 

#pip install --upgrade junos-eznc
Traceback (most recent call last):
  File "/usr/bin/pip", line 7, in <module>
    from pip._internal import main
  File "/usr/lib/python2.6/site-packages/pip/_internal/__init__.py", line 19, in <module>
    from pip._vendor.urllib3.exceptions import DependencyWarning
  File "/usr/lib/python2.6/site-packages/pip/_vendor/urllib3/__init__.py", line 8, in <module>
    from .connectionpool import (
  File "/usr/lib/python2.6/site-packages/pip/_vendor/urllib3/connectionpool.py", line 92
    _blocking_errnos = {errno.EAGAIN, errno.EWOULDBLOCK}
                                    ^
SyntaxError: invalid syntax

Any help much appreciated !!

**Comment by vkumar007** [comment]
issue is with old cent os running 6.x version and with python 2.6 as xaml requires version of python greater than 2.6
