### ISSUE TITLE
pip install discord.py not working

### ISSUE THREAD

**Issue by DJLinx** [facebook/prophet#938]
pip install discord.py: Command "python setup.py egg_info" failed with error code 1 in C:\Users\user~1\AppData\Local\Temp\pip-install-l68ekse8\idna-ssl\

pip install --upgrade setuptools: C:\WINDOWS\system32>pip install --upgrade setuptools
Collecting setuptools
  Using cached https://files.pythonhosted.org/packages/c8/b0/cc6b7ba28d5fb790cf0d5946df849233e32b8872b6baca10c9e002ff5b41/setuptools-41.0.0-py2.py3-none-any.whl
Installing collected packages: setuptools
  Found existing installation: setuptools 39.0.1
Exception:
Traceback (most recent call last):
  File "c:\users\user\appdata\local\programs\python\python36-32\lib\site-packages\pip\_internal\cli\base_command.py", line 179, in main
    status = self.run(options, args)
  File "c:\users\user\appdata\local\programs\python\python36-32\lib\site-packages\pip\_internal\commands\install.py", line 393, in run
    use_user_site=options.use_user_site,
  File "c:\users\user\appdata\local\programs\python\python36-32\lib\site-packages\pip\_internal\req\__init__.py", line 50, in install_given_reqs
    auto_confirm=True
  File "c:\users\user\appdata\local\programs\python\python36-32\lib\site-packages\pip\_internal\req\req_install.py", line 816, in uninstall
    uninstalled_pathset = UninstallPathSet.from_dist(dist)
  File "c:\users\user\appdata\local\programs\python\python36-32\lib\site-packages\pip\_internal\req\req_uninstall.py", line 496, in from_dist
    for path in uninstallation_paths(dist):
  File "c:\users\user\appdata\local\programs\python\python36-32\lib\site-packages\pip\_internal\req\req_uninstall.py", line 50, in unique
    for item in fn(*args, **kw):
  File "c:\users\user\appdata\local\programs\python\python36-32\lib\site-packages\pip\_internal\req\req_uninstall.py", line 68, in uninstallation_paths
    for row in r:
_csv.Error: line contains NULL byte

Please dont close this.

**Comment by bletham** [comment]
This issue tracker is for a different package, it looks like you'll want to ask over here: https://github.com/Rapptz/discord.py
