### ISSUE TITLE
i'm unable to resolve the following error while installing pysl

### ISSUE THREAD

**Issue by arjavjain59998** [facebook/prophet#947]
Collecting pyls
  Using cached https://files.pythonhosted.org/packages/de/b7/5a056c2cac8fd19c905ae7451c2a60b9195531959c3770a49d6be4d905e3/pyls-0.1.3.zip
    ERROR: Complete output from command python setup.py egg_info:
    ERROR: Downloading http://pypi.python.org/packages/source/d/distribute/distribute-0.6.14.tar.gz
    Traceback (most recent call last):
      File "/private/var/folders/vm/c9z5j3210zsffd6420jm_r740000gn/T/pip-install-zdue1q2w/pyls/setup_utils/distribute_setup.py", line 143, in use_setuptools
        raise ImportError
    ImportError
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/vm/c9z5j3210zsffd6420jm_r740000gn/T/pip-install-zdue1q2w/pyls/setup.py", line 31, in <module>
        main()
      File "/private/var/folders/vm/c9z5j3210zsffd6420jm_r740000gn/T/pip-install-zdue1q2w/pyls/setup.py", line 11, in main
        distribute_setup.use_setuptools()
      File "/private/var/folders/vm/c9z5j3210zsffd6420jm_r740000gn/T/pip-install-zdue1q2w/pyls/setup_utils/distribute_setup.py", line 145, in use_setuptools
        return _do_download(version, download_base, to_dir, download_delay)
      File "/private/var/folders/vm/c9z5j3210zsffd6420jm_r740000gn/T/pip-install-zdue1q2w/pyls/setup_utils/distribute_setup.py", line 124, in _do_download
        to_dir, download_delay)
      File "/private/var/folders/vm/c9z5j3210zsffd6420jm_r740000gn/T/pip-install-zdue1q2w/pyls/setup_utils/distribute_setup.py", line 193, in download_setuptools
        src = urlopen(url)
      File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 222, in urlopen
        return opener.open(url, data, timeout)
      File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 531, in open
        response = meth(req, response)
      File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 641, in http_response
        'http', request, response, code, msg, hdrs)
      File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 569, in error
        return self._call_chain(*args)
      File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 503, in _call_chain
        result = func(*args)
      File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 649, in http_error_default
        raise HTTPError(req.full_url, code, msg, hdrs, fp)
    urllib.error.HTTPError: HTTP Error 403: SSL is required
    ----------------------------------------
ERROR: Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/vm/c9z5j3210zsffd6420jm_r740000gn/T/pip-install-zdue1q2w/pyls/

**Comment by arjavjain59998** [comment]
error while installing pysl

**Comment by bletham** [comment]
This issue tracker is for a different project, you'll have to find the maintainer for pyls and ask there.

But you might try to pip install distribute first.
