### ISSUE TITLE
Importing Prophet causes pyinstaller to fail

### ISSUE THREAD

**Issue by icedoom888** [facebook/prophet#982]
Hello everyone, 
I have been using Fbprophet in order to build a sales prediction tool.
The project is completed and I would now like to distribute this tool in order to make it accessible to other people, not as experienced with coding/python environments...
Therefore I am using pyinstaller (on Windows) in order to generate an .exe file.

The generated .exe file does not work.
After some debugging i figured that importing **Fbprophet causes pyinstaller to fail.**

The error is the following:

```
Traceback (most recent call last):
File "prova.py", line 2, in <module> 
  from fbprophet import Prophet, make_holidays
File "c:\users\-\appdata\local\conda\conda\envs\times\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 627, in exec_module
    exec(bytecode, module.__dict__)
File "site-packages\fbprophet\__init__.py", line 8, in <module>
File "c:\users\-\appdata\local\conda\conda\envs\times\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 627, in exec_module
    exec(bytecode, module.__dict__)
File "site-packages\fbprophet\forecaster.py", line 17, in <module>
File "c:\users\-\appdata\local\conda\conda\envs\times\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 627, in exec_module
    exec(bytecode, module.__dict__)
File "site-packages\pystan\__init__.py", line 9, in <module>
File "c:\users\-\appdata\local\conda\conda\envs\times\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 627, in exec_module
    exec(bytecode, module.__dict__)
File "site-packages\pystan\api.py", line 15, in <module>
File "c:\users\-\appdata\local\conda\conda\envs\times\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 627, in exec_module
    exec(bytecode, module.__dict__)
File "site-packages\pystan\model.py", line 31, in <module>
ModuleNotFoundError: No module named 'Cython'
```
Does anyone know how to fix this problem? 

Thank you for the help!

**Comment by bletham** [comment]
hm note that the error is coming from inside PyStan. It's entirely possible that you're the first person to ever try to use pyinstaller with a pystan program :-)  Since the C++ toolchain is involved, it may be complicated.

Are you sure that Cython is installed in the environment that pyinstaller is running in? That seems to be what the direct error message is for.

Otherwise I do not have enough experience with pyinstaller to offer any useful advice, maybe someone else here does or else over at the PyStan repo?

**Comment by icedoom888** [comment]
Hello @bletham , thank you for the very prompt response...
I just realized i posted the wrong trace, that was indeed due to the lack of cython in the environment.
The actual problem seems to come from the Cython compiler itself... I was hoping someone tried this before and could help me out.
This is the actual Trace:

```
File "main_with_prices.py", line 5, in <module>
    from nested_CV import nested_CV, find_closest_date, generate_new_dates, compute_accuracy
  File "c:\users\-\appdata\local\conda\conda\envs\times\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 627, in exec_module
    exec(bytecode, module.__dict__)
  File "nested_CV.py", line 5, in <module>
    from fbprophet.diagnostics import cross_validation
  File "c:\users\-\appdata\local\conda\conda\envs\times\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 627, in exec_module
    exec(bytecode, module.__dict__)
  File "site-packages\fbprophet\__init__.py", line 8, in <module>
  File "c:\users\-\appdata\local\conda\conda\envs\times\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 627, in exec_module
    exec(bytecode, module.__dict__)
  File "site-packages\fbprophet\forecaster.py", line 17, in <module>
  File "c:\users\-\appdata\local\conda\conda\envs\times\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 627, in exec_module
    exec(bytecode, module.__dict__)
  File "site-packages\pystan\__init__.py", line 9, in <module>
  File "c:\users\-\appdata\local\conda\conda\envs\times\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 627, in exec_module
    exec(bytecode, module.__dict__)
  File "site-packages\pystan\api.py", line 15, in <module>
  File "c:\users\-\appdata\local\conda\conda\envs\times\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 627, in exec_module
    exec(bytecode, module.__dict__)
  File "site-packages\pystan\model.py", line 32, in <module>
  File "c:\users\-\appdata\local\conda\conda\envs\times\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 627, in exec_module
    exec(bytecode, module.__dict__)
  File "site-packages\Cython\Build\__init__.py", line 1, in <module>
  File "c:\users\-\appdata\local\conda\conda\envs\times\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 627, in exec_module
    exec(bytecode, module.__dict__)
  File "site-packages\Cython\Build\Dependencies.py", line 45, in <module>
  File "c:\users\-\appdata\local\conda\conda\envs\times\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 627, in exec_module
    exec(bytecode, module.__dict__)
  File "site-packages\Cython\Compiler\Main.py", line 28, in <module>
  File "Cython\Compiler\Scanning.py", line 1, in init Cython.Compiler.Scanning
ModuleNotFoundError: No module named 'Cython.Plex'

```

**Comment by wldnjf2000** [comment]
I also saw same error message. After some configuration, I was able to run an exe file in a Windows environment.

try this:
1.Add some packages on hiddenimports in main_with_prices.spec file
             hiddenimports=[
             'Cython.Plex',
             'fbprophet',
             'Cython.Compiler.Lexicon',
             'Cython.Tempita._looper',
             'pystan.plots',
             'pylab'
             ]

2.Execute cmd  pyinstaller main_with_prices.spec

3.Move some folders directly to the distribute folder
- [PYTHON_PATH]/lib/site-packages/Cython/Utility  ->  ~/dist/main_with_prices/Cython/
- [PYTHON_PATH]/lib/site-packages/fbprophet -> ~/dist/main_with_prices/

**Comment by icedoom888** [comment]
@wldnjf2000 Thank you for the help.
Unfortunately I still get the same error after following your suggestions..

**Comment by stevejgoodman** [comment]
@icedoom888 did you resolve the issue? I've just tried to build the same use-case and hit the same problem.

**Comment by icedoom888** [comment]
@stevejgoodman Unfortunately I didn't manage to use Pyinstaller with FBProphet at all.

**Comment by deven-chakraborty** [comment]
@icedoom888 Did you end up finding an alternative?

**Comment by rileymd88** [comment]
@wldnjf2000 Thanks for your instructions. I managed to get a step further but now I receive a different error. Any idea what it could be? I looked and the file it is complaining about is located at Cython/Utiltiy so not sure why it does not find it. Here is the complete error:

`c:\programdata\anaconda3\lib\site-packages\PyInstaller\loader\pyimod03_importers.py:627: MatplotlibDeprecationWarning:
The MATPLOTLIBDATA environment variable was deprecated in Matplotlib 3.1 and will be removed in 3.3.
  exec(bytecode, module.__dict__)
Traceback (most recent call last):
  File "Prophet\__main__.py", line 14, in <module>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "c:\programdata\anaconda3\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 627, in exec_module
    exec(bytecode, module.__dict__)
  File "site-packages\fbprophet\__init__.py", line 8, in <module>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "c:\programdata\anaconda3\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 627, in exec_module
    exec(bytecode, module.__dict__)
  File "site-packages\fbprophet\forecaster.py", line 17, in <module>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "c:\programdata\anaconda3\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 627, in exec_module
    exec(bytecode, module.__dict__)
  File "site-packages\pystan\__init__.py", line 9, in <module>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "c:\programdata\anaconda3\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 627, in exec_module
    exec(bytecode, module.__dict__)
  File "site-packages\pystan\api.py", line 15, in <module>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "c:\programdata\anaconda3\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 627, in exec_module
    exec(bytecode, module.__dict__)
  File "site-packages\pystan\model.py", line 32, in <module>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "c:\programdata\anaconda3\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 627, in exec_module
    exec(bytecode, module.__dict__)
  File "site-packages\Cython\Build\Inline.py", line 17, in <module>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "c:\programdata\anaconda3\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 627, in exec_module
    exec(bytecode, module.__dict__)
  File "site-packages\Cython\Compiler\ParseTreeTransforms.py", line 14, in <module>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "c:\programdata\anaconda3\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 627, in exec_module
    exec(bytecode, module.__dict__)
  File "site-packages\Cython\Compiler\ExprNodes.py", line 30, in <module>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "c:\programdata\anaconda3\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 627, in exec_module
    exec(bytecode, module.__dict__)
  File "site-packages\Cython\Compiler\Nodes.py", line 18, in <module>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "c:\programdata\anaconda3\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 627, in exec_module
    exec(bytecode, module.__dict__)
  File "site-packages\Cython\Compiler\Builtin.py", line 16, in <module>
  File "site-packages\Cython\Compiler\Code.py", line 371, in load
  File "site-packages\Cython\Compiler\Code.py", line 295, in load_utilities_from_file
  File "site-packages\Cython\Utils.py", line 254, in open_source_file
FileNotFoundError: C:\Users\ckg\AppData\Local\Temp\_MEI412922\Cython\Utility\ObjectHandling.c
[36960] Failed to execute script __main__`

**Comment by Rjerk** [comment]
> I also saw same error message. After some configuration, I was able to run an exe file in a Windows environment.
> 
> try this:
> 1.Add some packages on hiddenimports in main_with_prices.spec file
> hiddenimports=[
> 'Cython.Plex',
> 'fbprophet',
> 'Cython.Compiler.Lexicon',
> 'Cython.Tempita._looper',
> 'pystan.plots',
> 'pylab'
> ]
> 
> 2.Execute cmd
> 
> * pyinstaller main_with_prices.spec
> 
> 3.Move some folders directly to the distribute folder
> 
> * [PYTHON_PATH]/lib/site-packages/Cython/Utility  ->  ~/dist/main_with_prices/Cython/
> * [PYTHON_PATH]/lib/site-packages/fbprophet -> ~/dist/main_with_prices/

It works for me!  my .spec file also contains these lines:

```
             datas=[
                  ('./prophet_model.pkl', 'fbprophet/stan_model/'),
                  ('/usr/local/lib64/python3.6/site-packages/Cython/Utility/*.c', 'Cython/Utility/'),
                  ('/usr/local/lib64/python3.6/site-packages/Cython/Utility/*.h', 'Cython/Utility/'),
                  ('/usr/local/lib64/python3.6/site-packages/Cython/Utility/*.pyx', 'Cython/Utility/'),
             ],
             hiddenimports=[
                'gunicorn.glogging', 'gunicorn.workers.sync',
                'fbprophet',
                'Cython.Compiler.Lexicon',
                'Cython.Tempita._looper',
                'pystan.plots',
                'pylab'
             ],
```

**Comment by bletham** [comment]
It looks like there was some success here, so I'm going to close this and hopefully future attempts with pyinstaller can use these tips.
